### ISSUE TITLE
Too many duplicate dependencies in `go.mod`

### ISSUE THREAD

**Issue by DemiMarie** [cloudflare/cloudflare-go#1057]
### Current cloudflare-go version

ebb278509dfcda4fe884939c57be41ac4f9b8f82

### Description

cloudflare-go seems to depend on 35 versions of `cloud.google.com/go`, six of `cloud.google.com/go/bigquery`, five of `github.com/BurntSushi/toml`, and many other duplicate versions.

### Use cases

The main use-case is containers that want to minimize dependency footprints.

### Potential cloudflare-go usage

```go
// N/A, this is a meta issue
```

**Comment by jacobbednarz** [comment]
I gather you're talking about the `go.sum` file in which case, this [is expected](https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using).

**Comment by DemiMarie** [comment]
> I gather you're talking about the `go.sum` file in which case, this [is expected](https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using).

I see.  Does this mean that some dependencies have not updated to newer versions of _their_ dependencies?

If so, this is not a serious problem unless one of those transitive dependencies has a security hole or other major flaw.  It does, however, lead to an unnecessarily bloated binary.

**Comment by jacobbednarz** [comment]
not necessarily. the checksum file contains the hashes of all versions seen for a dependency and it's dependants.

there was some discussion about splitting the package at #1025 to split the runtime/dev dependencies however, it's not a huge priority at the moment.
