### ISSUE TITLE
Two invalid Page Rules actions supported; two others missing 

### ISSUE THREAD

**Issue by OJFord** [cloudflare/cloudflare-go#106]
Currently, pagerules.go:
- Provides `waf` and `mirage` not supported by the API*
- Is missing `automatic_https_rewrites` and `opportunistic_encryption` supported by the API

I'm trying to add page rules  to Terraform (hashicorp/terraform/#11249) because I'd like to use them, and found these missing. (Unfortunately for me `automatic_https_rewrites` was one I personally wanted to use...)

*(Though also, heads-up that if you provide `waf` as the ID, but give it nonsense as the value, it'll tell you it can only be `on` or `off` - as well as the error about it being an invalid setting altogether.)

**Comment by OJFord** [comment]
Actually though, on further inspection it seems as though it'll allow interacting with these, it just won't format nicely (maybe even panic?) if it gets an error to do with one of the action types that don't appear in the prettified name slice?

I'm sorry if I'm misunderstanding things, first time I've used Go.

**Comment by OJFord** [comment]
@elithrar This isn't really about docs, is it? It's [in the code](https://github.com/cloudflare/cloudflare-go/blob/master/pagerules.go#L56-L77).

**Comment by benjvi** [comment]
I've seen some changes in the behaviour wrt these attributes recently (`automatic_https_rewrites` and `opportunistic_encryption`, but also `always_use_https`). Tests using those values in terraform started failing with 400 errors in the last few days - would be good to know precisely which attributes are supported
