### ISSUE TITLE
Stream API Metadata

### ISSUE THREAD

**Issue by Venoox** [cloudflare/cloudflare-go#1062]
### Current cloudflare-go version

v0.48.0

### Description

Add metadata support to the StreamCreateVideoDirectURL function.
According to [Cloudflare Docs](https://developers.cloudflare.com/stream/uploading-videos/direct-creator-uploads/) it is possible by adding "meta" field to the request.

### Use cases

Use case is self explanatory

### Potential cloudflare-go usage

```go
StreamCreateVideoDirectURL(ctx, cloudflare.StreamCreateVideoParameters{
	AccountID:          accountId,
	MaxDurationSeconds: 600,
	Creator:            "test",
	Metadata:           map[string]interface{}{
            "env": "production",
        },
})
```

**Comment by Venoox** [comment]
If it's okay I can implement this and create a PR

**Comment by jacobbednarz** [comment]
sure thing, happy to review a PR for it.
