### ISSUE TITLE
Cannot unmarshal string into int when creating PageRule

### ISSUE THREAD

**Issue by OJFord** [cloudflare/cloudflare-go#108]
I'm seeing a similar issue to #52 but with PageRules, in which they are actually created and I can retrieve fine with curl et al. - but an error is returned:

> error unmarshalling the JSON response: json: cannot unmarshal string into Go value of type int

**Comment by jamesog** [comment]
Thanks, I've reported an internal bug to have this addressed.

**Comment by jamesog** [comment]
The fix was deployed yesterday. Thanks for reporting this :-)

**Comment by OJFord** [comment]
Fantastic, thanks! Should be able to get page rules working in Terraform now :slightly_smiling_face:

**Comment by OJFord** [comment]
This seems to have regressed?

> error unmarshalling the JSON response: json: cannot unmarshal array into Go struct field PageRuleDetailResponse.result of type cloudflare.PageRule

As before, it's particularly annoying because it occurs even on operations that succeed.  c.f. terraform-providers/terraform-provider-cloudflare#12.

**Comment by elithrar** [comment]
@OJFord Looking into this.

**Comment by elithrar** [comment]
OK, I can't reproduce on the current HEAD (e6739d6) - no issues unmarshalling the response from the API:

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/cloudflare/cloudflare-go"
)

func main() {
	client, err := cloudflare.New(
		os.Getenv("CF_API_KEY"),
		os.Getenv("CF_API_EMAIL"),
	)
	if err != nil {
		log.Fatal(err)
	}

	zoneID, err := client.ZoneIDByName(os.Getenv("CF_ZONE_NAME"))
	if err != nil {
		log.Fatal(err)
	}

	rules, err := client.ListPageRules(zoneID)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Fprintf(os.Stdout, "%#v\n", rules)

	rule := cloudflare.PageRule{
		Targets: []cloudflare.PageRuleTarget{cloudflare.PageRuleTarget{
			Target: "url",
			Constraint: struct {
				Operator string `json:"operator"`
				Value    string `json:"value"`
			}{
				Operator: "matches",
				Value:    fmt.Sprintf("%s/*?test=yes", os.Getenv("CF_ZONE_NAME")),
			},
		},
		},
		Actions: []cloudflare.PageRuleAction{
			cloudflare.PageRuleAction{
				ID:    "ip_geolocation",
				Value: "on",
			},
		},
		Priority: 1,
		Status:   "active",
	}

	if err := client.CreatePageRule(zoneID, rule); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by OJFord** [comment]
@elithrar Ah, sorry, it is (at least partly) my fault.

It's reading a single page rule that produces it for me:
```go
pageRule, err := client.PageRule(zoneID, d.Id())
if err != nil {
  return err
}
```
[here](https://github.com/OJFord/terraform-provider-cloudflare/blob/7cd161b44f526d85d1ab0ec13bb24b7b76b9c4ae/cloudflare/resource_cloudflare_page_rule.go#L260) (I've confirmed locally that it is definitely that line with a `fmt.Errorf`.)

Trouble is, `d.Id()` is giving me an empty string at the moment; so I'm looking to fix that. Presumably though cloudflare-go shouldn't be failing with *this* error if I do that? Sounds like it must be not only passing an empty resource ID to the API, but then failing to parse the error response when it does?

**Comment by OJFord** [comment]
Oh, and `d.Id()` is empty because I haven't set the ID, because `CreatePageRule` (unlike e.g. `CreateDNSRecord`) returns only an `error`; not the created object with an ID.

So in order to determine the created ID, I need to enumerate `ListPageRule` before and after creating one? Is there a reason the API looks like this, or is it just an oversight that can be fixed?

(Sorry, I appreciate this is venturing into a separate issue, but I don't want to split the discussion if it's going to be quick to answer. Happy to move this comment to a new issue if you prefer :slightly_smiling_face:)

Thanks again for all your help!

**Comment by elithrar** [comment]
Yes, I think we should fix this (I noticed it too).

Open to a PR, otherwise we’ll create a new issue to track that work.
