### ISSUE TITLE
Not possible to create DNS DS record

### ISSUE THREAD

**Issue by simplysoft** [cloudflare/cloudflare-go#1092]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.50.0

### Go environment

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/<redacted>/Library/Caches/go-build"
GOENV="/Users/<redacted>/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/<redacted>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<redacted>/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.19.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.19.1/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.19.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4v/2yh595t54s12rhpqdlmqj7_r0000gn/T/go-build3518853116=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Expected output

Successful creation 

### Actual output

`Error creating DNS record:  DNS Validation Error (1004)`

### Code demonstrating the issue

-

### Steps to reproduce

```
flarectl  dns create --zone <zone> --type DS --name <name> --content "43094 8 2 EXXXXXXXXXXXXXXXX7B8DF013480382413D6A8A8BXXXXXXXXXX"
```

When entering the exact same data via UI, it works without problems

**Comment by jacobbednarz** [comment]
thanks for raising this issue however `flarectl` is largely in maintenance only mode while we work out what the future of a CLI tool is. as such, if this is something you need and is broken for you, i'd recommend opening a PR addressing it otherwise this is unlikely to get actioned any time in the near future.
