### ISSUE TITLE
StreamVideo.duration - incorrect type

### ISSUE THREAD

**Issue by Venoox** [cloudflare/cloudflare-go#1096]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.51.0

### Go environment

GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/tomaz/Library/Caches/go-build"
GOENV="/Users/tomaz/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tomaz/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tomaz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.18.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tomaz/GolandProjects/vpl_backend/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2s/nnn7f20d4md80pjm0wdgdy340000gn/T/go-build1225515982=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Expected output

Expected to get StreamVideo struct from the method.

### Actual output

json: cannot unmarshal number 5.2 into Go struct field StreamVideo.duration of type int

### Code demonstrating the issue

api.StreamGetVideo(ctx, cloudflare.StreamParameters{
AccountID: accountId,
VideoID: videoId,
})

### Steps to reproduce

api.StreamGetVideo(ctx, cloudflare.StreamParameters{
AccountID: accountId,
VideoID: videoId,
})

**Comment by jacobbednarz** [comment]
the endpoint documents this as an integer so i'll need to confirm which is correct from the service team.

**Comment by Fumler** [comment]
Anything we can do to help here? Getting the same error.

**Comment by danilobuerger** [comment]
@jacobbednarz The duration returned from the api is a float:

![Screenshot 2023-01-22 at 12 36 42](https://user-images.githubusercontent.com/996231/213913755-c8b139e9-bcb6-4f00-bf08-fdc57940db2c.png)

**Comment by Schachte** [comment]
I think we should go ahead and merge:
https://github.com/cloudflare/cloudflare-go/pull/1190

I will get the public docs updated this week so there is parity between API response, cloudflare-go and our documentation. 

Additionally, I think https://github.com/cloudflare/cloudflare-go/pull/1088 from @Venoox will be a good addition I'll help get merged this week as well!

CC: @jacobbednarz 👀
