### ISSUE TITLE
Update TunnelConfig Responses in documentation as well as in SDK

### ISSUE THREAD

**Issue by TroyKomodo** [cloudflare/cloudflare-go#1098]
### Current cloudflare-go version

master

### Description

The cloudflared instance for `UnvalidatedIngressRule`
Can be seen here https://github.com/cloudflare/cloudflared/blob/6be36fa2c52634a2f4a3223f8f7cd1ac331102f9/config/configuration.go#L179

This is the same type returned by the API response.
However the SDK is missing the `OriginRequest` field.

### Use cases

Parity with API & Cloudflared

### Potential cloudflare-go usage

```go
Parity with API & Cloudflared
```

**Comment by vazexqi** [comment]
What is the path to resolution here? I see that there are now at least two pull requests to fix this. I have had to fork my own internal copy of this and used it in my own terraform provider to workaround this. 

@jacobbednarz - Per your comment at https://github.com/cloudflare/cloudflare-go/pull/1099#issuecomment-1266202171, is this more of a get it documented" in the API blocker?

**Comment by asychev** [comment]
Any updates or ETA?

**Comment by mattiaforc** [comment]
Hi everyone, I guess this causes problems when updating the tunnel via SDK, for me it is impossible to create a proper tunnel configuration.
For example, when I create via SDK and then read back (via direct call to the API) the tunnel configurations, this is what I get:
```json
"config": {
  "ingress": [
    {
      "service": "https://grafana.my.domain",
      "hostname": "grafana.my.domain"
    },
    {
      "service": "http_status:404"
    }
  ],
  "warp-routing": {
    "enabled": false
  },
  "originRequest": {}
}
```

Notice that `originRequest` is in the root of `config`. If I create the same exact ingress via web UI, then the tunnel configuration is:

```json
"config": {
  "ingress": [
    {
      "service": "https://grafana.my.domain",
      "hostname": "grafana.my.domain",
      "originRequest": {}
    },
    {
      "service": "http_status:404"
    }
  ],
  "warp-routing": {
    "enabled": false
  }
}
```
The `originRequest` is in the specific ingress. 

The former does not work, although it is considered valid from Cloudflare API (it gives me back a successful response), it won't work when trying to visit `grafana.my.domain`, it always get me to Cloudflare's host not reachable page (522), whilst the latter works perfectly fine.

**Comment by mattiaforc** [comment]
Nevermind - the SDK is not aligned to the APIs but this was not the problem of my tunnel; I just realized that the web UI also automatically creates a CNAME record pointing to the tunnel, while my code was only updating the tunnel!
