### ISSUE TITLE
Incomplete custom hostname (and custom hostname ssl) status constants

### ISSUE THREAD

**Issue by rcj4747** [cloudflare/cloudflare-go#1109]
### Current cloudflare-go version

v0.52.0

### Description

[custom_hostname.go](https://github.com/cloudflare/cloudflare-go/blob/master/custom_hostname.go) has definitions for a subset of `CustomHostnameStatus` values (`pending`, `active`, `moved`, `deleted`, & `blocked`) but this is incomplete based on the API's [custom hostname object definition](https://api.cloudflare.com/#custom-hostname-for-a-zone-properties). Missing values are: `active_redeploying, pending_deletion, pending_blocked, pending_migration, pending_provisioned, test_pending, test_active, test_active_apex, test_blocked, test_failed, provisioned`

Additionally, there are no constants for the `CustomHostnameSSL.Status` which is defined as a `string`.  Valid values per the API doc are `initializing, pending_validation, deleted, pending_issuance, pending_deployment, pending_deletion, pending_expiration, expired, active, initializing_timed_out, validation_timed_out, issuance_timed_out, deployment_timed_out, deletion_timed_out, pending_cleanup, staging_deployment, staging_active, deactivating, inactive, backup_issued, holding_deployment`

### Use cases

A user of cloudflare-go would like to the status value in a custom hostname object (and custom hostname SSL object) using the constants defined in the go library without adding hard-coded strings to their code.

### Potential cloudflare-go usage

```go
switch currentRecord.Status {
	case cloudflare.MOVED, cloudflare.DELETED:
		// do things
	// !! ACTIVE_REDEPLOYING is not defined today
	case cloudflare.ACTIVE, cloudflare.ACTIVE_REDEPLOYING, cloudflare.PENDING:
		// do things
	case cloudflare.BLOCKED:
		// do things
```

**Comment by jacobbednarz** [comment]
closing this one off as these are present in v2 (https://github.com/cloudflare/cloudflare-go/blob/v2/custom_hostnames/customhostname.go#L432) however, we won't be backporting them to v0 at this point in time. 

if they are missing some values, we should raise a support ticket or chat to your account team about raising a ticket for the service team to update the enum value used here.
