### ISSUE TITLE
X-Auth-Key header should be redacted in debug logs

### ISSUE THREAD

**Issue by troymjones** [cloudflare/cloudflare-go#1143]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.55.0

### Go environment

provider.terraform-provider-cloudflare_v3.29.0

### Expected output

Debug output should redact any sensitive API keys from debug, trace, etc logs.

2022-12-08T00:14:18.105Z [DEBUG] provider.terraform-provider-cloudflare_v3.29.0: Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/accounts/dabb2c6d3e5582260ef1a0dd67fb870b/workers/scripts/indeed-api-gateway-dev-worker-script/bindings HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.3.4 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.29.0
Content-Type: application/json
X-Auth-Email: api-platforms-cloudflare-automation@indeed.com
X-Auth-Key: REDACTED
Accept-Encoding: gzip

### Actual output

Debug output includes the X-Auth-Key header in plaintext. When combined with Cloudflare's terraform provider, this can expose personal as well as service account global API keys.

2022-12-08T00:14:18.105Z [DEBUG] provider.terraform-provider-cloudflare_v3.29.0: Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/accounts/dabb2c6d3e5582260ef1a0dd67fb870b/workers/scripts/indeed-api-gateway-dev-worker-script/bindings HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.3.4 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.29.0
Content-Type: application/json
X-Auth-Email: api-platforms-cloudflare-automation@indeed.com
X-Auth-Key: [MY API KEY WAS SHOWN HERE]
Accept-Encoding: gzip

### Code demonstrating the issue

All headers are logged here without any change or attempt to redact sensitive keys:

https://github.com/cloudflare/cloudflare-go/blob/d7efda7b30549c48e7e69cf9b1b76c518138dfdc/cloudflare.go#L259

### Steps to reproduce

Setting logging to DEBUG, or in my case, setting TF_LOG=DEBUG environment variable in terraform.

**Comment by troymjones** [comment]
Here is an example of what Datadog does to redact sensitive keys.

Output:
datadog_monitor.api_gateway_worker_errors: Refreshing state... [id=104643268]
2022-12-08T00:14:18.565Z [INFO]  provider.terraform-provider-datadog_v3.16.0: 2022/12/08 00:14:18 [DEBUG] Waiting for state to become: [success]: timestamp=2022-12-08T00:14:18.565Z
2022-12-08T00:14:18.566Z [INFO]  provider.terraform-provider-datadog_v3.16.0: 2022/12/08 00:14:18 
GET /api/v1/monitor/104643268 HTTP/1.1
Host: api.datadoghq.com
User-Agent: terraform-provider-datadog/3.16.0 (terraform 2.10.1; terraform-cli 1.3.4) datadog-api-client-go/2.3.1 (go go1.17.13; os linux; arch amd64)
Accept: application/json
Dd-Api-Key: REDACTED
Dd-Application-Key: REDACTED
Accept-Encoding: gzip

Here is the code that appears to set it as REDACTED: https://github.com/DataDog/datadog-api-client-go/blob/1c6033006d72db906faef2daeecda0ccd20cb48e/api/datadog/client.go#L107

**Comment by jacobbednarz** [comment]
thanks but this isn't something we'll tackle in this library in the immediate future. 

I'll add it as a request for our next iteration of the Go client.

**Comment by jacobbednarz** [comment]
also, just a note, the sections linked above in this library are not used for Terraform output; only for library debug logs. the output for the Terraform output comes from it's own logger instance.

**Comment by jacobbednarz** [comment]
reopening this as I've found a way we can achieve this within Terraform (thanks to some new internals!) without the major overhaul we explored in the past. 

should be within the next couple of releases if al goes to plan.
