### ISSUE TITLE
Complete removal of the global `api.AccountID`

### ISSUE THREAD

**Issue by favonia** [cloudflare/cloudflare-go#1154]
### Current cloudflare-go version

0.57

### Description

Currently, only DNS firewall, Railgun, and `ZoneIDByName` can depend on the global `api.AccountID` (possibly via `api.userBaseURL`). I wonder if it is in the plan to completely stop using the global `api.AccountID` even outside the Terraform-related API. The current interface is slightly confusing because it is unclear when `api.AccountID` is used. If it is indeed planned to remove `api.AccountID`, I hope the field and the setter will soon be deprecated and then removed.

### Use cases

A clear indication that `api.AccountID` will not be used (if that is the plan).

### Potential cloudflare-go usage

```go
// This does not address other endpoints related to Railgun
type RailgunListOptions struct {
	AccountID string
	Direction string
}

// This does not address other endpoints related to DNS Firewall
type DNSFirewallUserAnalyticsOptions struct {
	AccountID string
	Metrics   []string
	Since     *time.Time
	Until     *time.Time
}
```

**Comment by jacobbednarz** [comment]
Yes, once 4.x of the Terraform provider is cut (cloudflare/terraform-provider-cloudflare#1646) a couple of these methods will also go with it.
