### ISSUE TITLE
Cant't execute DNSRecord

### ISSUE THREAD

**Issue by rluisr** [cloudflare/cloudflare-go#118]
Hi cloudflare team.

```go
api, err := cloudflare.New(os.Getenv("CF_API_KEY"), os.Getenv("CF_API_EMAIL"))
if err != nil {
	panic(err)
}

res, err := api.DNSRecord("b5b82f8d72414f849bd96a50e6228ece", "645577699")
if err != nil {
	panic(err)
}
```
I executed this code, error occurred.

`panic: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":7003,\"message\":\"Could not route to \\/zones\\/b5b82f8d72414f849bd96a50e6228ece\\/dns_records\\/645577699, perhaps your object identifier is invalid?\"},{\"code\":7000,\"message\":\"No route for that URI\"}],\"messages\":[],\"result\":null}"`

I don't know how to solve this.

Go 1.8
OS : Windows 10 / CentOS 7.3

**Comment by jamesog** [comment]
Hello @rluisr. The record ID you're giving to `DNSRecord` isn't correct. It should be a 32-byte hex string, similar to the zone ID.

Try listing all records with `DNSRecords` to get the ID of the record you're after. The [documentation](https://godoc.org/github.com/cloudflare/cloudflare-go#API.DNSRecords) has examples on how you can filter the results.

**Comment by rluisr** [comment]
Hello @jamesog 
Thanks your reply and solve this problem.
