### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by pascalandy** [cloudflare/cloudflare-go#121]
Is it possible to an `healthcheck` on the DNS a domain is pointing to?

Thank you!

**Comment by Tenzer** [comment]
Are you meaning in relation to monitors for a load balancing setup? https://api.cloudflare.com/#load-balancer-monitors-create-a-monitor

**Comment by pascalandy** [comment]
Eventually yes, but now I just want to do a healthcheck a my VPSs

**Comment by elithrar** [comment]
Hey @pascalandy - Cloudflare doesn't yet offer standalone health-checks. We (as of next week) can do failover and/or load balancing (using built-in health-checks & alerts), but not *just* the health check part.

**Comment by pascalandy** [comment]
OK make sense. I did request an account for this new LB feature. Can't wait to try it :)

**Comment by elithrar** [comment]
@pascalandy Email me - msilverlock /at cloudflare.com - and I can turn on the ability to purchase it today (a few days earlier than everyone else) :)

(closing this ticket out for now)
