### ISSUE TITLE
Will the zero value of UpdateDNSRecordParams keep existing DNS record tags?

### ISSUE THREAD

**Issue by favonia** [cloudflare/cloudflare-go#1224]
### Current cloudflare-go version

0.61.0

### Description

To make it possible to clear DNS record tags, version 0.61.0 removed the flag `omitempty` for the field `tags` for serializing `UpdateDNSRecordParams` into a JSON object (#1196). However, I wonder if setting the field `tags` to `nil` (which will be serialized as `null`) will keep existing tags.

### Use cases

Before 0.61.0, the zero value of `UpdateDNSRecordParams` will preserve existing settings, but after 0.61.0, I don't see that guarantee from the API documentation.

### Potential cloudflare-go usage

```go
// Updating IP

params := UpdateDNSRecordParams{
	ID:      id,
	Content: new_ip,
}

UpdateDNSRecord(ctx, ZoneIdentifier(zone), params)
```

### References

#1196

**Comment by jacobbednarz** [comment]
yes, it does despite not being explictly called out in the API.

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/cloudflare/cloudflare-go"
)

func main() {
	api, err := cloudflare.New(os.Getenv("CLOUDFLARE_API_KEY"), os.Getenv("CLOUDFLARE_EMAIL"))
	if err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()

	r1, _ := api.CreateDNSRecord(ctx, cloudflare.ZoneIdentifier(os.Getenv("CLOUDFLARE_ZONE_ID")), cloudflare.CreateDNSRecordParams{
		Name:    "foo",
		Type:    "A",
		Content: "1.2.3.4",
		Tags:    []string{"a", "b"},
	})

	fmt.Println("create: ", r1.Result.Tags)

	api.UpdateDNSRecord(ctx, cloudflare.ZoneIdentifier(os.Getenv("CLOUDFLARE_ZONE_ID")), cloudflare.UpdateDNSRecordParams{
		ID:   r1.Result.ID,
		Tags: nil,
	})

	r2, _ := api.GetDNSRecord(ctx, cloudflare.ZoneIdentifier(os.Getenv("CLOUDFLARE_ZONE_ID")), r1.Result.ID)
	fmt.Println("after update: ", r2.Tags)

	api.DeleteDNSRecord(ctx, cloudflare.ZoneIdentifier(os.Getenv("CLOUDFLARE_ZONE_ID")), r1.Result.ID)
}
```

it's not the most Go-like solution but it works. we can potentially make it a pointer but if it works as is, i'm less inclined to change it until we change all the types to pointers later in the library revamp.

**Comment by favonia** [comment]
@jacobbednarz Thank you! :heart: (I was not able to verify this with my current plan.)

**Comment by jacobbednarz** [comment]
apologies for missing your comment on the linked PR. once PRs are released and that note for new issues is added, i automatically unsubscribe to avoid a bunch of fly-by comments post release.

**Comment by jacobbednarz** [comment]
let me know if you need access to a testing account for this sort of thing and i can arrange one to be setup given the amount of help you've provided firming up the DNS portions of this library.
