### ISSUE TITLE
Change UpdateDNSRecord to also return the DNSRecordResponse 

### ISSUE THREAD

**Issue by joaoafonsopereira** [cloudflare/cloudflare-go#1239]
### Current cloudflare-go version

v0.63.0

### Description

Change [UpdateDNSRecord](https://github.com/cloudflare/cloudflare-go/blob/e41c0a2a615b8ee946b5ddf3698fb2181de0485d/dns.go#L230) return type from just `error` to `(*DNSRecordResponse, error)` (and consequently returning the `DNSRecordResponse` that is [already being received](https://github.com/cloudflare/cloudflare-go/blob/e41c0a2a615b8ee946b5ddf3698fb2181de0485d/dns.go#L247))

The proposed change would make this method consistent with:
- the [update DNS Record](https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-update-dns-record) endpoint being hit, which returns the updated record in its response
- [CreateDNSRecord](https://github.com/cloudflare/cloudflare-go/blob/e41c0a2a615b8ee946b5ddf3698fb2181de0485d/dns.go#L130) -- similar to how [CreateWorkerRoute](https://github.com/cloudflare/cloudflare-go/blob/e41c0a2a615b8ee946b5ddf3698fb2181de0485d/workers_routes.go#L31)'s return type is consistent with [UpdateWorkerRoute](https://github.com/cloudflare/cloudflare-go/blob/e41c0a2a615b8ee946b5ddf3698fb2181de0485d/workers_routes.go#L137)

### Use cases

Handling `CreateDNSRecord` and `UpdateDNSRecord`'s responses in a uniform way.

In my particular case, I need to create/update a DNS record whenever I create/update a worker route (in order to automatically generate a new certificate, as I'm using [Total TLS](https://developers.cloudflare.com/ssl/edge-certificates/additional-options/total-tls/)). 
Since these pairs of methods (`Create/UpdateDNSRecord` and `Create/UpdateWorkerRoute`) are somewhat similar, it would be nice for their signatures/return types to be consistent with each other, enabling one to write code that mirrors those similarities.

### Potential cloudflare-go usage

```go
// the main goal is that this function returns a cloudflare.DNSRecord, regardless of whether
// it was created or updated.
func createOrUpdateDNSRecord(ctx context.Context, someParam SomeParam) (cloudflare.DNSRecord, error) {
        // look up dns record somewhere, based on some parameter that doesn't matter
        dnsRecord := findDnsRecord(someParam) 

	proxied := true

	var resp *cloudflare.DNSRecordResponse
	var err error
	if dnsRecord == nil {
		resp, err = cfApi.CreateDNSRecord(ctx, cloudflare.ZoneIdentifier(ZONE_ID), cloudflare.CreateDNSRecordParams{...})
	} else {
		resp, err = cfApi.UpdateDNSRecord(ctx, cloudflare.ZoneIdentifier(ZONE_ID), cloudflare.UpdateDNSRecordParams{...})
	}
        return resp.Result, err
}
```

**Comment by jacobbednarz** [comment]
👋 we're in the process of making the Go library parameters and return types more consistent with our end goal outlined at https://github.com/cloudflare/cloudflare-go/blob/master/docs/experimental.md (recommend taking a look to get the full picture).

i'm open to updating the method signature for `Update` however, the return type will need to be `DNSRecord`, not `DNSRecordResponse` as we are doing for the `Create` operation.

**Comment by joaoafonsopereira** [comment]
👋 
Sorry, missed that document!

No worries there, the essence of this proposal is to make `Update` and `Create`'s signatures consistent.
Thank you for the quick response, and let me know if you want me to submit a PR implementing those changes.

**Comment by jacobbednarz** [comment]
This isn't high on my priority list so if it is something you want, you're welcome to submit a PR.
