### ISSUE TITLE
Image direct upload V2

### ISSUE THREAD

**Issue by Venoox** [cloudflare/cloudflare-go#1248]
### Current cloudflare-go version

v0.63.0

### Description

https://developers.cloudflare.com/api/operations/cloudflare-images-create-authenticated-direct-upload-url-v-2

Cloudflare has a version 2 of image direct upload which supports additional parameters like signed urls, metadata...
If approved I can make the code changes and submit a PR.

### Use cases

This will implement the API

### Potential cloudflare-go usage

```go
Make a new function CreateImageDirectUploadURLV2 to keep backward compatibility
```

**Comment by bbbshah** [comment]
Any plans to support this? It seems like a such a common use-case.
