### ISSUE TITLE
flarectl dns update should handle empty 'content' field more informatively

### ISSUE THREAD

**Issue by catatsuy** [cloudflare/cloudflare-go#1255]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.64.0

### Go environment

it is not related to 'go env'

### Expected output

An error message indicating that the 'content' field cannot be left empty during the 'update' operation.

### Actual output

No error is produced when the 'content' field is empty during the 'update' operation.

### Code demonstrating the issue

nothing

### Steps to reproduce

```go
func dnsCreate(c *cli.Context) error {
	if err := checkFlags(c, "zone", "name", "type", "content"); err != nil {
		return err
	}
```

```go
func dnsUpdate(c *cli.Context) error {
	if err := checkFlags(c, "zone", "id"); err != nil {
		fmt.Println(err)
		return err
	}
```

**Comment by jacobbednarz** [comment]
thanks for the issue @catatsuy. unfortunately `flarectl` is pretty much in maintenance only mode at the moment so until we release the next iteration of the CLI tooling, we're not actively spending time chasing down bugs like this one.

i'll add this as a note for the next iteration but for now, i'll close this off as unresolved.
