### ISSUE TITLE
Duration type conversion was dropped (mistakenly?)

### ISSUE THREAD

**Issue by ferhatelmas** [cloudflare/cloudflare-go#1259]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.64.0

### Go environment

Not needed

### Expected output

Not needed

### Actual output

Not needed

### Code demonstrating the issue

Not needed

### Steps to reproduce

Not needed

### References

It's not used in the code base but since was exported at some point and dropped without mentioning and only type doesn't have both directions, it might be a good idea to add it back.
Related change: [`f65e02d` (#837)](https://github.com/cloudflare/cloudflare-go/pull/837/commits/f65e02dc86d91b5383858c18d6406a5752f13454#diff-ddf345f689b80697d535f7288c6333fda4df3ad1eea91de21abcb7d78d8f2643L927)

On the other hand, if breaking change is possible, generics might be used to simplify convert types.

**Comment by jacobbednarz** [comment]
this was intentionally dropped (in the following release that it was introduced) as it was causing issues in the experimental client.

there are no plans at the moment to add it back and break the type aliasing. we don't use generics anywhere currently so i'm not particularly concerned about swapping to generics (that may change in the future once we start replacing other functionality with that pattern).
