### ISSUE TITLE
The library should understand 204, No Content responses

### ISSUE THREAD

**Issue by ElvinEfendi** [cloudflare/cloudflare-go#126]
`DELETE` request to the custom hostname endpoint(https://api.cloudflare.com/#custom-hostname-for-a-zone-delete-a-custom-hostname-and-any-issued-ssl-certificates-) returns an empty(incorrect JSON) response with the status of `204`. According to the API doc it should return a correct JSON:
```
{
  "id": "<id of deleted custom hostname>"
}
```
Assuming the API doc for this specific case is outdated, `makeRequest` should be able to handle `204` responses instead of returning an error.

**Comment by ElvinEfendi** [comment]
I noticed that `204` is not documented at https://api.cloudflare.com/#getting-started-responses either.

**Comment by jamesog** [comment]
Thanks @ElvinEfendi, I'll open an internal bug for this to be checked.

**Comment by jamesog** [comment]
Hi @ElvinEfendi, our API team have made changes to this endpoint so it returns 200 now.

**Comment by ElvinEfendi** [comment]
Hey @jamesog, verified that it returns 200. Thanks!
