### ISSUE TITLE
How to filter custom hostnames based on SSL status

### ISSUE THREAD

**Issue by ElvinEfendi** [cloudflare/cloudflare-go#130]
Does the custom hostnames endpoint support filtering based on `ssl[status]` attribute? I tried
```
/zones/<zone_id>/custom_hostnames?page=7&per_page=50&ssl=status%3Dactive
```
But it does not seem to work. The same idea works for `hostname` though.

**Comment by elithrar** [comment]
It does not. Let me raise this internally.

**Comment by Smadarl** [comment]
The API does allow sorting based on ssl_status, but I don't see a way to do that with this package yet.  Could that be a feature request?
