### ISSUE TITLE
Support custom waf rules creation

### ISSUE THREAD

**Issue by stafot** [cloudflare/cloudflare-go#1309]
### Current cloudflare-go version

latest

### Description

In my understanding and correct if I am wrong currently cloudflare-go doesn't support the creation of custom waf rules and and WAFExpression, WAFAction as described in the [Cloudflare developers API](https://developers.cloudflare.com/waf/custom-rules/create-api/#create-a-custom-rule)

### Use cases

To be able to add on my ruleset specific access restrictions

### Potential cloudflare-go usage

```go
// WAFRule represents the WAF rule structure
type WAFRule struct {
	ID         string    `json:"id,omitempty"`
	Paused     bool      `json:"paused"`
	Description string   `json:"description"`
	Filter     WAFFilter `json:"filter"`
}

// WAFFilter represents the WAF filter structure
type WAFFilter struct {
	ID          string          `json:"id,omitempty"`
	Paused      bool            `json:"paused"`
	Expressions []WAFExpression `json:"expressions"`
}

// WAFExpression represents the WAF expression structure
type WAFExpression struct {
	Operator    string   `json:"operator"`
	ZoneID      string   `json:"zone_id,omitempty"`
	Field       string   `json:"field"`
	Value       string   `json:"value,omitempty"`
	IPRanges    []IPRange `json:"ip_ranges,omitempty"`
}

	wafRule := WAFRule{
		Paused:     false,
		Description: fmt.Sprintf("Allow listed IP ranges for domain: %s", domain),
		Filter: WAFFilter{
			Paused: false,
			Expressions: []WAFExpression{
				{
					Operator: "or",
					Field:    "ip",
					IPRanges: createIPRanges(ipRanges),
				},
			},
		},
	}
```

**Comment by jacobbednarz** [comment]
cloudflare-go does already support the edge rules engine based WAF. you can see the methods in [rulesets.go](https://github.com/cloudflare/cloudflare-go/blob/master/rulesets.go).

if you want to see usage, you can either check out the test files or terraform provider resources that rely on these methods.

**Comment by stafot** [comment]
@jacobbednarz Thanks for your answer, I checked the tests and look helpful. Could you please also share the abovementioned terraform-provider link to check the implementation there tooo?
