### ISSUE TITLE
Possible values of `status` attribute of `ssl` in custom hostnames endpoint

### ISSUE THREAD

**Issue by ElvinEfendi** [cloudflare/cloudflare-go#131]
I could not find the full list of available `ssl` statuses in https://api.cloudflare.com/#custom-hostname-for-a-zone-properties. Can you point me to a doc or just list the full list statuses with their meaning?

**Comment by elithrar** [comment]
Hey Elvin - I've bugged the engineering team running this to update their
schemas/republish to api.cloudflare.com so it reflects the possible values.

In the meantime, the possible values:

```
"null"
"deleted"
"active"
"pending_issuance"
"pending_validation"
pending_deployment"
"initializing"
```

Let me know if you need more details.

**Comment by handrews** [comment]
@elithrar, @ElvinEfendi: To see the documented set of values, click the "Show Definition" button under "Custom Hostname of a Zone"'s object definition section.

In that table, in the third row ("ssl") look at the last line of the description column, under the example value.  There is a "Show definition >>" link there.  When you click it, it displays the fields in the ssl object as a sub-table.

The first row of the sub-table is "status", and the list of values appears in the "constraints" column.  Note that "read only" is another constraint, not a value.  We should really make that more obvious.  It would probably also be good to make the "Show definition>>" link a button to make it more visible.

**Comment by ElvinEfendi** [comment]
Thanks for quick reply @elithrar, @handrews! I found it in the page after following the above steps.

> It would probably also be good to make the "Show definition>>" link a button to make it more visible.

I was expecting "show definition" button to have the same appearance everywhere, I guess this was the main thing made it hard for me to find it there :)

**Another related question**
Do you generate a webhook when ssl status changes? Or is the busy polling only solution?

**Comment by elithrar** [comment]
Today: pull/polling only.

I'll raise this with the team working on this as not the first to ask about
webhooks (no promises on timeframe).

**Comment by handrews** [comment]
@elithrar could you please file an api doc ticket on the "show definition" button appearance thing?  I'm heading out of town on vacation in about an hour and am not on VPN, and I don't want to forget about it.
