### ISSUE TITLE
Feature request: Wildcard and multi-domain support in Cloudflare Access

### ISSUE THREAD

**Issue by vcajes** [cloudflare/cloudflare-go#1310]
### Current cloudflare-go version

latest

### Description

Wildcard and multi-domain support in Cloudflare Access (released by Cloudflare in March/2023)

https://blog.cloudflare.com/access-wildcard-and-multi-hostname/

The Cloudflare UI already allows to create multiple domains within a single Cloudflare Access application, but this is not supported yet on Terraform.

I can see that the current Cloudflare UI sends the "self_hosted_domains" parameter (array of strings), so if you can support this field on the API, we will be able to add support for it on the Terraform Cloudflare provider.

### Use cases

- Allow API and Frontend apps behind Cloudflare Access to communicate with each other (as described on your own blog post)
- Allow us to setup this with Terraform 

### Potential cloudflare-go usage

```go
Terraform integration, currently missing the "self_hosted_domains" field:

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application
```

### References

https://blog.cloudflare.com/access-wildcard-and-multi-hostname/

**Comment by jacobbednarz** [comment]
already supported via https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#480-14th-june-2023
