### ISSUE TITLE
`flarectl` to echo API request instead of command run

### ISSUE THREAD

**Issue by ww7** [cloudflare/cloudflare-go#1323]
### Current cloudflare-go version

v0.70.0

### Description

`flarectl` simplify routine, but for portable Bash scripting better to use `curl` requests to API

`flarectl` can help to compile API request that can be quickly used in scripting

I'm requesting a new `GLOBAL OPTION` that print API request to console (e.g. as `curl` example)

### Use cases

Portable scripts

### Potential cloudflare-go usage

```go
For quick scripts developing, API requests verify and `flarectl` troubleshooting
```

**Comment by jacobbednarz** [comment]
flarectl is in maintenance only mode at this point while we work out what the next generation of our SDKs look like. configuration like this should be automatically included in that so i'm closing this off since we won't be taking any action here.
