### ISSUE TITLE
Handle more than 10k KVs in `WriteWorkersKVEntries` and `DeleteWorkersKVEntries` methods 

### ISSUE THREAD

**Issue by sbs2001** [cloudflare/cloudflare-go#1324]
### Current cloudflare-go version

v0.70.0

### Description

The  underlying APIs for `WriteWorkersKVEntries` and   `DeleteWorkersKVEntries` support 10k items max. It'd be great if the go code would batch the inout if more than 10k items are provided. Ofcourse we can do this manually in our code, but this library already does something like this in case of IPlist methods.

If more than 10k items are provided to these methods, we get the error:

```
bulk put: 'received 12762 key/value pairs, but max allowed per request is: 10000' (10012) 
```

### Use cases

We're working on newer version of https://github.com/crowdsecurity/cs-cloudflare-bouncer which would be based on workers and worker kv instead of IP lists. We'd need to update the KV with lots and lots of IPs.  

### Potential cloudflare-go usage

```go
No change, the batching would have no user facing changes.
```

**Comment by jacobbednarz** [comment]
thanks for the suggestion but this is something we'd look to have supported in the service and not in the client library if it was to be a thing. 

i'm closing this out now as something we won't do but pass the feedback onto the service team to consider if they would ever add it.
