### ISSUE TITLE
How do I set up AMP-related settings using the api?

### ISSUE THREAD

**Issue by tianchengdemo** [cloudflare/cloudflare-go#1332]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.72.0

### Go environment

set GO111MODULE=on
set GOARCH=amd64  
set GOBIN=        
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.5
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\Users\Administrator\GolandProjects\cloudflare_add\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local
\Temp\go-build3539032895=/tmp/go-build -gno-record-gcc-switches

### Expected output

I want to use the api to set a switch for AMP to display the real pages of the site, but I can't seem to set it!

### Actual output

error unmarshalling the JSON response error body: unexpected end of JSON input

This is the error message from the api

### Code demonstrating the issue

_, err := api.UpdateZoneSetting(ctx, cloudflare.ZoneIdentifier(DomainInfos.ZoneID), cloudflare.UpdateZoneSettingParams{
		Name:       "sxg",
		PathPrefix: "amp",
		Value:      "true",
	})

### Steps to reproduce

https://dash.cloudflare.com/api/v4/zones/d2322619ccde42e08743987743091f4b/amp/sxg PUT
This is the URL set by the website

How do I use the API to achieve this?

**Comment by jacobbednarz** [comment]
AMP signed exchanges are not publicly documented or supported in the SDKs at this point.
