### ISSUE TITLE
SDK inconsistency in zone vs record APIs

### ISSUE THREAD

**Issue by ideahitme** [cloudflare/cloudflare-go#135]
**Description:**

Zones sdk code does not retrieve all zones, only the first page. 
DNS records sdk code does retrieve all records

**Details:**
This is a snippet from `zone.go` `ListZones(z ...string)` method. 

```go
		// TODO: Paginate here. We only grab the first page of results.
		// Could do this concurrently after the first request by creating a
		// sync.WaitGroup or just a channel + workers.
		res, err = api.makeRequest("GET", "/zones", nil)
		if err != nil {
			return []Zone{}, errors.Wrap(err, errMakeRequestError)
		}
		err = json.Unmarshal(res, &r)
		if err != nil {
			return []Zone{}, errors.Wrap(err, errUnmarshalError)
		}
		zones = r.Result
```

As noted in TODOs it does not implement pagination, moreover the struct where JSON is unmarshaled does not define (as opposed to response from dns records API): 

```go
// ResultInfo contains metadata about the Response.
type ResultInfo struct {
	Page       int `json:"page"`
	PerPage    int `json:"per_page"`
	TotalPages int `json:"total_pages"`
	Count      int `json:"count"`
	Total      int `json:"total_count"`
}
```

1. I would assume `ResultInfo` is still part of the http response from `"https://api.cloudflare.com/client/v4/zones` and can be retrieved ? 
2. Are u planning to have this fixed, I could create a PR if it is not yet planned ?

**Comment by Tenzer** [comment]
Related issues: #6 and #4.

**Comment by ideahitme** [comment]
As per official documentation https://api.cloudflare.com/#zone-list-zones it has 
```
type ResultInfo struct {
	Page       int `json:"page"`
	PerPage    int `json:"per_page"`
	TotalPages int `json:"total_pages"`
	Count      int `json:"count"`
	Total      int `json:"total_count"`
}
```
as json, so in theory it should be pretty simple to implement

**Comment by ideahitme** [comment]
@Tenzer I see,  feel free to close this if you think it is necessary
