### ISSUE TITLE
ImageDetailsResponse JSON Unmarshaling

### ISSUE THREAD

**Issue by sank3** [cloudflare/cloudflare-go#1358]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.74.0

### Go environment

GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/current/Library/Caches/go-build"
GOENV="/Users/current/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/current/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/current/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/current/project/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-

### Expected output

One of the valid errors from `UploadImage` method of github.com/cloudflare/cloudflare-go@v0.74.0/images.go to line 160.

Valid errors - https://developers.cloudflare.com/api/operations/cloudflare-images-upload-an-image-via-url?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcloudflare%2Fapi-schemas%2Fmain%2Fopenapi.yaml#Request

### Actual output

error unmarshalling the JSON response error body: invalid character 'E' looking for beginning of value

### Code demonstrating the issue

//input data
token:="my token"
accountID:="my_account_id"
url:="https://example.com/valig_image.jpg"

api, err := cloudflare.NewWithAPIToken(token)
	if err != nil {
		return err
	}

rc := cloudflare.AccountIdentifier(accountID)
params := cloudflare.UploadImageParams{
URL:      url,
}

img, err := c.api.UploadImage(ctx, rc, params)
if err != nil {
log.WithError(err).Error("failed to upload image to cloudflare")
}

### Steps to reproduce

The issue is coming randomly when the Cloudflare API returns an error a string instead of JSON when uploading an image.

The error is produced by github.com/cloudflare/cloudflare-go@v0.74.0/images.go line 196.

**Comment by jacobbednarz** [comment]
what is the full response you are seeing here?

**Comment by sank3** [comment]
Since I am behind the Cloudflare SDK, I do no have full visibility of the result. The error returned by SDK is this-
`error unmarshalling the JSON response error body: invalid character 'E' looking for beginning of value`

**Comment by jacobbednarz** [comment]
you can either use a MITM proxy or use `cloudflare.Debug(true)` as part of your [client instantiation](https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L108) to output the HTTP interactions.

**Comment by sank3** [comment]
Thank you for the debug suggestion.
Here is the root cause of JSON marshaling failing-

If an image URL is passed in the UploadImageParams which does not exist (the image hosting server returns 404), Cloudflare SDK fails to marshal the API response.
The actual error from Cloudflare API is not JSON, its a string - 

`ERROR 5454: Error during the fetch, code: 404, message: <!doctype html><html></html>`

**Comment by jacobbednarz** [comment]
if you can provide the entirety of the output (including HTTP headers with credentials redacted) I can take it to the team and investigate why this isn't returning the v4 envelope it should be.

**Comment by sank3** [comment]
### Request
```
POST /client/v4/accounts/5af68dbe390a3ebd25c977e8bcda1d3c/images/v1 HTTP/1.1
Host: api.cloudflare.com
User-Agent: cloudflare-go/v4
Content-Length: 343
Accept: application/json
Authorization: Bearer [redacted]
Content-Type: multipart/form-data; boundary=6035237d791695e6d2a3e3992a1eaafd4769911959fc475eddd666b6790d
Accept-Encoding: gzip

--6035237d791695e6d2a3e3992a1eaafd4769911959fc475eddd666b6790d
Content-Disposition: form-data; name="url"

https://example.com/image_does_not_exist.jpeg
--6035237d791695e6d2a3e3992a1eaafd4769911959fc475eddd666b6790d
Content-Disposition: form-data; name="metadata"
{}

--6035237d791695e6d2a3e3992a1eaafd4769911959fc475eddd666b6790d--
```

### Response:
I see the body is truncated, but only this much is being read by the `makeRequestWithAuthTypeAndHeadersComplete` method of SDK.

```
HTTP/2.0 404 Not Found
Cache-Control: no-cache
Cf-Cache-Status: DYNAMIC
Cf-Images: err=5454
Cf-Ray: 7f2e960379aa46c2-BOM
Content-Type: text/plain;charset=utf-8
Date: Mon, 07 Aug 2023 09:45:19 GMT
Server: cloudflare
Set-Cookie: __cflb=redacted; SameSite=Lax; path=/; expires=Mon, 07-Aug-23 12:15:20 GMT; HttpOnly
Set-Cookie: __cfruid=redacted; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Envoy-Upstream-Service-Time: 251

ERROR 5454: Error during the fetch, code: 404, message: <!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <m
```

**Comment by xjewer** [comment]
sorry for troubles caused. this has to be fixed now. can you try it again? @sank3

**Comment by sank3** [comment]
Looks good to me. thanks.
