### ISSUE TITLE
Version tag not recognized by go (`V0.77.0` instead of `v0.77.0`)

### ISSUE THREAD

**Issue by favonia** [cloudflare/cloudflare-go#1398]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.77.0

### Steps to reproduce

Run `go get github.com/cloudflare/cloudflare-go@V0.77.0` (or visit <https://pkg.go.dev/github.com/cloudflare/cloudflare-go@V0.77.0>)

### Expected output

```
go: upgraded github.com/cloudflare/cloudflare-go v0.76.0 => v0.77.0
```

### Actual output

```
go: upgraded github.com/cloudflare/cloudflare-go v0.76.0 => v0.76.1-0.20230912200526-f968533e2861
```

### Suggested solution

Go only recognizes the lowercase `v` as the start of the version tag. An easy fix is to re-release the version 0.77.0 with the correct tag `v0.77.0`.

**Comment by jacobbednarz** [comment]
this was retagged shortly after so I suspect you hit a cache somewhere with this one. can you give it another go over the next couple of hours and let me know if it doesn't work for you?

**Comment by favonia** [comment]
@jacobbednarz Hmm unfortunately I can't see it anymore. I remember seeing that on GitHub when I created this issue, so maybe GitHub is the culprit? Anyways, I can confirm that it is working now. Sorry about the noise.

**Comment by jacobbednarz** [comment]
sorry, to clarify, _I_ retagged this and removed the old tag to fix the conflicts shortly after I noticed. I botched the casing (thanks caps lock!) but the new tag should be all good providing it isn't in any downstream caches.
