### ISSUE TITLE
All API documentation links are incorrect

### ISSUE THREAD

**Issue by dkoston** [cloudflare/cloudflare-go#1426]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.80.0

### Go environment

```
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/dave/Library/Caches/go-build'
GOENV='/Users/dave/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/xxxxx/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/dave/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.21.0/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.0/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/xxxxxx/go/src/github.com/xxxxx/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/lm/gzk1q0b95491ctlw16p4_4_m0000gn/T/go-build2255234786=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### Expected output

Be able to understand easily which API call is called by each go function.

For example:

https://pkg.go.dev/github.com/cloudflare/cloudflare-go#API.CreateList

This should have a link which takes me to APIv4 docs for a specific api call

### Actual output

[https://pkg.go.dev/github.com/cloudflare/cloudflare-go#API.CreateList](https://pkg.go.dev/github.com/cloudflare/cloudflare-go#API.CreateList) links to [https://api.cloudflare.com/#rules-lists-create-list](https://api.cloudflare.com/#rules-lists-create-list) which redirects to [https://developers.cloudflare.com/api/#rules-lists-create-list](https://developers.cloudflare.com/api/#rules-lists-create-list). This link takes you to the api docs landing page rather than a specific api call's documentation

### Code demonstrating the issue

package main

import "log"

func main() {

 log.Fatalf("API docs not found")
}

### Steps to reproduce

go to https://pkg.go.dev/github.com/cloudflare/cloudflare-go#API.CreateList or any function that calls APIv4 and find the link spits you out on the documentation landing page.

I recommend fixing your old links at developers.cloudflare.com rather than changing the links in the code / docs here as that will fix for all references to your old api.cloudflare.com docs. Surprised to see that all the old links were broken.

### References

no

**Comment by jacobbednarz** [comment]
thanks for the issue here. we're aware many of the links are no longer working as the API documentation now resides elsewhere. we have a ticket internally tracking this however, there is not currently an ETA or if we will remove them entirely given some of the endpoints have multiple sources of documentation. 

for now, I recommend using developers.cloudflare.com/api directly for your documentation searching.
