### ISSUE TITLE
What does "foo" mean in `CHANGELOG.md`?

### ISSUE THREAD

**Issue by favonia** [cloudflare/cloudflare-go#1430]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.80

### Expected entry

> (an actual component): what has been change

### Actual entry

> foo: Add support for body_scanning (Enhanced File Detection) in teams account configuration (https://github.com/cloudflare/cloudflare-go/issues/1423)

**Comment by jacobbednarz** [comment]
it was an error for a changelog entry. the release notes were fixed when it was noticed.

**Comment by favonia** [comment]
@jacobbednarz Thank you. I see that GitHub release notes were fixed, but not the file `CHANGELOG.md`:
https://github.com/cloudflare/cloudflare-go/blob/2cf9895e063c865976350f4d4b4ecccba6579dc6/CHANGELOG.md?plain=1#L23

**Comment by jacobbednarz** [comment]
i'll probably have to manually regenerate the entire thing as it only incrementally generates the current release iirc. the source entry was fixed too.
