### ISSUE TITLE
Delete by filters

### ISSUE THREAD

**Issue by stevenanthonyrevo** [cloudflare/cloudflare-go#1458]
### Current cloudflare-go version

latest

### Description

After review the source code and the test cases. 

I am surprised that many of the Test cases don't allow deleting a resource by a specific attribute. 

Would be nice to have.

### Use cases

Delete tunnel by the name instead of the requirement of tunnel id. 

### Potential cloudflare-go usage

```go
client.DeleteTunnel(context.Background(), TunnelName)
```

### References

Not sure if I have found this in the repo.

**Comment by jacobbednarz** [comment]
services don't offer the ability to delete by non-unique identifiers so we won't add them here since we aim to be 1:1 with those implementations.
