### ISSUE TITLE
Zone command group doesn't work in flarectl amd64 build of v0.83.0 github release

### ISSUE THREAD

**Issue by iavael** [cloudflare/cloudflare-go#1465]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v.0.83.0

### Go environment

N/A

### Expected output

```
$ ./flarectl zone list
                 ID                |    NAME     |     PLAN     | STATUS  
-----------------------------------+-------------+--------------+---------
  [REDACTED] | [REDACTED] | Free Website | active  
$ echo $?
0
```

### Actual output

```
$ ./flarectl zone list
$ echo $?
1
```

### Code demonstrating the issue

N/A

### Steps to reproduce

Download amd64 build from https://github.com/cloudflare/cloudflare-go/releases/tag/v0.83.0, untar and run any zone subcommand

**Comment by iavael** [comment]
Releases v0.82.0 and v0.81.0 work fine
When I build flarectl myself from v0.83.0 tag or from master branch, it works fine too. Problem occurs only with "official" build from github release.

**Comment by grex-gh** [comment]
It's the same for any version including v0.83.0 onward. Could this please be fixed?

**Comment by lmchao** [comment]
Same issue present when building from code on any release later than v0.82.0, tested on macos 14.2.1.
Also on the prebuilt releases distributed via brew
