### ISSUE TITLE
Latest release (0.1.0) violates semver constraints

### ISSUE THREAD

**Issue by isaacl** [cloudflare/cloudflare-go#1522]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.1.0

### Go environment

n.a.

### Expected output

According to semver, the previous release, 0.89.0, is _newer_ than 0.1.0.  Did you mean to release as 1.0.0?

### Actual output

n.a.

### Code demonstrating the issue

n.a.

### Steps to reproduce

n.a.

**Comment by jacobbednarz** [comment]
this was not an intentional release; sorry for the confusion here.
