### ISSUE TITLE
RawResponse usage

### ISSUE THREAD

**Issue by meirf** [cloudflare/cloudflare-go#160]
I see [RawResponse](https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L211) as a type, but I don't see anything that returns it or accepts it. 

How can it be used? Is there some type relationship to other types?

**Comment by elithrar** [comment]
The Raw() method returns this:
https://github.com/cloudflare/cloudflare-go/blob/73188131583704facec77adbb1e666a7917f973c/cloudflare.go#L218-L229
