### ISSUE TITLE
Ways to test WorkersKV in gofiber/storage package

### ISSUE THREAD

**Issue by Geun-Oh** [cloudflare/cloudflare-go#1605]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.91.0

### Go environment

.

### Expected output

Hello. I'm adding storage driver to [https://github.com/gofiber/storage](https://github.com/gofiber/storage).
I tested and add features, but I didn't find the methods to test them in github actions environment.

Please let me know is there any test accounts that I can use with, or the other ways to test it.

Thanks.

### Actual output

.

### Code demonstrating the issue

1.

### Steps to reproduce

1.

### References

This is PR of what I made. [https://github.com/gofiber/storage/pull/1298](https://github.com/gofiber/storage/pull/1298)

**Comment by jacobbednarz** [comment]
we only have unit tests in this repository. if you want an integration test, you will need a Cloudflare account to use.

**Comment by gaby** [comment]
@jacobbednarz The readme on this repo should suggest using Miniflare or Worked for testing this package.

https://github.com/cloudflare/miniflare
https://github.com/cloudflare/workerd
