### ISSUE TITLE
API now returning pageviews.search_engine instead of pageviews.search_engines

### ISSUE THREAD

**Issue by robbiet480** [cloudflare/cloudflare-go#167]
API docs are still showing `search_engines` but I just pulled data via cURL and confirmed it's now or maybe sometimes `search_engine`. 

https://github.com/cloudflare/cloudflare-go/blob/4155500e79b003e97c08ee87211bb70c30b3d664/zone.go#L199

**Comment by elithrar** [comment]
It should be `search_engine` (singular), as you have confirmed. I've raised a PR internally to fix the schema.
