### ISSUE TITLE
ReplayProtection attribute of MagicTransitIPsecTunnel struct is of type *bool and not type bool

### ISSUE THREAD

**Issue by Sceptyre** [cloudflare/cloudflare-go#1770]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.93.0

### Go environment

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\User\AppData\Local\go-build
set GOENV=C:\Users\User\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\User\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\User\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.9
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\git\terraform-provider-cloudflare\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\USER~1\AppData\Local\Temp\4\go-build340422575=/tmp/go-build -gno-record-gcc-switches

### Expected output

Expected ReplayProtection to behave the same as the AllowNullCipher bool attribute. Appears to have been a linting enforced change however the lint appears to state that it should only apply to bool attributes with 'omitempty' flag. I can resubmit a pr however don't want to get caught in the linting error again.

### Actual output

Attribute expects a *bool value however AllowNullCipher expects bool.
`cannot use true (untyped bool constant) as *bool value in struct literal`

### Code demonstrating the issue
```
package main

import (
    "github.com/cloudflare/cloudflare-go"
)

func main() {
    myIpsecTunnel := cloudflare.MagicTransitIPsecTunnel{
        ReplayProtection: true, // enable replay protection
        AllowNullCipher: false, // should behave the same
    }
}
```
### Steps to reproduce

1. Define a MagicTransitIPsecTunnel w/ ReplayProtection set to true/false
2. Get *bool expected error

### References

https://github.com/cloudflare/cloudflare-go/pull/1710

**Comment by jacobbednarz** [comment]
this is intentional. new booleans should only be represented as boolean pointers to determine the three states: truthy, falsey and not set. you need to update your code to handle the correct types.

**Comment by Sceptyre** [comment]
I see. Then shouldn't AllowNullCipher also be a bool pointer? Just want to make sure I understand the difference between the two.

**Comment by jacobbednarz** [comment]
the older boolean has been left as is for compatibility since it was before we made the convention switch.

**Comment by Sceptyre** [comment]
I gotcha! Just legacy then. Thank you!
