### ISSUE TITLE
Implement organization-level Load Balancer pool/monitor API calls

### ISSUE THREAD

**Issue by FnuGk** [cloudflare/cloudflare-go#178]
There is currently no way to access access organization level load balancer pool/monitor settings.

The API calls in question is:

Monitors:
- https://api.cloudflare.com/#organization-load-balancer-monitors-list-monitors
- https://api.cloudflare.com/#organization-load-balancer-monitors-create-a-monitor
- https://api.cloudflare.com/#organization-load-balancer-monitors-monitor-details
- https://api.cloudflare.com/#organization-load-balancer-monitors-delete-a-monitor
- https://api.cloudflare.com/#organization-load-balancer-monitors-modify-a-monitor

Pools:
- https://api.cloudflare.com/#organization-load-balancer-pools-properties
- https://api.cloudflare.com/#organization-load-balancer-pools-create-a-pool
- https://api.cloudflare.com/#organization-load-balancer-pools-pool-details
- https://api.cloudflare.com/#organization-load-balancer-pools-delete-a-pool
- https://api.cloudflare.com/#organization-load-balancer-pools-modify-a-pool

**Comment by elithrar** [comment]
Pass UseOrganization
https://godoc.org/github.com/cloudflare/cloudflare-go#UsingOrganization -
the LB methods will then use the /organizations endpoints automatically.

**Comment by FnuGk** [comment]
Ahh so i needed to just RTFM.
Will close the issue then
