### ISSUE TITLE
DNSRecord.Priority is no longer an int, but a string

### ISSUE THREAD

**Issue by beyang** [cloudflare/cloudflare-go#192]
This appears to have changed in the last 48 hours. This client library does not appear to reflect the new API schema and as a result, the Terraform Cloudflare provider is breaking.

Pull request submitted here: https://github.com/cloudflare/cloudflare-go/pull/191

**Comment by prdonahue** [comment]
Hi @beyang I've confirmed this, and believe it to be a regression. Has been flagged internally with the appropriate team.

**Comment by prdonahue** [comment]
PR has been merged to revert, and this will be released tomorrow AM Pacific Time. Thanks for the report. Shoot me an email if you'd like some Cloudflare swag (pat@).

**Comment by gitnik** [comment]
Just so I understand correctly: This will be reverted on the API layer? I surely hope so. This breaks quite a bit of stuff right now

**Comment by beyang** [comment]
Thank you for the quick action!

**Comment by prdonahue** [comment]
@gitnik yes, it has been reverted. The change was a regression.

@beyang you're welcome, and sorry for the inconvenience.
