### ISSUE TITLE
"JSON unmarshalling" error while trying to get dns records of any zone

### ISSUE THREAD

**Issue by cornerot** [cloudflare/cloudflare-go#193]
Code example:

```go
searchRecord := cloudflare.DNSRecord{}
cfRecords, err := api.DNSRecords(id, searchRecord)
fmt.Println(cfRecords, err)
```

Output:

```
error unmarshalling the JSON response: json: cannot unmarshal string into Go struct field DNSRecord.priority of type int
```

flarectl example:
```bash
flarectl d l --zone zzzz.com
```

Output:

```
error unmarshalling the JSON response: json: cannot unmarshal string into Go struct field DNSRecord.priority of type int
```

**Comment by denniswebb** [comment]
This must be the result of an API change at Cloudflare.  Saw this today using the terraform provider for cloudflare.

**Comment by Fumler** [comment]
Experiencing the same with kubernetes external-dns.

**Comment by prdonahue** [comment]
This has been fixed on the Cloudflare API side. 

Can you try re-running @EricTendian @Fumler @denniswebb @cornerot?

**Comment by EricTendian** [comment]
@prdonahue thanks! I can confirm things are working properly now, at least Kubernetes external-dns is working.

**Comment by cornerot** [comment]
Thanks! Working now.
