### ISSUE TITLE
How to retrieve `recordID` for a DNS record?

### ISSUE THREAD

**Issue by jmvbxx** [cloudflare/cloudflare-go#203]
Firstly, I love this solution and we use it in several parts of our infrastructure. Thanks for all the work!

I have an embarrassingly simple question: How/Where do I get the `recordID` from? I can't seem to find it anywhere. What I'm trying to do is this:
```
	d, err := cloudflare.DeleteDNSRecord(zoneID, recordID)
	if err != nil {
		fmt.Errorf("Failed to delete record: %s", err)
	}
```
Thank you in advance!

**Comment by garrettgalow** [comment]
I believe this is what you want: https://godoc.org/github.com/cloudflare/cloudflare-go#API.DNSRecords

You can pass in a DNSRecord object that will set the filter to return to you a list of records. Then you should be able to get the record id.

**Comment by jmvbxx** [comment]
Perfect. Thank you!
