### ISSUE TITLE
Add support for Spectrum API

### ISSUE THREAD

**Issue by T4cC0re** [cloudflare/cloudflare-go#207]
Hi,

could you add support to configure spectrum?

https://developers.cloudflare.com/spectrum/api-reference/

Thanks!

**Comment by jacobbednarz** [comment]
👋 @T4cC0re - I started on this via #209 however I realised that our development account doesn't have any of the Spectrum features enabled so I'm reaching out to our account manager to get it enabled before I embark too much further on this one to ensure we have accurate responses and coverage for the edge cases.
