### ISSUE TITLE
Set MX priority

### ISSUE THREAD

**Issue by wordskill** [cloudflare/cloudflare-go#216]
I am probably missing something really obvious, but there appears to be no documented way to include the priority number when adding MX records via flarectl. I checked the documentation here and anywhere else Google led me, but could not unearth any examples.

I tried the following guesses but always ended up with a priority of 0 when I checked the resulting record in the dash:

```
flarectl dns create --zone=$domain --name=$domain --type="MX" --content=10 mxa.mailgun.org

flarectl dns create --zone=$domain --name=$domain --type="MX" --content="10 mxa.mailgun.org"

flarectl dns create --zone=$domain --name=$domain --type="MX" --content=10:mxa.mailgun.org

flarectl dns create --zone=$domain --name=$domain --type="MX" --content="10:mxa.mailgun.org"

flarectl dns create --zone=$domain --name=$domain --type="MX" --content=10,mxa.mailgun.org

flarectl dns create --zone=$domain --name=$domain --type="MX" --content="10,mxa.mailgun.org"

flarectl dns create --zone=$domain --name=$domain --type="MX" --content=mxa.mailgun.org 10

flarectl dns create --zone=$domain --name=$domain --type="MX" --content="mxa.mailgun.org 10"

flarectl dns create --zone=$domain --name=$domain --type="MX" --content=mxa.mailgun.org:10

flarectl dns create --zone=$domain --name=$domain --type="MX" --content="mxa.mailgun.org:10"

flarectl dns create --zone=$domain --name=$domain --type="MX" --content=mxa.mailgun.org,10

flarectl dns create --zone=$domain --name=$domain --type="MX" --content="mxa.mailgun.org,10"
```

If there is a way to do this, I propose that it should be added to the documentation.

**Comment by jacobbednarz** [comment]
For whatever reason, `flarectl`s [DNS](https://github.com/cloudflare/cloudflare-go/blob/master/cmd/flarectl/dns.go) API doesn't have the ability to set or retrieve the priority (despite the main library supporting it). Perhaps worth opening a PR if this is something you'd like to see!

**Comment by pmocek** [comment]
Complicating this matter are the facts that 1) a DNS record of type MX includes preference number (regularly misidentified as priority) as part of the record content (i.e., as part of its RDATA), and 2) the Cloudflare API treats this number as a separate attribute.

I imagine two options:

Option A (optionally embed preference/priority in content):

    flarectl dns create --zone=example.com --name=example.com --type=MX --content='10 mail.example.com'
    flarectl dns create --zone=example.net --name=example.net --type=MX --content='mail.example.net'

Option B (optionally specify preference/priority in separate argument):

    flarectl dns create --zone=example.com --name=example.com --type=MX --priority=10 --content='mail.example.com'
    flarectl dns create --zone=example.net --name=example.net --type=MX --content='mail.example.net'

In either case, we continue to rely on Cloudflare to use some default value when no preference/priority is specified by the user.

Option A fits better with DNS specifications.  Option B fits better with Cloudflare API.

Flarectl already has a special case for MX records, combining the Priority and Content attributes of an MX record object into the content column of output, so option A is more consistent with current behavior.  The CLI in this case would continue translating Cloudflare-API-style fields to and from actual DNS record fields.

Option A is slightly more complicated to implement, as the content field must be examined and optionally parsed.  Option B is more explicit and possibly more intuitive.

**Comment by elimn** [comment]
This is still an issue. It prevents you from creating or modify any MX records what so ever. Even just attempting to update an existing entry will fail.

`flarectl dns update --id=$mx_id --zone=$domain --name=$domain  --type="MX" --content="..."`

Will return:

`Error updating DNS record:  HTTP status 400: priority is a required field. (9100)`

I'm wondering if this repo/tool is abandoned. Cloudflare's docs point you to this utility, recommending you download it for bulk changes... But between this bug and the lack of an ability to update root records ( #206 ) I'm finding this tool simply can't do what Cloudflare's support team thinks it can.
