### ISSUE TITLE
Default weight of pool origins

### ISSUE THREAD

**Issue by sssilver** [cloudflare/cloudflare-go#217]
Presently the type `LoadBalancerOrigin` is defined as:

```go
type LoadBalancerOrigin struct {
	Name    string  `json:"name"`
	Address string  `json:"address"`
	Enabled bool    `json:"enabled"`
	Weight  float64 `json:"weight"`
}
```

When instantiated without setting `Weight`, Golang defaults it to 0. This isn't desirable; `Weight` should probably be defaulted to **1**.

Related: #175

**Comment by jacobbednarz** [comment]
@sssilver Just looking at the documentation, the `weight` field accepts a value between 0 and 1. I haven't used this product in depth myself so would you be able to provide a little more information on why you think the default should be 1? I'm happy to make the change but haven't hit this issue myself.
