### ISSUE TITLE
Support for Logpull API

### ISSUE THREAD

**Issue by derekargueta** [cloudflare/cloudflare-go#225]
Correct me if I'm wrong, but it appears that the [Logpull API](https://support.cloudflare.com/hc/en-us/articles/216672448-Enterprise-Log-Share-Logpull-REST-API) is not implemented in this package.

https://api.cloudflare.com/#logs-received

**Comment by rita3ko** [comment]
@derekargueta we have https://github.com/cloudflare/logshare

**Comment by derekargueta** [comment]
ah! Thank you @rita3ko! Closing this then.
