### ISSUE TITLE
ZoneIDByName() assumes zero or one zone per zone name

### ISSUE THREAD

**Issue by pmocek** [cloudflare/cloudflare-go#234]
Function ZoneIDByName() purports to retrieve a zone's ID from its name, but actually returns only the ID of the first matching zone returned by api.[ListZones](https://api.cloudflare.com/#zone-list-zones)().  

Were zone names unique for a given API user, this would not be a problem.  But a user may have multiple zones with the same name created under multiple accounts.  This function ignores any zones with matching names that are listed after the first match.

```go
// ZoneIDByName retrieves a zone's ID from the name.
func (api *API) ZoneIDByName(zoneName string) (string, error) {
    res, err := api.ListZones(zoneName) 
    if err != nil {
        return "", errors.Wrap(err, "ListZones command failed")
    }
    for _, zone := range res {
        if zone.Name == zoneName {
            return zone.ID, nil
        }
    }
    return "", errors.New("Zone could not be found")
}
```

**Comment by jacobbednarz** [comment]
> Function ZoneIDByName() purports to retrieve a zone's ID from its name, but actually returns only the ID of the first matching zone returned by api.[ListZones](https://api.cloudflare.com/#zone-list-zones)().

I think this logic is sound as my understanding is that a zone should only be accessible to a single account (could be wrong though!) and you shouldn't be able to encounter duplicates across accounts.

> Were zone names unique for a given API user, this would not be a problem. But a user may have multiple zones with the same name created under multiple accounts.

With the given context here, I'm unsure how you could get into this situation as we've previously attempted to do this during a migration and ended up tripped up because a zone was already assigned to an existing account.

> This function ignores any zones with matching names that are listed after the first match.

Regardless of how this situation arises, perhaps we include some smarts to error if we don't have an exact, single match?

**Comment by pmocek** [comment]
> my understanding is that a zone should only be accessible to a single account

It is my understanding that a zone *is* accessible only to its owner account.

However, I have observed that multiple zones with the same name can exist in multiple accounts.  Using flarectl, I created zones of the same name and associated them with two different accounts, all using my same API credentials, using the `--org-id` option to the create subcommand of the zone command.

Thus, name is a non-ambiguous way to refer to a zone, and thus it makes no sense to retrieve an ID for *the* zone corresponding with a given name, as there is not necessarily one of them--there may be zero, one, or multiple.

One potential solution is to both add an option to specify organization ID to ZoneIDByName() and begin failing with an error upon finding multiple matches.  Another is add a requirement that an org ID be provided to ZoneIDByName().

> I'm unsure how you could get into this situation

Following is one way to do so:

1. flarectl zone create --zone=foo.example.com --org-id=12345
2. flarectl zone create --zone=foo.example.com --org-id=67890

**Comment by jacobbednarz** [comment]
> 1. flarectl zone create --zone=foo.example.com --org-id=12345

Was this performed a while ago? I just checked with `flarectl` and `curl` and it doesn't work due to not providing the root domain (in this case `example.com`).

```
curl "https://api.cloudflare.com/client/v4/zones" \
     -H "X-Auth-Email: $CF_EMAIL" \
     -H "X-Auth-Key: $CF_API_KEY" \
     -H "Content-Type: application/json" \
     --data '{"name":"foo.example.com","account":{"id":"01a7362d577a6c3019a474fd6f485823","name":"Demo Account"},"jump_start":false}'

{"success":false,"errors":[{"code":1116,"message":"Please ensure you are providing the root domain and not any subdomains (e.g., example.com, not subdomain.example.com)"}],"messages":[],"result":null}
```

The only way I could get this to accept the `--zone` parameter was using a root domain which then put the site into pending NS modifications but I haven't actually gone ahead and set it up.

**Comment by pmocek** [comment]
I revised my example above.  The domain names I have used were, indeed, root domains, not secondary ones.

**Comment by jacobbednarz** [comment]
Thanks @pmocek - I'll have a change proposal up for this shortly. I'm not sure whether multiple active zones are intended but it should definitely be safer to work with in the event where there is ambiguity.

**Comment by jacobbednarz** [comment]
@pmocek I've raised #236 which should address both of the points we've discussed above. Would you mind taking a look and ensuring it caters to your needs?

**Comment by pmocek** [comment]
Changes for #236 do not fix this problem.  The very definition of ZoneIDByName() is flawed.  This cannot be fixed.  There is no guarantee that a name corresponds to zero or one zone IDs.  In fact, there may be zero, one, or multiple of them.

If it was up to me, I believe I would obsolete ZoneIDByName(), add one new function called something like ZoneIDsByName() or ZoneIDSetByName(), and add another new function called something like ZoneIDByNameAndOrganizationID().  This would, of course, very visibly break any downstream software that now uses ZoneIDByName(), **but those are already broken**--their flaw is simply obscured at this time.  Any software built upon the assumption that there is at most a one-to-one relationship between zone name and zone ID is built upon a faulty assumption.  Anything that relies on such almost certainly works as expected exclusively when there happens to be just zero or one zones with a given name.
