### ISSUE TITLE
flarectl zone create doesn't work with .club domains

### ISSUE THREAD

**Issue by vrocks** [cloudflare/cloudflare-go#241]
flarectl.exe for Windows x64 does not create a new zone when the domain name has a .club extension.

There also is no error message.

**Comment by jacobbednarz** [comment]
Thanks for the report @vrocks! Are you able to provide the version you're using as well as the command?

**Comment by vrocks** [comment]
Turns out it was a banned zone from Cloudflare. I went ahead and tried it with curl.
So the only real issue is that flarectl doesn't give you the error message.
version is: 2017.10.0
flarectl zone create --jumpstart=false --zone=domain.club
