### ISSUE TITLE
Correctly support origin_dns in spectrum application

### ISSUE THREAD

**Issue by ewilde** [cloudflare/cloudflare-go#252]
Currently the `origin_dns` attribute is defined as 

```
type SpectrumApplicationOriginDNS struct {
	Type  string   `json:"type"`
	Names []string `json:"names"`
	TTL   int      `json:"ttl"`
}
```

However this results in a bad request `400`

## Proposal
creating a spectrum application in the UI and connecting it to a `load balancer` results in the following json 

```
{
            "id": "5683dc9a12ba4dc6bceaca011bcafcf5",
            "protocol": "tcp/22",
            "dns": {
                "type": "CNAME",
                "name": "ssh.backofficetechnology.co.uk"
            },
            "origin_dns": {
                "name": "ssh.origin.backofficetechnology.co.uk"
            },
            "origin_port": 22,
            "ip_firewall": true,
            "proxy_protocol": false,
            "tls": "off",
            "created_on": "2018-11-19T16:38:40.797134Z",
            "modified_on": "2018-11-19T16:38:40.797134Z"
        }
```

This suggests the struct should be defined as follows:
```
type SpectrumApplicationOriginDNS struct {
	Name  string   `json:"name"`
}
```

I've test that this works both in `postman` using the resulting json and in this related PR: https://github.com/terraform-providers/terraform-provider-cloudflare/pull/156

I will open a PR shortly

**Comment by jacobbednarz** [comment]
Thanks! Looks like there are tests missing for this specific field too which explains why CI hasn't picked up on it.

Let me know if you don't get around to the PR today. I'm doing some work on our Spectrum app configuration and happy to address this.

**Comment by ewilde** [comment]
@jacobbednarz i've added a test and PR #253 . I think i've copied the style of the project 😄 . Please let me know if it's not correct

**Comment by jacobbednarz** [comment]
👏 this is great. thanks!
