### ISSUE TITLE
No SDK equiv for deleteZoneRulesetRule / "Delete a zone ruleset rule"

### ISSUE THREAD

**Issue by tlimoncelli** [cloudflare/cloudflare-go#2557]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.97.0

### Go environment

GOARCH='amd64'
GOBIN='/Users/tlimoncelli/bin'
GOCACHE='/Users/tlimoncelli/Library/Caches/go-build'
GOENV='/Users/tlimoncelli/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/tlimoncelli/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/tlimoncelli/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.22.3'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/tlimoncelli/git/cloudflare-go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/ry/6mvxxmy52kl_cd939xsl42y00000gn/T/go-build693033671=/tmp/go-build -gno-record-gcc-switches -fno-common'

### Expected output

There is no SDK equivalent for this route:

https://developers.cloudflare.com/api/operations/deleteZoneRulesetRule

There is `DeleteRuleset()` but that is for the ruleset, not the individual rule (DeleteRulesetRule().

There should probably be equivs for createZoneRulesetRule, deleteZoneRulesetRule and updateZoneRulesetRule

### Actual output

n/a

### Code demonstrating the issue

n/a

### Steps to reproduce

n/a

### References

- https://developers.cloudflare.com/api/operations/createZoneRulesetRule
- https://developers.cloudflare.com/api/operations/deleteZoneRulesetRule
- https://developers.cloudflare.com/api/operations/updateZoneRulesetRule

**Comment by jacobbednarz** [comment]
👋 support for manipulating ruleset rules isn't really advised due to some confusing situations you can get yourself into if you're not updating the ruleset as a whole, however, if you really want to go ahead with it, v2 does have support for ruleset rules - https://github.com/cloudflare/cloudflare-go/blob/v2/api.md#rules-4

as we are focusing efforts on v2, i don't think we'll be backporting the functionality to v0.x. if this is something you need in v0, you're welcome to drop in a PR and i'll take a look.
