### ISSUE TITLE
Pool Health Details

### ISSUE THREAD

**Issue by Pryz** [cloudflare/cloudflare-go#265]
Hello Cloudflare !

It seems that this library doesn't support the pool health endpoint yet. (https://api.cloudflare.com/#load-balancer-pools-pool-health-details)

Is there something blocking to support it or are you open to a PR ?

## Your Environment

- Using latest (v0.8.5) or `master`

**Comment by asleepe** [comment]
any updates on this?

**Comment by AndreaM12345** [comment]
any updates on this issue?
