### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by ejcx** [cloudflare/cloudflare-go#271]
## Expected behavior
When I run `dep init` on a project using cloudflare-go, I can use the latest APIs like UploadWorker

## Current behavior
When I run `dep init` on a a project using cloudflare-go, I cannot use the latest APIs like UploadWorker.

## Possible solution
Cut a new release after adding any new API

## Steps to reproduce (for bugs)
1. Use any workers api in a project that uses cloudflare-go
2. Run `dep init` to vendor your dependencies.
3. `go build` your code.
4. Notice the build failures. dep grabbed the 0.8.5 release!

## Context
I regularly run in to issues when building `cf` github.com/ejcx/cf.

`dep` fetches the latest release and since the latest release was in mid 2018 it doesn't have all the new things that have been added.

**Comment by jacobbednarz** [comment]
Thanks @ejcx, totally agree. I think this is something we've discussed to benefit the Terraform provider too (as 0.12 will be using go modules) and will good to have releases cut instead of commit shas.

cc @garrettgalow would you be able to follow this one up in @patryk's absence?

**Comment by garrettgalow** [comment]
opened up sdk-38 internally for us to figure out the process for this. seems like us doing that died after Matt left.

**Comment by patryk** [comment]
I have re-started release process (sans flarectl binaries). Will deal with them later.
