### ISSUE TITLE
LoadBalancer struct missing enabled field

### ISSUE THREAD

**Issue by SteveGoldthorpe-Work** [cloudflare/cloudflare-go#272]
## Expected behavior

Add an Enabled bool field so that load balancers can be enabled or disabled.

## Current behavior

There is no Enabled field so it's impossible to find out if the load balancer is enabled or to set the enabled state.

## Possible solution
load_balancing.go

    type LoadBalancer struct {
            ID             string              `json:"id,omitempty"`
    ...
            Proxied        bool                `json:"proxied"`
    +       Enabled        bool                `json:"enabled"`
            Persistence    string              `json:"session_affinity,omitempty"`
            PersistenceTTL int                 `json:"session_affinity_ttl,omitempty"`
Although I'm not sure if this will break any existing code.  Using omitemtpy doesn't seem like a good idea as I suspect any bool false values would be omitted.
## Context

Trying to implement the enabled parameter in the terraform cloudflare provider.

**Comment by patryk** [comment]
Fix merged. Thanks.
