### ISSUE TITLE
Add logpush jobs client

### ISSUE THREAD

**Issue by SebastianCzoch** [cloudflare/cloudflare-go#274]
Since Logpush Jobs are available for Enterprise domains, it will be good to have it in Go client.
https://developers.cloudflare.com/logs/logpush/

This changes are required for https://github.com/terraform-providers/terraform-provider-cloudflare/issues/210

API documentation: https://api.cloudflare.com/#logpush-jobs-properties

**Comment by zackproser** [comment]
Closing this now that logpush support has been merged into master. Thanks @SebastianCzoch !
