### ISSUE TITLE
Help wanted: flarectl equivalent to "Remove Site from Cloudflare" in the control panel on https://dash.cloudflare.com

### ISSUE THREAD

**Issue by oG14108149527Exl0Ftr7sY** [cloudflare/cloudflare-go#277]
Would like to use flarectl on mac to add 311 domains to CloudFlare.com

Installed cloudflare-go using https://brew.sh and Go 

With the command 

go get -u github.com/cloudflare/cloudflare-go/

Running:
./flarectl h

displays the version number and help file

QUESTION:
Next thing is a problem:

Re:
"You must set your API key and account email address in the environment variables CF_API_KEY and CF_API_EMAIL."

Could anyone please point in the right direction?

Question: 

Where is the environment variable file ? / how to  "environment variable"?

**Comment by jacobbednarz** [comment]
There isn't an "environment file" that you need here. You pass in your credentials using environment variables. On unix systems, it looks like the following:

```
export CF_API_KEY="abc123..." CF_API_EMAIL="test@test.com"
```

And windows:

```
set CF_API_KEY="abc123..." 
set CF_API_EMAIL="test@test.com"
```

And then run your `flarectl` commands.

This question is also a little outside the scope of this repository so I'd recommend doing some  research online (perhaps stackoverflow as a starting point) as to setting and using environment variables on your OS.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Thank you for great and fast support.

What is the command for adding a single domain using flarectl?

While out of the office and in the field it would be great to be able to ssh or mosh from iPhone to a server and from the server use flarectl to add a domain to Cloudflare.com

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Thank you very much for providing access to the great tool flarectl

Flarectl will be a great timesaver both behind the desk in the office as well as out in the field with an iPhone and mosh access or ssh access to the server.



1.
Would like to verify that all domains are secured with DNSSEC.

Can flarectl provide a list of the domains that are not secured with DNSSEC?

What would the command be?




2.
What is the flarectl command equivalent to “Remove site from Cloudflare” in the control panel at https://dash.cloudflare.com/?

**Comment by jacobbednarz** [comment]
> How to delete a zone?

You cannot with flarectl. There isn't support for it at the moment. Feel free to open a PR with this functionality if you'd like it. The command you're using (`zone purge`) is for cache purging.

> How to list more than 20 domains?

Again, you cannot. This is an assumption made and you'll need to use the SDK if you'd like more. Again, please open a PR for this functionality if you'd like to use it.

> Would like to verify that all domains are secured with DNSSEC.

This isn't exposed in the `flarectl` command. Instead, you'll need to use `dig` with the `+dnssec` flag. Alternatively, an online tool such as https://dnssec-analyzer.verisignlabs.com.
