### ISSUE TITLE
Implement Billing endpoints

### ISSUE THREAD

**Issue by Tenzer** [cloudflare/cloudflare-go#31]
https://api.cloudflare.com/#user-billing-profile
https://api.cloudflare.com/#user-billing-history

**Comment by gliptak** [comment]
@Tenzer Do you see this added to `https://github.com/cloudflare/cloudflare-go/blob/master/user.go` or to a new file `https://github.com/cloudflare/cloudflare-go/blob/master/billing.go`? Thanks

**Comment by elithrar** [comment]
@gliptak user.go is fine for now.

**Comment by gliptak** [comment]
@jamesog Can this be closed? Thanks

**Comment by jamesog** [comment]
Yep, indeed. Thanks.
