### ISSUE TITLE
Add support for worker resource bindings

### ISSUE THREAD

**Issue by adampointer-form3** [cloudflare/cloudflare-go#313]
Provide support for the Resource Bindings API for Worker Scripts as detailed here https://developers.cloudflare.com/workers/api/resource-bindings/. This will allow programatic access to bind scripts to KV namespaces and WASM modules.

## Expected behavior

Implement a `UploadWorkerWithBindings` method to attach extra data to a request including KV namespaces and WASM bytecode in the form of an `io.Reader`. This will then perform a multipart/form-data request to the CF api.

## Current behavior

Not currently supported.

## Possible solution

I have a PR ready :)

## Context

My company needs to be able to manage it's CF Workers via Terraform and we need to be able to bind KV namespaces. This change will enable the corresponding changes within the Terraform provider to be made.

**Comment by patryk** [comment]
Fixed by #363
