### ISSUE TITLE
Zone.PurgeCache uses http method "DELETE" but docs say "POST"

### ISSUE THREAD

**Issue by oh4real** [cloudflare/cloudflare-go#318]
I am using the cloudflare-go client in a custom terraform_provider.  I have also implemented an in-house cloudflare client. When purging the cache on a host, I knew it to be POST, but in reading the cloudflare-go methods, I saw it using DELETE.

I was a bit anxious when I discovered go client was using DELETE, but used it and all was good.

The API says all the purge_cache calls should use POST (https://api.cloudflare.com/#zone-purge-files-by-cache-tags-or-host @ 06/16/2019). 

Should probably sync with the API docs.

## Expected behavior

Purging cache continues to work.

## Current behavior

Purging cache works but uses undocumented DELETE http method

## Possible solution

Swap POST for DELETE in the Zone methods for purging

## Context

As stated, I was a bit nervous using an undocumented DELETE.

**Comment by jacobbednarz** [comment]
@patryk are you able to double check which is the intended method here?

**Comment by patryk** [comment]
We switched from `DELETE` to `POST`, but kept it for legacy reasons. We should change to use `POST` here.
