### ISSUE TITLE
additional WAF rule endpoint support

### ISSUE THREAD

**Issue by sbfaulkner** [cloudflare/cloudflare-go#321]
support should be added for some missing WAF endpoints...

https://api.cloudflare.com/#waf-rule-packages-firewall-package-details
https://api.cloudflare.com/#waf-rule-packages-edit-firewall-package
https://api.cloudflare.com/#waf-rule-groups-list-rule-groups
https://api.cloudflare.com/#waf-rule-groups-rule-group-details
https://api.cloudflare.com/#waf-rule-groups-edit-rule-group

## Context

I'm prepared to work on terraform additions to add additional WAF data sources, as well and resources to support reading and configuring of WAF rule packages and groups.

These additional endpoints will be needed to implement these.

**Comment by patryk** [comment]
Related PRs merged. Closing.

**Comment by sbfaulkner** [comment]
maybe re-open for now as we still actually need a couple more of the ones listed (I just did small PRs) namely...

https://api.cloudflare.com/#waf-rule-groups-rule-group-details
https://api.cloudflare.com/#waf-rule-groups-edit-rule-group
