### ISSUE TITLE
Add context to API methods

### ISSUE THREAD

**Issue by johanbrandhorst** [cloudflare/cloudflare-go#324]
## Expected behavior

When making API requests it is generally good to be able to cancel requests. In Go this is done via `context.Context` parameters. I would like to be able to cancel requests.

## Current behavior

There is no way to cancel pending requests.

## Possible solution

Either change all the methods to take a context (probably undesirable), or add `XContext` methods with the same parameters as `X` but taking a context (see ListZonesContext).

**Comment by johanbrandhorst** [comment]
This is still needed

**Comment by johanbrandhorst** [comment]
This is still needed.

**Comment by jacobbednarz** [comment]
released in [v0.14.0](https://github.com/cloudflare/cloudflare-go/releases/tag/v0.14.0)
