### ISSUE TITLE
flarectl - add support for zone lockdown rules

### ISSUE THREAD

**Issue by Constantin07** [cloudflare/cloudflare-go#328]
This is feature request.

It looks like at the moment the `flarectl` doesn't support zone lockdown. It would be nice to be added.

```
./flarectl zone -h
NAME:
   flarectl zone - Zone information

USAGE:
   flarectl zone command [command options] [arguments...]

COMMANDS:
     list, l      List all zones on an account
     create, c    Create a new zone
     check        Initiate a zone activation check
     info, i      Information on one zone
     plan, p      Plan information for one zone
     settings, s  Settings for one zone
     purge        (Selectively) Purge the cache for a zone
     dns, d       DNS records for a zone
     railgun, r   Railguns for a zone
     certs, c     Custom SSL certificates for a zone
     keyless, k   Keyless SSL for a zone
```

## Expected behaviuor
Support zone lock down.

## Current behaviuor
No support to add zone lockdown.

## References

https://support.cloudflare.com/hc/en-us/articles/115001595131-Locking-down-URLs-in-Cloudflare

**Comment by viggy28** [comment]
Folks, I am working on this. 

Let me know if there are any caveats that I need to be aware of.  TIA.

**Comment by patryk** [comment]
Added with PR #332.

**Comment by Constantin07** [comment]
Thank you @patryk @viggy28
