### ISSUE TITLE
flarectl always reports the same version "2017.10.0"

### ISSUE THREAD

**Issue by rvalitov** [cloudflare/cloudflare-go#343]
The version does not change during all the updates to flarectl
https://github.com/cloudflare/cloudflare-go/blob/master/cmd/flarectl/flarectl.go#L16

**Comment by rvalitov** [comment]
Won't fix?

**Comment by jacobbednarz** [comment]
Fixed via #524

**Comment by patryk** [comment]
Hi @rvalitov, version should now auto-populate build time when GoReleaser is used.
