### ISSUE TITLE
The result_info 'count' field in calls to zones/<zoneID>/spectrum/apps with pagination enabled is not accurate.  always reports 1

### ISSUE THREAD

**Issue by fnickels** [cloudflare/cloudflare-go#3631]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

n/a

### Go environment

originally found in my go implementation, but quickly determined it is likely a bug in the API, not sure where to report those, so dropping it here.

### Expected output

$ curl --request GET \
  --url 'https://api.cloudflare.com/client/v4/zones/{zoneID}/spectrum/apps?page=1&per_page=3&order=dns' \
  --header 'Authorization: Bearer {obfuscated}' \
  --header 'Content-Type: application/json'
{
  "result": [
    {
      "id": "<zoneId>",
      "protocol": "tcp/5223",
 ... <not important>
      "created_on": "2019-08-09T02:04:15.102226Z",
      "modified_on": "2019-08-09T02:04:15.102226Z"
    }
  ],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 3,
    "count": 3,
    "total_count": 17
  }
}

### Actual output

$ curl --request GET \
  --url 'https://api.cloudflare.com/client/v4/zones/{zoneID}/spectrum/apps?page=1&per_page=3&order=dns' \
  --header 'Authorization: Bearer {obfuscated}' \
  --header 'Content-Type: application/json'
{
  "result": [
    {
      "id": "<zoneId>",
      "protocol": "tcp/5223",
 ... <not important>
      "created_on": "2019-08-09T02:04:15.102226Z",
      "modified_on": "2019-08-09T02:04:15.102226Z"
    }
  ],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 3,
    "count": 1,
    "total_count": 17
  }
}

### Code demonstrating the issue

curl --request GET \
  --url 'https://api.cloudflare.com/client/v4/zones/{zoneID}/spectrum/apps?page=1&per_page=3&order=dns' \
  --header 'Authorization: Bearer {obfuscated}' \
  --header 'Content-Type: application/json'

### Steps to reproduce

Run the following curl command against a zone which has two or more Spectrum instances

curl --request GET \
  --url 'https://api.cloudflare.com/client/v4/zones/{zoneID}/spectrum/apps?page=1&per_page=3&order=dns' \
  --header 'Authorization: Bearer {obfuscated}' \
  --header 'Content-Type: application/json'

note that the count value in result_info is always zero and it likely should not be.

The response example at https://developers.cloudflare.com/api/operations/spectrum-applications-list-spectrum-applications
also shows the same behaviour.  Other calls to similar API paths do not behave in this fashion.

**Comment by jacobbednarz** [comment]
please report these through customer support who can raise it with the internal teams to have them triage it. thanks!
