### ISSUE TITLE
Required helping method to check if error is a 5XX error 

### ISSUE THREAD

**Issue by vishuvenu** [cloudflare/cloudflare-go#3698]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.111.0

### Go environment

NA

### Expected output

```
time="2024-03-13T18:13:38Z" level=error msg="received internal server error response (HTTP 500), please try again later"
```

### Actual output

```
time="2024-03-13T18:13:38Z" level=fatal msg="received internal server error response (HTTP 500), please try again later"
Stream closed EOF for external-dns/external-dns-cloudflare-205ef5f2-6977ccb67d-kh76q (external-dns)
```

### Code demonstrating the issue

We want to have a simple method to identify the error type
```
	zonesResponse, err := p.Client.ListZonesContext(ctx)
	if err != nil {
		var apiErr *cloudflare.Error
		if errors.As(err, &apiErr) {
			if apiErr.ServerErrored(err) {
				// Pass any 5XX errors as SoftError
				return nil, provider.NewSoftError(err)
			}
		}
		return nil, err
	}

```

### Steps to reproduce

NA

### References

We see few fatal errors when we use Cloudflare as the provider with External-DNS

https://github.com/kubernetes-sigs/external-dns/issues/4315

**Comment by jacobbednarz** [comment]
this already exists today; see https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L294-L302 and https://github.com/cloudflare/cloudflare-go/blob/master/errors.go#L212-L252.
