### ISSUE TITLE
Support for mapping Access service tokens to Access policy

### ISSUE THREAD

**Issue by etiennetremel** [cloudflare/cloudflare-go#372]
At the moment it doesn't seem to be possible to create an Access Policy with a Decision type Non-Identity.
If this get supported, we can then attach a Access Service Token to an Access Policy using the API.

Details on how to attach an access service token to an access policy: https://developers.cloudflare.com/access/service-auth/service-token/

**Comment by jacobbednarz** [comment]
this has been added in #419

**Comment by patryk** [comment]
It is, thanks!
