### ISSUE TITLE
QUESTION: Media management (upload/download) supported?

### ISSUE THREAD

**Issue by Emixam23** [cloudflare/cloudflare-go#393]
Hi,

I was looking at your library and was wondering if you were supporting the upload of media?

Because I saw this https://developers.cloudflare.com/stream/getting-started/simple-uploads/ just before so I was hoping that you were providing this functionality as well.

I am looking for:
- Uploading an image/video
- Upload a batch of images/videos
- Use the response link (of an upload) to integrate an image/video into a website/mobile app

Thanks,

**Comment by jacobbednarz** [comment]
There isn't support for this at the moment however you're welcome to add it if you have some use for it.

**Comment by Emixam23** [comment]
I've never contributed to a git before but, I found out some http code to upload a media, maybe we can integrate it?

**Comment by ashleygwilliams** [comment]
hey @Emixam23 - your usecase may be slightly different, so apologies if this is not relevant, but if you'd like to upload content and serve it statically over http- Workers Sites can do that and we have a CLI tool that let's you do it (https://github.com/cloudflare/wrangler) - you can read more here: https://workers.cloudflare.com/sites, https://developers.cloudflare.com/workers/tooling/wrangler/kv_commands/
