### ISSUE TITLE
cloudflare terraform provider is failing to parse the response from creating a spectrum application

### ISSUE THREAD

**Issue by kyleburton** [cloudflare/cloudflare-go#396]
Using the 2.2 version of the cloudflare terraform provider to create a `cloudflare_spectrum_application` resource, the request responds with a json document containing:

```
 {
  "result": {
    "id": "...",
    ...
    "ip_firewall": true,
    "proxy_protocol": "off",
    "spp": false,
    ...
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

The SpectrumApplication struct's field for `proxy_protocol` is a [`bool`](https://github.com/cloudflare/cloudflare-go/blob/master/spectrum.go#L21).  This results in a failure to marshal the response.

## Expected behavior

It appears that the CloudFlare Spectrum HTTP API has changed to return a string ("on", "off"), the struct should be updated. 

## Steps to reproduce (for bugs)

Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant.

1. using the cloudflare terraform provider v2
2. create a `cloudflare_spectrum_application` resource
3. execute a `terraform apply`

## Your Environment

```
> terraform version
Terraform v0.12.6
+ provider.aws v2.41.0
+ provider.cloudflare v2.2.0
+ provider.powerdnsroy v0.12.17
+ provider.template v2.1.2
```

```
> go version
go version go1.12.5 darwin/amd64
```

```
> uname -a
Darwin ... 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct  4 23:08:59 PDT 2019; root:xnu-4570.71.57~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
```

**Comment by jacobbednarz** [comment]
this should be covered by #395

**Comment by kyleburton** [comment]
Thanks for the update - do you have any visibility into when it might be getting merged?
