### ISSUE TITLE
flarectl doesnt support plan type Enterprise 

### ISSUE THREAD

**Issue by sarimali** [cloudflare/cloudflare-go#397]
When we on board sites to cloudflare we want to create them under our enterprise account. 

## Expected behavior

there should be a optional flag for --plan Enterprise 

ie. flarectl zone create --zone example.io  --jumpstart true --account-id ${CF_ACCOUNT_ID} --type partial --plan Enterprise 

## Current behavior
Not supported

## Possible solution
Default to basic and add it as a optional flag

## Context

I'm trying to on board sites in a automated way and this is impeding progress

## Your Environment

Include as many relevant details about the environment you experienced
the bug in:

* Version used: 8a0d6e0
* Environment name and version: MacOS 10.15.1

**Comment by jacobbednarz** [comment]
Have you considered using a tool designed for this type of task like Terraform? There is a Cloudflare provider which already handles this.

**Comment by sarimali** [comment]
Its ok for most cases however we have too many unique sites (1500+). Our domains need to be a partial setup, we are on google cloud so verification is possible but moving from the registrar's is not. My purpose is for cloudflare ssl certs on our domains. I'm using the cname verification method which is still not possible with terraform, i was hoping to leverage `flarectl` with `gcloud` and api calls for everything that is still not possible.

**Comment by garrettgalow** [comment]
cname support is supported: https://github.com/terraform-providers/terraform-provider-cloudflare/issues/280

docs: https://www.terraform.io/docs/providers/cloudflare/r/zone.html
