### ISSUE TITLE
GraphQL Support?

### ISSUE THREAD

**Issue by dacamp** [cloudflare/cloudflare-go#412]
Are there any plans to support the new [GraphQL](https://developers.cloudflare.com/analytics/graphql-api/) Analytics API within this SDK?

**Comment by ameshkov** [comment]
Yeah, it's unclear if we should implement our own client, or if we should simply wait for GraphQL support to appear in the official client.

**Comment by jacobbednarz** [comment]
@dacamp I know I haven't added it as we don't use it but I can't see why it wouldn't be added if there was a desire for it.

@ameshkov Have you considered opening a PR to this repository if it's something you need? Seems odd to me that the options you've provided don't include contributing back if you're in a need of a feature that currently isn't there.

**Comment by martinhaus** [comment]
Analytics API End of life is set to November 2, 2020 (https://api.cloudflare.com/#zone-analytics-properties). Any plans on implementing GraphQL support? 
Or is it better not to use this SDK and use GraphQL directly?
