### ISSUE TITLE
api.DeleteDNSRecord cause error HTTP status 401: invalid credentials

### ISSUE THREAD

**Issue by cytown** [cloudflare/cloudflare-go#414]
It's fine just few days before, but cause error today, dunno why, and other api such as api.ZoneIDByName and api.DNSRecords as well as api.CreateDNSRecord will works just fine, but only the api.DeleteDNSRecord will cause error:
> error from makeRequest: HTTP status 401: invalid credentials

## Expected behavior

Expect it will work without any error.

## Current behavior

Other api such as api.ZoneIDByName and api.DNSRecords as well as api.CreateDNSRecord will works just fine, but only the api.DeleteDNSRecord will cause error:
> error from makeRequest: HTTP status 401: invalid credentials

## Possible solution

Not yet.

## Steps to reproduce (for bugs)

create a new dns entry A record, and then use this api to delete that one, will reproduce.

## Your Environment

Include as many relevant details about the environment you experienced
the bug in:

* Tried 0.10.6 and update to 0.11.0 today, all fails
* Go 1.13.3, mac 10.14.6.

p.s. tried debug and found it will return EOF error, hope will helps

**Comment by jacobbednarz** [comment]
I haven't been able to reproduce this using the following steps.

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/cloudflare/cloudflare-go"
)

func main() {
	api, err := cloudflare.New(os.Getenv("CF_API_KEY"), os.Getenv("CF_API_EMAIL"))
	if err != nil {
		log.Fatal(err)
	}

	zoneID := os.Getenv("CF_ZONE_ID")
	record := cloudflare.DNSRecord{
		Name:    "test",
		Content: "example.com",
		Type:    "CNAME",
	}

	r, cErr := api.CreateDNSRecord(zoneID, record)
	if cErr != nil {
		log.Fatal(cErr)
	}

	fmt.Println(fmt.Sprintf("%+v", r))

	dErr := api.DeleteDNSRecord(zoneID, r.Result.ID)
	if dErr != nil {
		log.Fatal(err)
	}

}
```

```
$ CF_ZONE_ID="redacted" CF_API_EMAIL="redacted" CF_API_KEY="redacted" go run my_file.go

&{Result:{ID:67047f666b86ed4ad009145a4e31b778 Type:CNAME Name:test.example.com Content:example.com Proxiable:true Proxied:false TTL:1 Locked:false ZoneID:redacted CreatedOn:2020-01-20 23:40:11.858495 +0000 UTC ModifiedOn:2020-01-20 23:40:11.858495 +0000 UTC Data:<nil> Meta:map[auto_added:false managed_by_apps:false managed_by_argo_tunnel:false] Priority:0} Response:{Success:true Errors:[] Messages:[]} ResultInfo:{Page:0 PerPage:0 TotalPages:0 Count:0 Total:0}}
```

Please provide a full reproduction test case that exhibits the behaviour your seeing.

**Comment by cytown** [comment]
got the real issue: You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard

**Comment by MatteoManzoni** [comment]
I'm affected by this issue too.
Why they removed this features from .cf, .ga, .gq, .ml, .tk TLDs?

**Comment by cytown** [comment]
> I'm affected by this issue too.
> Why they removed this features from .cf, .ga, .gq, .ml, .tk TLDs?

Just because most of these TLDs users won't pay.

**Comment by cytown** [comment]
Transfer to NS1, it works without any issue.

Bye cloudflare.
