### ISSUE TITLE
Who do I report problems with your service to?

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudflare/cloudflare-go#423]
I'm the author of a transparent HTTP/S proxy for Windows. The proxy is fully compliant and issues a connection that is indistinguishable (or so it seems) from the original outbound connection. However, your service catches and flags these connections as robots. Even if your cookies are sent, still, flagged as a robot. The detection is random and arbitrary as it's not always repeatable.

The same behavior can be seen with Telerik's Fiddler. I'm wondering who I can reach out to in order to get this addressed. It seems in general your service is designed to cause issues for proxy/tunnel users, or its doing so erroneously. Either way, I'm wondering who I can contact to figure out why, as there is no discernable client-side issue I can see. I've proxied proxies through other proxies to deep inspect encrypted traffic and there's no issue I can see.

**Comment by jacobbednarz** [comment]
I would recommend you contact Cloudflare Support directly to enter through the normal support channels. You can see the steps and options at https://support.cloudflare.com/hc/en-us/articles/200172476-Contacting-Cloudflare-Support

As to your issue, based on my personal experience, I don't think it's anything to do with your proxy and more about the multi-fold security controls Cloudflare use on their on domain as well as customers. It's not just cookies, IP reputation, fingerprints or any other magic solution. It's a pretty sizable list of mitigations that work together from a variety of sources designed to keep automated, malicious and unintended traffic off the domains they sit in front of.

**Comment by TechnikEmpire** [comment]
Thanks. It's just beyond me what could possibly be detected. I ripped everything apart, right down to the wire and watched the raw bytes go out over it, they are identical to without my proxy (because that's the point of transparent, local proxy) and yet it still flags it. So either I'm blind or that's some pretty next level security. I checked my IP reputation, all clean. Baffled.

Anyway thanks for the direction.

**Comment by garrettgalow** [comment]
Jacob's suggestion is the best one. We would need more details and probably some investigation on our side to have any chance of figuring this out.

**Comment by TechnikEmpire** [comment]
@garrettgalow Thanks. Closing out.

**Comment by TechnikEmpire** [comment]
Just FYI, it appears that not offering HTTP/2 as an alt-protocol caused this issue. I rewrote a core aspect of my proxy to enable HTTP/2 and this issue vanished. Fiddler would suffer from the same issue because HTTP/2 is only supported upstream by a very specific web request handler in .NET Core 3.x, which Fiddler almost certainly is not using.
