### ISSUE TITLE
Add SSL-For-SaaS v2 fields to CustomHostname struct in go-client

### ISSUE THREAD

**Issue by denverSerraoWP** [cloudflare/cloudflare-go#435]
We are using the cloudflare-go client for our integration with Cloudflare.  Some of our zones are being migrated to the SSL-for-SaaS v2 format.  We are using the go-client to do CRUD operations on CustomHostnames and would like the go-client to return the new v2 fields in the [CustomHostname](https://github.com/cloudflare/cloudflare-go/blob/e8318fc46e048c21d7e36d1854938afe8220eaa7/custom_hostname.go#L33) struct

## Expected behavior

This is the response on a GET for the customHostnames API endpoint if there are verification errors.  Per our discussions with Cloudflare, the `status` and `verification_errors` fields are newly added in the response

We would like those fields added in the [CustomHostnames](https://github.com/cloudflare/cloudflare-go/blob/e8318fc46e048c21d7e36d1854938afe8220eaa7/custom_hostname.go#L33) struct   and properly populated with the values from the customHostname in question

`{
  "result": {
    "id": "348696e6-0d6c-45da-8b92-b96adf07fcfb",
    "hostname": "le-test.partial.cf",
    "ssl": null,
    "status": "pending",
    "ownership_verification": {
      "txt_name": "_cf-custom-hostname.le-test.partial.cf",
      "txt_value": "89fdb4b6-9b68-40e6-b021-2ddc84e47217"
    },
    "verification_errors": [
      "fallback origin is pending_deployment, not active."
    ],
    "created_at": "2019-10-30T22:12:31.266787Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}`

## Current behavior

We use the [CustomHostname](https://github.com/cloudflare/cloudflare-go/blob/e8318fc46e048c21d7e36d1854938afe8220eaa7/custom_hostname.go#L144), [CreateCustomHostname](https://github.com/cloudflare/cloudflare-go/blob/e8318fc46e048c21d7e36d1854938afe8220eaa7/custom_hostname.go#L96) and other similar CRUD API methods which return a CustomHostname or CustomHostnameResponse struct.  We need the v2 fields of `status` and `verification_errors` in the responses of those objects

## Context

Our API needs to expose to our customers the status of the CustomHostname object so that they know if they can use the domain or need to restart verification.  So we need to be able to display the status and corresponding errors as appropriate to them

## Your Environment

* Version used 
github.com/cloudflare/cloudflare-go v0.11.4
Go 1.14

**Comment by jacobbednarz** [comment]
Looks like this was closed via #438

**Comment by patryk** [comment]
It's already released. Closing.
