### ISSUE TITLE
Reversed 'priority' Order of Page Rules

### ISSUE THREAD

**Issue by anton-yurchenko** [cloudflare/cloudflare-go#436]
Hey,
Looks like the priorities of the Page Rules are reversed.
It is stated in [API documentation](https://api.cloudflare.com/#page-rules-for-a-zone-create-page-rule) that the higher the 'priority' the higher the preference of the rule.

## Expected behavior
Creating a page rule with:
- `priority=1` should result in a new rule which is placed on top of the other, as number 1.
- `priority=2` should results in a new rule as number 2.

## Current behavior
- `priority=1` results in a rule being created last, in my case number 12.
- `priority=2` results in a rule created as number 11 in my case.

## Steps to reproduce (for bugs)
Tested with the following code:
```
package main

import (
	"encoding/json"
	"log"

	"github.com/cloudflare/cloudflare-go"
)

func main() {
	// Construct a new API object
	api, err := cloudflare.New("<api-key>", "<email>")
	if err != nil {
		log.Fatal(err)
	}

	// Create Page Rule
	jsonData := []byte(`
{
	"targets": [
		{
			"target": "url",
			"constraint": {
				"operator": "matches",
				"value": "test.example.com"
			}
		}
	],
	"actions": [
		{
			"id": "cache_level",
			"value": "bypass"
		}
	],
	"priority": 1,
	"status": "active"
}`)

	rule := new(cloudflare.PageRule)
	err = json.Unmarshal(jsonData, &rule)
	if err != nil {
		log.Fatal(err)
	}

	pageRule, err := api.CreatePageRule("<zone-id>", *rule)
	if err != nil {
		log.Fatal(err)
	}

	// Print Priority
	result, err := api.PageRule("<zone-id>", pageRule.ID)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("priority: ", result.Priority)
}
```
And **curl**:
```bash
curl -X POST "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/pagerules" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: c2547eb745079dac9320b638f5e225cf483cc5cfdda41" \
     -H "Content-Type: application/json" \
     --data '{"targets":[{"target":"url","constraint":{"operator":"matches","value":"test.example.com"}}],"actions":[{"id":"cache_level","value":"bypass"}],"priority":1,"status":"active"}'
```

## Context

It looks like an issue with an API that directly affects all implementations.
Originally encountered that issue as a part of a Terraform project.

## References
- [Terraform issue](https://github.com/terraform-providers/terraform-provider-cloudflare/issues/638)

## Your Environment
Go version 1.14
Module version v0.11.5

**Comment by jacobbednarz** [comment]
This issue is documented at terraform-providers/terraform-provider-cloudflare#187 including a workaround for Terraform.
