### ISSUE TITLE
zone.go race conditions

### ISSUE THREAD

**Issue by jimrobinson** [cloudflare/cloudflare-go#439]
## Expected behavior

I'm looking at some code I inherited that creates an instance of the cloudflare api and lists its zones.  A boiled down representation of what it is doing is:

https://play.golang.org/p/ZZ2f7KWiVc2

I would expect this code to run w/o any issue under a race detector, but instead I get a spew of warnings about a race on json marshalling, and it ultimately states 'Found 38 data race(s)', the problematic lines called out from the api are:

https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L396
https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L397
https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L402
https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L407
https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L408

On those lines we see that the goroutine launched on line 396 is
referring back to 'r' and 'zones' declared earlier

https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L358-L359

## Current behavior

The zones load, but the race detector yells bloody murder

## Possible solution

1. Use a new instance of 'r' (https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L358) inside each goroutine (https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L396).

2. Add a sync.Mutex lock outside of the goroutines and use it to lock zones when appending.

3. Use a new instance of res and err inside the goroutines (https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L397).

For reference: [zone.patch.txt](https://github.com/cloudflare/cloudflare-go/files/4411283/zone.patch.txt)

## Steps to reproduce (for bugs)

1. copy https://play.golang.org/p/ZZ2f7KWiVc2 into a new project directory
2. go build -race 
3. run it w/ a valid api key and email pair

Include as many relevant details about the environment you experienced
the bug in:

go version go1.14 linux/amd64

**Comment by jimrobinson** [comment]
Apologies, I didn't realize the diff that git was dumping out had ansi color codes in it...

[zone.patch2.txt](https://github.com/cloudflare/cloudflare-go/files/4411318/zone.patch2.txt)

**Comment by jacobbednarz** [comment]
Thanks for raising this one @jimrobinson. I was about to start digging into why the`-race` wasn't working on the `go test` steps in CI and realised that we don't have test coverage on `ListZones` so this wouldn't have been picked up 🙃

I'll hopefully have a chance to patch this up in the coming week or so. Feel free to submit a PR if you've already got this one snuffed.
