### ISSUE TITLE
Add support for Cloudflare Bot Management

### ISSUE THREAD

**Issue by LukasdeBoer** [cloudflare/cloudflare-go#467]
Bot management is a service provided by CloudFlare that detects bots and exposes new variables you can use in custom firewall rules. For more information, see here: https://www.cloudflare.com/products/bot-management/

It is enabled/disabled in the Settings menu of a zone, but it is not exposed via the settings API so it can not be set using this library at the moment. It is exposed via the following URL: `https://api.cloudflare.com/client/v4/zones/$ZONE_ID/bot_management`

This endpoint allows setting of the `enabled` flag, which enables bot management, and the `fight_mode` flag which will automatically challenge probable bots.

example GET response:
```
{
  "result": {
    "fight_mode": false,
    "enabled": true
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

and via PUT you can set values:
```
{
  "enabled": true,
  "fight_mode": true
}
```
Would be great if this feature was supported so it then can also be used in the Cloudflare Terraform provider.

**Comment by jacobbednarz** [comment]
There isn’t public API documentation for this yet so it won’t be added as we are only building on the stable exposed endpoints. 

Are you able to open a support ticket to get this documented?

**Comment by LukasdeBoer** [comment]
They said they won't document it until the API is final, so we'll have to wait for a bit here.

**Comment by jacobbednarz** [comment]
Thanks for the update! Let's leave this as is for now then and once the team releases a stable API, we can add the functionality here.

**Comment by dc232** [comment]
@jacobbednarz @LukasdeBoer any update on this? 
Would be awesome to see this feature integrated into applications like terraform

**Comment by LukasdeBoer** [comment]
Hi @dc232, It's good that they didn't declare the API final, because it looks like Cloudflare has completely overhauled this setup and now has Bot Management enabled by default, so this issue can be closed.

**Comment by mariogintili** [comment]
For those wondering how to make this available as a header just use -> https://developers.cloudflare.com/terraform/additional-configurations/transform-rules/#create-an-http-request-header-modification-rule and then grab the value `request.cf.botManagement.score`
