### ISSUE TITLE
Implement Origin CA endpoints

### ISSUE THREAD

**Issue by Tenzer** [cloudflare/cloudflare-go#47]
https://api.cloudflare.com/#origin-ca

**Comment by iToto** [comment]
I'm working on this FYI
https://github.com/iToto/cloudflare-go/tree/origin_ca_support

**Comment by dchenk** [comment]
Will this be done anytime soon?

**Comment by iToto** [comment]
This ticket escaped me. Will try to allocate some time for it this weekend.
