### ISSUE TITLE
Implement Virtual DNS endpoints

### ISSUE THREAD

**Issue by Tenzer** [cloudflare/cloudflare-go#48]
https://api.cloudflare.com/#virtual-dns-users-
https://api.cloudflare.com/#virtual-dns-organizations-

**Comment by elithrar** [comment]
I'd like to split Virtual DNS out into its own sub-package: we currently only implement one endpoint on the User, but not the Org.

e.g.

```
import (
     "github.com/cloudflare/cloudflare-go"
     "github.com/cloudflare/cloudflare-go/virtualdns"
)

    ...
    client, err := cloudflare.New(key, email)
    ...
    vdns, err := virtualdns.New(client)
    ...
    vdns.SetOrg(orgID) // Optional; causes us to use the /organizations/:id endpoint format.

    vdns.GetClusters()
    vdns.CreateClusters()
    // etc.
```

Objections? Proposing a similar approach for non-zone related services.

**Comment by elithrar** [comment]
WIP: https://github.com/cloudflare/cloudflare-go/pull/109
