### ISSUE TITLE
Logpush get challenge should error when unsuccessful

### ISSUE THREAD

**Issue by jacobbednarz** [cloudflare/cloudflare-go#499]
_Initially raised by @trjstewart and transferred from terraform-providers/terraform-provider-cloudflare#726_

>When creating a Logpush Ownership Challenge using the resource `cloudflare_logpush_ownership_challenge` it will create the resource and persist it to state even when the ownership API call returns an unsuccessful response with a status of 200.
>
>According to the [documentation](https://api.cloudflare.com/#logpush-jobs-get-ownership-challenge) it looks like we should be taking a look at the value returned in `result.valid`. Specifically if it's false I think we should throw an error with the value of `result.message`.
>
>I may not get the time to test this out and submit a PR so wanted to raise an issue in case someone else wants to take a look, should be pretty easy to validate and remediate.

Calls to [`GetLogpushOwnershipChallenge`](https://github.com/cloudflare/cloudflare-go/blob/246f2f7879452475ec188afc4e9749bdd0c4aab4/logpush.go#L215) return cleanly despite if the result of the call is not validated by Cloudflare. Instead, this should error and exit with the associated message.

**Comment by trjstewart** [comment]
Thanks all!
