### ISSUE TITLE
Unclear error message from using cloudflare API

### ISSUE THREAD

**Issue by Lilja** [cloudflare/cloudflare-go#502]
I'm currently trying to set up letsencrypt certificate with cloudflare's dns through [traefik](https://github.com/containous/traefik).

traefik uses [go-acme/lego](https://github.com/go-acme/lego) [which apparently uses this SDK](https://github.com/go-acme/lego/issues/1213#issuecomment-656335307). 

I'm attempting to figure out what the error means. I think it's somewhat unclear which of the two errors are the actual one.

```
time="2020-07-09T10:46:19Z" level=error msg="Unable to obtain ACME certificate for domains \"dersand.net,*.dersand.net\" : unable to generate a certificate for the domains [dersand.net *.dersand.net]: error: one or more domains had a problem:\n[*.dersand.net] [*.dersand.net] acme: error presenting token: cloudflare: failed to find zone net.: ListZonesContext command failed: error from makeRequest: HTTP status 403: insufficient permissions\n[dersand.net] [dersand.net] acme: error presenting token: cloudflare: failed to find zone net.: ListZonesContext command failed: error from makeRequest: HTTP status 403: insufficient permissions\n" providerName=dnscloudflare.acme
```

To use the cloudflare provider with traefik, I use two environment variables: `CF_DNS_API_TOKEN`, and `CF_ZONE_API_TOKEN`.

According to the [configuration page of go-acme/lego](https://go-acme.github.io/lego/dns/cloudflare/#credentials), `CF_DNS_API_TOKEN` is supposed to have DNS:Edit permission and `CF_ZONE_API_TOKEN` is supposed to have Zone:Read permission.

Here are my API key permissions in cloudflare, taken from cloudflare login -> dashboard -> get your api token -> specific token(three dots button) -> View summary:

![permissions](https://i.imgur.com/9p3HR9x.png)

The permissions are very broad, I'd say it would probably work with what's given to it.

**Comment by deuill** [comment]
Indeed the error comes from the Cloudflare API, though I believe this might be an issue with configuration on your side, based on the error message:

```
acme: error presenting token: cloudflare: failed to find zone net.
```

It seems that `lego` is trying to match against the `net.` FQDN? Tracing the code takes me here:

https://github.com/go-acme/lego/blob/6043c9347ca44682aa5d01b0f8711d1f2192cba9/providers/dns/cloudflare/cloudflare.go#L125-L133

And here:

https://github.com/go-acme/lego/blob/6043c9347ca44682aa5d01b0f8711d1f2192cba9/challenge/dns01/nameserver.go#L138-L152

It seems that, perhaps at the time, the SOA zone was equal to `net.`, though I no longer can confirm with with `dig` on my side.
Can you confirm the issue persists and, if so, what a `dig SOA dersand.net` returns on the machine where the LetsEncrypt daemon runs?

**Comment by Lilja** [comment]
Looks like I had stupid rules in my dnsmasq in my pihole instance. Resolved.
