### ISSUE TITLE
Per Hostname AOP does not format POST body correctly

### ISSUE THREAD

**Issue by dhaynespls** [cloudflare/cloudflare-go#510]
API expects:

`{"config":[{"hostname":"app.example.com","cert_id":"2458ce5a-0c35-4c7f-82c7-8e9487d3ff60","enabled":true}]}`

but we're supplying:

`{[{"hostname":"app.example.com","cert_id":"2458ce5a-0c35-4c7f-82c7-8e9487d3ff60","enabled":true}]}`

Simple fix, PR incoming!

**Comment by patryk** [comment]
Merged PR.
