### ISSUE TITLE
JSON Unmarshal error for CreateDNSRecord

### ISSUE THREAD

**Issue by davis12529** [cloudflare/cloudflare-go#52]
I am trying implementing a dns add service function in my go program so I referred to flarectl and dns.go

	record := cf.DNSRecord{
		Name:    r.Name,
		Type:    strings.ToUpper(r.Type),
		Content: r.Content,
		TTL:     int(r.TTL),
		Proxied: r.Proxy,
	}

`if res, err := d.api.CreateDNSRecord(zoneId, record); err != nil {
		return nil, err`

I get `Error unmarshalling JSON: json: Unmarshal(nil *cloudflare.DNSRecordResponse)` when running a unit test. I double-checked that I am passing everything correctly by looking at flarectl.go. 

DNS record is actually created. Verified by using curl api.

Any help or insights are greatly appreciated!

**Comment by elithrar** [comment]
Hey @davis12529 - I've fixed this. Pull the latest version :)
