### ISSUE TITLE
GET custom_hostname is broken, either the API or the client needs to be changed

### ISSUE THREAD

**Issue by Olliferdl** [cloudflare/cloudflare-go#527]
Fetching custom hostnames is broken. The parser expects ssl.validation_errors to be an object, when it is in-fact an array like verification_errors.

I found this because terraform wouldn't run when there are validation errors on a custom hostname.

This test makes the false assumption, that ssl.validation_errors is an object: https://github.com/cloudflare/cloudflare-go/blob/6aad7098d28c7a9e54914b58eb0c9979cd1dc13a/custom_hostname_test.go#L338

I know, your API documentation states, that ssl.validation_errors should be an object, but given the plural form, the array would make sense.
https://api.cloudflare.com/#custom-hostname-for-a-zone-properties

It might be an API issue tho, i will report it to your technical support too

Cheers
Oliver

**Comment by jacobbednarz** [comment]
Thanks for this one. Are you able to please provide a reproduction test case as well as the behaviour you are seeing? Feel free to redact any sensitive information but this will allow us to track down when this regression occurred or whether we need to update the documentation to match.

**Comment by theFreakus** [comment]
here you can see that the returned validation_errors field is an array:

curl -X GET "https://api.cloudflare.com/client/v4/zones/xxxxxxxxxxxxx/custom_hostnames/xxxxxxxxxxxxx" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "X-Auth-Key: $CLOUDFLARE_API_KEY" -H "Content-Type: application/json"
{
  "result": {
    "id": "xxxxxxxxxxx",
    "hostname": "xxxxxxxxxxxx",
    "ssl": {
      "id": "xxxxxxxxxxxxxxxxx",
      "type": "dv",
      "method": "http",
      "status": "pending_validation",
      "http_url": "xxxxxxxxx",
      "http_body": "xxxxxxxxx",
      "validation_errors": [
        {
          "message": "The requested hostname resolves to a Cloudflare zone that is not owned by you. HTTP domain control validation (DCV) cannot be completed. Update this hostname to resolve to your zone and PATCH to try again."
        }
      ],
...

to reproduce, you simply have to create a custom hostname that won't validate (domain doesn't point there, but the DNS record MUST exist, otherwise it will just show up as pending validation without errors)

Will that suffice?

**Comment by theFreakus** [comment]
Ah, and i'm not using the API client directly. I'm running terraform with the cloudflare provider.

It gave me error messages like:
Error: error reading custom hostname "xxxxxxxxxxxx": error unmarshalling the JSON response: json: cannot unmarshal array into Go struct field CustomHostnameSSL.result.ssl.validation_errors of type cloudflare.CustomHostnameSSLValidationErrors

which i traced back to the API client by browsing the source a little.

**Comment by jacobbednarz** [comment]
Thanks for that, it's much clearer now. It makes sense to raise here or in the Terraform provider so 👍 either way. Are you able to open a support ticket with Cloudflare Support to confirm which one should be the correct one? I'm happy to accept a PR once we have an idea on which way this should work.

**Comment by Olliferdl** [comment]
I opened a support ticket and will keep you updated

**Comment by nickysemenza** [comment]
The api doc for `validation_errors` is indeed wrong (but the docs are not maintained on github, we'll PR a fix to our internal repo), presumably the client code in this repo was generated off of the incorrect docs. 

https://github.com/cloudflare/cloudflare-go/pull/537#pullrequestreview-500614555 should fix the underlying issue, the API response mentioned above is correct:

> ```
> curl -X GET "https://api.cloudflare.com/client/v4/zones/xxxxxxxxxxxxx/custom_hostnames/xxxxxxxxxxxxx" -H "X-Auth-Email: $CLOUDFLARE_EMAIL" -H "X-Auth-Key: $CLOUDFLARE_API_KEY" -H "Content-Type: application/json"
> {
>   "result": {
>     "id": "xxxxxxxxxxx",
>     "hostname": "xxxxxxxxxxxx",
>     "ssl": {
>       "id": "xxxxxxxxxxxxxxxxx",
>       "type": "dv",
>       "method": "http",
>       "status": "pending_validation",
>       "http_url": "xxxxxxxxx",
>       "http_body": "xxxxxxxxx",
>       "validation_errors": [
>         {
>           "message": "The requested hostname resolves to a Cloudflare zone that is not owned by you. HTTP domain control validation (DCV) cannot be completed. Update this hostname to resolve to your zone and PATCH to try again."
>         }
>       ],
> ...
> ```

**Comment by nickysemenza** [comment]
Just following up here:
1) https://api.cloudflare.com/#custom-hostname-for-a-zone-properties has been updated to show the actual API response
2) https://github.com/cloudflare/terraform-provider-cloudflare/pull/822 should pull in the fix from #537, so I believe that `v2.12.0` of the terraform provider should contain the fix for the original problem reported by @Olliferdl.

**Comment by jacobbednarz** [comment]
Awesome stuff! Thanking you @nickysemenza 👏

**Comment by nickysemenza** [comment]
@jacobbednarz mind closing this? I don't have permissions on this repo.
