### ISSUE TITLE
Deprecated action signature error with latest codegangsta/cli library

### ISSUE THREAD

**Issue by tlianza** [cloudflare/cloudflare-go#55]
When I run "flarectl ips" this warning comes out:

> DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See 
> https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by jamesog** [comment]
We'll be vendoring cli in #10 so that might "fix" this - but thanks, good to know that's changed since I last fetched cli.

@elithrar do you want to re-vendor cli and update flarectl in your PR or shall we leave it for the time being?

**Comment by elithrar** [comment]
I've just rebased my PR so I'll re-vendor and check as part of the push.
