### ISSUE TITLE
Loadbalancer pool failure when user removed from account

### ISSUE THREAD

**Issue by alexhouse** [cloudflare/cloudflare-go#557]
We're using the Cloudflare provider through Terraform which hooks into this go library. The API key and email we were originally using has now been removed from our Cloudflare account & as a result, all `terraform apply` commands are failing because the pool resource apparently no longer exists (at least under the new user's pools endpoint).

## Expected behavior

Load balancer pool should be found when listing/viewing.

## Current behavior

Load balancer pool fails to return anything as it's looking under the `/user` namespace instead of `/account`

## Possible solution

Change ListLoadBalancerPool and all related methods to use `/account` endpoint instead of `/user`

## Steps to reproduce (for bugs)

1. Use one user/api key to create a load balancer & pool
2. Remove user/api key from account and replace with another user
3. Attempt to list load balancer pools

## Context

Due to this we're currently blocked from any Terraform applies which is preventing us from maintaining other parts of our infrastructure. Our current potential workaround is to entirely delete and then re-create the load balancer pool which isn't optimal.

## Your Environment

* Version used (e.g. git sha or specific tag): `terraform-provider-cloudflare` v2.13.2 (`cloudflare-go` v0.13.5)

**Comment by jacobbednarz** [comment]
To use the account level endpoints, you need to set the `account_id` (Terraform provider) or `api.AccountID` (`cloudflare-go`) and the [`userBaseURL`](https://github.com/cloudflare/cloudflare-go/blob/e60da8b667c90310431af0ba6686443476df48c8/cloudflare.go#L335) will update accordingly.

**Comment by alexhouse** [comment]
We did try setting the account_id in Terraform but it didn't appear to change the endpoint being used. I'll raise this there instead then. Thanks.
