### ISSUE TITLE
it is impossible to delete several FW rules at once (api.DeleteFirewallRules)

### ISSUE THREAD

**Issue by PavelvKalinin** [cloudflare/cloudflare-go#565]
## Expected behavior

the function should delete several firewall rules by the IDs passed to it

## Current behavior

when passing multiple IDs to a function, an error occurs
`error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"message\": \"invalid field value: a2982f3dd8df442*****90da937e7b99,38997b32*****8f68e131986d1ab51a1\",\n      \"source\": {\n        \"parameter\": \"id\"\n      }\n    }\n  ],\n  \"messages\": null\n}\n"`

## Steps to reproduce (for bugs)

```
func main() {
	api, _ := cloudflare.New(apiKey, apiEmail)

	zoneID := "e5a692d6a2d090b8ee8efd6*****"
	firewallRuleIDs1 := []string{"7e50436a45fa4d68a8157517e*****" }
	firewallRuleIDs2 := []string{"e037c9d76a31459b88fc04c3e*****", "8623c65269c3445596f9e9be0b****" }

	err := api.DeleteFirewallRules(zoneID, firewallRuleIDs1)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Deleted")
	}

	err = api.DeleteFirewallRules(zoneID, firewallRuleIDs2)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("Deleted")
	}
}
```

response:
go run cmd/test/test.go

> Deleted
> error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"message\": \"invalid field value: e037c9d76a31459b88fc04c3e3*****,8623c65269c3445596f9e9be0b*****\",\n      \"source\": {\n        \"parameter\": \"id\"\n      }\n    }\n  ],\n  \"messages\": null\n}\n"
>

**Comment by jacobbednarz** [comment]
Looks like your using it as the method intends and the API is documented. @patryk are you able to check if this is still possible?

In the meantime, @PavelvKalinin you may need to loop over the IDs and use the singular version of the method to unblock it.
