### ISSUE TITLE
Proxied cannot be set to false when updating a DNS record

### ISSUE THREAD

**Issue by mikarios** [cloudflare/cloudflare-go#568]
structure cloudflare.DNSRecord has two boolean fields.
Both of these cannot be set to false because of omitempty in the json tag.
The result is that one cannot change this value to false when calling the UpdateDNSRecord function.
I would suggest changing it to pointer to boolean but this could be considered a breaking change for whoever is using your library as it is.
It is a bug though and if no one has encountered it then perhaps no one has used it (or they didn't notice)

**Comment by sebastiean** [comment]
If anyone has encountered this issue whilst using the latest version of the Terraform Cloudflare provider. A workaround is to use version 2.15.0:

`terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "2.15.0"
    }
  }
}`

**Comment by tholu** [comment]
The boolean pointer should be better documented in an example, because it is a breaking change and considerable ugly and unintuitive to use: `&[]bool{true}[0]` compared to the previous `true`.
