### ISSUE TITLE
errorFromResponse fails when unauthorized

### ISSUE THREAD

**Issue by scjudd** [cloudflare/cloudflare-go#579]
When calling `api.GetLogpullRetentionFlag` with an API token that is unauthorized to make this request, the API apparently returns the text "Authorization failed". This causes a not-very-helpful error to be surfaced to the user:

```error from makeRequest: error unmarshalling the JSON response: invalid character 'A' looking for beginning of value```

The problem lies in the `errorFromResponse` function, which presumes that the `respBody` parameter contains encoded JSON.

## Expected behavior

We shouldn't surface a JSON unmarshalling error to the user. The user should have gotten some sort of authorization error.

## Possible solution

Can we add special case handling for when the API returns errors that aren't JSON formatted?

## Steps to reproduce (for bugs)

1. Create an API token without Zone -> Logs -> Edit permissions
2. Create a `cloudflare.API` object and call `api.GetLogpullRetentionFlag`

## Context

I'm writing a Prometheus exporter that will aggregate data obtained via the Logpull API. A part of the exporter's initialization routine is verifying that Logpull retention is enabled.

## Your Environment

Include as many relevant details about the environment you experienced
the bug in:

* Version used: `v0.13.7`
* Environment name and version: `go version go1.15.6 linux/amd64`

**Comment by jacobbednarz** [comment]
Thanks for raising this one @scjudd. Let me take a look as to why this isn't coming back in a JSON format before we take any next steps as the assumption is that everything should be coming back as application/json content type.

**Comment by jacobbednarz** [comment]
Ok, I've pinpointed the issue. This endpoint doesn't yet support API tokens (specifically, fetching the retention flag) so you'll need to use API keys to work around this. I'll have a look at getting the support added for this however I'm afriad I don't have an ETA on it.

**Comment by bharatnc** [comment]
@jacobbednarz the response is now fixed. Should be seeing something similar to the following now - which a valid json envelope:

```
# token with logs:read permission only
curl -s -D "/dev/stderr" https://api.cloudflare.com/client/v4/zones/$ZONE_ID/logs/control/retention/flag -X GET -H "Authorization: Bearer $LOGS_READ_ONLY_TOKEN"   | jq .
HTTP/2 401
date: Thu, 21 Jan 2021 01:25:35 GMT
....

{
  "success": false,
  "errors": [
    {
      "code": 10000,
      "message": "Authentication error"
    }
  ]
}
```

**Comment by jacobbednarz** [comment]
Thanks @bharatnc; I was just about to report back and seen you beat me to it 😃 Closing now this is resolved.

**Comment by scjudd** [comment]
Thank you both!
