### ISSUE TITLE
Surface JSON error code in Error type

### ISSUE THREAD

**Issue by jsha** [cloudflare/cloudflare-go#587]
Feature request:

Right now the Error type looks like this:

```
type Error interface {
	error
	// Raised when user credentials or configuration is invalid.
	User() bool
	// Raised when a parsing error (e.g. JSON) occurs.
	Parse() bool
	// Raised when a network error occurs.
	Network() bool
}
```

I would like it if this also had a `Code() int` method that returned the numeric error code for API errors. For instance, right now when I submit a duplicate firewall rule I get this output:

```
error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 10202,\n      \"message\": \"filter at index (0) conflicts with an existing filter\",\n      \"source\": {\n        \"pointer\": \"/0/filter\"\n      },\n      \"meta\": {\n        \"id\": \"xxx\"\n      }\n    }\n  ],\n  \"messages\": null\n}\n"
```

I'd like to be able to access that `"code": 10202` field and conclude that this is just an "already exists" error and suppress it.

**Comment by jacobbednarz** [comment]
released in [v0.14.0](https://github.com/cloudflare/cloudflare-go/releases/tag/v0.14.0)
