### ISSUE TITLE
ZoneAnalyticsDashboard broken as of 2021-03-01

### ISSUE THREAD

**Issue by ricardbejarano** [cloudflare/cloudflare-go#598]
## Expected behavior

I expect [ZoneAnalyticsDashboard](https://pkg.go.dev/github.com/cloudflare/cloudflare-go#API.ZoneAnalyticsDashboard) to return the same results as it always has.

## Current behavior

The Zone Analytics API was sunsetted as of March 1st, 2021, and the Go SDK has not been migrated over to the new GraphQL Analytics API.

The request returns the following error message:
```
Zone Analytics API is sunset and replaced by GraphQL API
```

## Possible solution

Integrating the SDK into the new [GraphQL Analytics API](https://developers.cloudflare.com/analytics/graphql-api/).

Cloudflare provides a migration guide [here](https://developers.cloudflare.com/analytics/migration-guides/zone-analytics/).

## Steps to reproduce (for bugs)

Call [`*API.ZoneAnalyticsDashboard`](https://github.com/cloudflare/cloudflare-go/blob/v0.13.8/zone.go#L712).

The second return argument (of type `error`) is non-`nil`.

## Your Environment

Include as many relevant details about the environment you experienced
the bug in:

* Version used (e.g. git sha or specific tag): `v0.13.8` (latest as of now)
* Environment name and version (e.g. Go 1.11, MacOS 10.14.1): `go version go1.16 darwin/amd64` (but it's platform-independent since this has to do with the remote end changing its behaviour).

**Comment by jacobbednarz** [comment]
The SDK hasn't added support for GraphQL as the current SDK approach would end up reimplementing a GraphQL client on top of it and wouldn't be as useful. I'm happy to poke some people on this to see what their thoughts are going forward however, for now, I'd recommend using a Go GraphQL client to interact with the analytics you're after. 

I'll reopen this should there be any updates worth while.

**Comment by ricardbejarano** [comment]
Fair enough 😞

**Comment by ricardbejarano** [comment]
FYI wrote [ricardbejarano/go-cloudflare-analytics](https://github.com/) as a client lib for the new API.

I still have to document it and test it thoroughly, but should be able to `v1` it by EOW.
