### ISSUE TITLE
flarectl zonefile upload

### ISSUE THREAD

**Issue by yakatz** [cloudflare/cloudflare-go#601]
I am bulk moving a lot of domains from several other providers to CloudFlare. All the other providers allow me to get a BIND-style zonefile. The CloudFlare web API has an endpoint to upload these zonefiles, but it is not supported in `flarectl`.

## Your Environment

* Version used (e.g. git sha or specific tag): 0.13.8

**Comment by jacobbednarz** [comment]
Thanks for raising this one @yakatz. 

You're right that at the moment there isn't an option to use `flarectl` to upload these BIND files. I'm not against having this as a sub command however I won't have time in the near future to push up a fix. If you'd like to send a PR, I'm happy to review it. 

Other than that, the best I can offer is interacting with the API directly through curl/BASH, etc.
