### ISSUE TITLE
ListZonesContext Invalid request headers (6003)

### ISSUE THREAD

**Issue by lucky0137** [cloudflare/cloudflare-go#605]
Running tips：ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)     
Sample Code：
        cf, err := cloudflare.New("Email", "ApiKey")
	if err != nil {
		fmt.Printf("cloudflare new client error: %+v", err)
	}
	// Fetch the zone ID
	id, err := cf.ZoneIDByName("example.com") // Assuming example.com exists in your Cloudflare account already
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("id:", id)

**Comment by jacobbednarz** [comment]
I'm not sure what you're after here. Are you able to open an issue following the issue template if you require assistance?

**Comment by zycon** [comment]
I'm getting the same error in my local, not sure who is culprit 

sdk v0.16.0

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zycon/Library/Caches/go-build"
GOENV="/Users/zycon/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zycon/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zycon"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zycon/liwa-nw/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/y4/k76rfcqd67z9dzkxvhyny7p80000gn/T/go-build266734655=/tmp/go-build -gno-record-gcc-switches -fno-common

**Expected:** API to work, verified the token is valid
 
**Actual OP**
2021/05/20 00:23:15 ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)

 #![image](https://user-images.githubusercontent.com/36449874/118879521-e0a5cc00-b901-11eb-9af1-ac151f42a590.png)
