### ISSUE TITLE
change methods that fetch all resources to be prefixed with `List`

### ISSUE THREAD

**Issue by jacobbednarz** [cloudflare/cloudflare-go#612]
### Current cloudflare-go version

0.15.0

Right now we have a myriad of methods that range from `ListX` and `Lists` (plural). This is hard to track down available methods for tools like autocomplete. Instead, we can consolidate the prefix to be consistent like the other CRUD operations.

**Comment by favonia** [comment]
As another breaking change, I wonder if it makes sense for these functions to return a modified `ResultInfo` saying that "there's only one single page" (that is, `Page` is always `1` and `Count` matches `Total`, etc,), completely hiding pagination from the library users.

**Comment by jacobbednarz** [comment]
See #615 for that. We're most likely going to remove it entirely. As it's not needed.

**Comment by favonia** [comment]
Got it. I am also happy with complete removal of it from the library interface. :smiley: (Could not find the relevant changes in the cited issues/PRs, though.)

**Comment by tjstansell** [comment]
If anyone is tracking this ticket, it seems the new [experimental](https://github.com/cloudflare/cloudflare-go/blob/master/docs/experimental.md) pieces will make this effort moot, as all of the methods will move down into functions on service objects.
