### ISSUE TITLE
Filtering TXT records by content doesn't work

### ISSUE THREAD

**Issue by atmosx** [cloudflare/cloudflare-go#613]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.15.0

### Go environment

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/atma/Library/Caches/go-build"
GOENV="/Users/atma/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/atma/Programs/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/atma/Programs"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/local/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/atma/temp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hd/vpt_qfmn2r1c5v_nlbtvy9bc0000gn/T/go-build265086489=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Expected output

A slice containing one record object

### Actual output

Empty slice

### Code demonstrating the issue

	// Fetch all DNS records for example.org
	host := cloudflare.DNSRecord{Type: "TXT"}
	records, err := api.DNSRecords(context.Background(), zoneID, host)
	if err != nil {
		fmt.Println(err)
		return
	}

	for _, r := range records {
		if r.Content == label {
			fmt.Println(r.Content)
		}
	}

	host1 := cloudflare.DNSRecord{Type: "TXT", Content: label}
	records1, err := api.DNSRecords(context.Background(), zoneID, host1)
	if err != nil {
		fmt.Println(err)
		return
	}

	for _, r := range records1 {
		fmt.Println(r.Content)
	}
	fmt.Println(fmt.Sprintf(" ary size %v", len(records1)))

### Steps to reproduce

Here is a sample code snippet:

```go
package main

import (
	"context"
	"fmt"

	cloudflare "github.com/cloudflare/cloudflare-go"
)

const (
	token = "<token>"
	zone  = "zone.com"
	label = "heritage=casper-3,environment=production"
)

func main() {
	api, err := cloudflare.NewWithAPIToken(token)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Fetch the zone ID for zone example.org
	zoneID, err := api.ZoneIDByName(zone)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Fetch all DNS records for example.org
	host := cloudflare.DNSRecord{Type: "TXT"}
	records, err := api.DNSRecords(context.Background(), zoneID, host)
	if err != nil {
		fmt.Println(err)
		return
	}

	for _, r := range records {
		if r.Content == label {
			fmt.Println(r.Content)
		}
	}

	host1 := cloudflare.DNSRecord{Type: "TXT", Content: label}
	records1, err := api.DNSRecords(context.Background(), zoneID, host1)
	if err != nil {
		fmt.Println(err)
		return
	}

	for _, r := range records1 {
		fmt.Println(r.Content)
	}
	fmt.Println(fmt.Sprintf(" ary size %v", len(records1)))
}
```

When running the above snippet:

```go
go run main.go
heritage=casper-3,environment=production
 ary size 0
```

So, the equality match works as expected. However when using `cloudflare.DNSRecord{Type: "TXT", Content: label}` where label is `const label = "heritage=casper-3,environment=production"` the result is an empty array. I would expect an array with one element.

**Comment by jacobbednarz** [comment]
Thanks for this one @atmosx! From the investigation, it looks like the library is working as intended however I think your TXT value is throwing off the results search due to the multiple `key=value` parameters and the fact that the default match parameter is "all". There are a few ways forward with this however I think the last is off the table as this appears to be working fine for the majority of users and there are workarounds in the first two you could use.

1. Don't use `key=value` values for TXT with match set to "all".
2. Update your search `Content` value to be prefixed with `contains:` for fuzzy matching. Unsure if this will have other side effects so YMMV.
    ```diff
    -host1 := cloudflare.DNSRecord{Type: "TXT", Content: label}`
    +host1 := cloudflare.DNSRecord{Type: "TXT", Content: "contains:"+label}`
    ```
3. We update the library to allow toggling the `match` parameter.
