### ISSUE TITLE
Make all List* methods automatically paginate results

### ISSUE THREAD

**Issue by jacobbednarz** [cloudflare/cloudflare-go#619]
### Current cloudflare-go version

0.15.0

### Description

When fetching resources, all resources should be returned automatically and the end user shouldn't need to explicitly do it.

**Comment by cdloh** [comment]
@jacobbednarz are you happy to accept PRs for this? I'm looking for this for the CustomHostnames endpoint.

**Comment by jacobbednarz** [comment]
Sure thing. See the zones endpoint for example.

**Comment by cdloh** [comment]
Gotcha. Will give it a shot @jacobbednarz !

Some of the endpoints use for loops (DNSRecords for eg) over sync.WaitGroup. Do you want to use sync.WaitGroup for any going forward?

**Comment by jacobbednarz** [comment]
Yeah, I think that's fine. Unless we have good reason not to?

**Comment by favonia** [comment]
I want to point out that the current `ListZones` and `ListZonesContext` might be flawed; see my pull request #674.

**Comment by jacobbednarz** [comment]
this is no longer required as we will be taking a different approach with the experimental client (for v2) with different, yet consistent interfaces.

see for initial musings https://github.com/cloudflare/cloudflare-go/blob/master/docs/experimental.md
