### ISSUE TITLE
[feature] Automatically Build + Upload flarectl

### ISSUE THREAD

**Issue by elithrar** [cloudflare/cloudflare-go#62]
https://docs.travis-ci.com/user/deployment/releases
- [ ] Update .travis.yml with an (encrypted) OAuth key and the relevant config
- [ ] Ensure that new builds on master upload new binaries for OS X, Linux and Windows.

**Comment by rkantos** [comment]
Any idea why this is won't fix? Might at least want to update this part to reflect the current status:
https://support.cloudflare.com/hc/en-us/articles/360000841472-Adding-Multiple-Sites-to-Cloudflare-via-Automation
> Adding Domains via flarectl (Cloudflare's CLI tool) 
> You can also add domains using flarectl, Cloudflare's official CLI. You can download a pre-built package for your operating system (Windows, macOS/Darwin, Linux) and create domains using it.
> 
> You'll need to set your API credentials first:

**Comment by nocive** [comment]
haven't you heard? it's the new trend, give no feedback to the community created issues and just close them for "staleness" 3 years later. Rinse, repeat, profit.
