### ISSUE TITLE
Getting 400: Invalid request headers (6003) flarectl

### ISSUE THREAD

**Issue by zycon** [cloudflare/cloudflare-go#643]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.17.0

### Go environment

GO111MODULE=""
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOENV="/home/pi/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
GOARM="6"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2908074601=/tmp/go-build -gno-record-gcc-switches"

### Expected output

Print user and zone information
![image](https://user-images.githubusercontent.com/36449874/118882392-34fe7b00-b905-11eb-81f1-68739a543366.png)

Issue happens in cloudflare-go sdk too

### Actual output

HTTP status 400: Invalid request headers (6003)

Cannot make any authenticated requests. Getting failed though `flarectl i ` works which doesn't req auth i believe 

### Code demonstrating the issue

flarectl z  l

### Steps to reproduce

flarectl fresh installation

**Comment by jacobbednarz** [comment]
How are you providing authentication to `flarectl`? All endpoints require authentication; you can see examples in the [README](https://github.com/cloudflare/cloudflare-go/tree/master/cmd/flarectl#usage).

**Comment by zycon** [comment]
Yes, i tried with setting env values only, but I don’t get why am getting 400 instead 402 or 403 . Is there any way to log headers

**Comment by zycon** [comment]
Oh, there was something wrong with my local env, Thanks for your time.
