### ISSUE TITLE
DNS Firewall API unusable due to it using no longer supported API endpoints

### ISSUE THREAD

**Issue by luqasn** [cloudflare/cloudflare-go#644]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

master (0e0a80b)

### Go environment

not relevant

### Expected output

I can list my dns clusters

### Actual output

404 Not Found

### Code demonstrating the issue

Not required, just look at the urls in the code

### Steps to reproduce

- Open the file containing the virtual DNS api method:  https://github.com/cloudflare/cloudflare-go/blob/master/virtualdns.go#L93
- Look at the api urls and find that they all use the `/user/virtual_dns/` base url.
- Look at the `v4` documentation: https://api.cloudflare.com/#dns-firewall-list-dns-firewall-clusters
- See that the dns firewall has moved from the user level to the account level. Old url nowhere to be found, no longer supported.

**Comment by jacobbednarz** [comment]
@luqasn are you able to point out which version you were using when this was working for you? Looking through the history, virtual DNS has only ever been supported at the user level. 

Could you also provide an example of the code you intending to use per the issue template to demonstrate how you are expecting to use this library?

**Comment by luqasn** [comment]
It broke for us on the 17th of March without any changes on our end. But this was kinda to be expected at some point because we received an email end of last year from Cloudflare saying 
> Jimdo is using deprecated DNS Firewall API endpoints:
GET organizations/:organization_identifier/virtual_dns POST organizations/:organization_identifier/virtual_dns GET organizations/:organization_identifier/virtual_dns/:identifier PATCH organizations/:organization_identifier/virtual_dns/:identifier DELETE organizations/:organization_identifier/virtual_dns/:identifier GET organizations/:organization_identifier/virtual_dns/:identifier/dns_analytics/report GET organizations/:organization_identifier/virtual_dns/:identifier/dns_analytics/report/bytime
We have since switched to account level DNS Firewall endpoints, found here: https://api.cloudflare.com/#dns-firewall-properties.

These calls were originating from our customer prometheus cloudflare exporter that internally uses `cloudflare-go`. I don't know why it says `organizations/:organization_identifier/virtual_dns`, as we have never been using anything else than the code in our fork (see below) that calls things under the `user/` path.

For the last 3 years we had been using [a branch](https://github.com/Jimdo/cloudflare-go/commits/virtualdns_analytics) of our [outdated fork](https://github.com/Jimdo/cloudflare-go) of `clouflare-go` because the virtual dns analytics change we contributed [took half a year to land](https://github.com/cloudflare/cloudflare-go/pull/183).

But we have now gone back to upstream cloudflare-go (version 0.14.0), which did not fix the issue, but that is to be expected if one assumes the no longer documented, deprecated `user/:userId/virtual_dns` is to blame, because there were no changes to the url layout for virtual dns ever since their introduction 5 years ago: https://github.com/cloudflare/cloudflare-go/blame/c6c01e523bd7d6140614d9e8f83ef97116966a67/virtualdns.go#L109

The code that is first to fail for us is this one:
```
clusters, err := collector.virtualDNS.ListVirtualDNS(context.Background())
```
and we get the following error:
> HTTP status 400: No route for that URI (7000)

Thanks for having a look!

**Comment by luqasn** [comment]
This is the url that this library uses to fetch dns clusters (as an example, same problem for other virtualdns calls):
`GET user/virtual_dns`

This is what cloudflare api documentation says you should use:
`GET accounts/:account_identifier/virtual_dns`

**Comment by jacobbednarz** [comment]
Thanks for the additional context as this now makes sense. Your title including "due to it using no longer supported API endpoints" suggested a regression however that isn't the case; this is an enhancement to include the updated levels of support.

Are you interested in opening a PR for this one?

**Comment by jacobbednarz** [comment]
You can use [`api.userBaseURL("/user")`](https://github.com/cloudflare/cloudflare-go/blob/d830806bd5d75b1ff2ab395227d112e3a42f0511/cloudflare.go#L334) instead of the hardcoded value. An example can be found in the load balancing methods at https://github.com/cloudflare/cloudflare-go/blob/d830806bd5d75b1ff2ab395227d112e3a42f0511/load_balancing.go#L224

**Comment by luqasn** [comment]
> Thanks for the additional context as this now makes sense. Your title including "due to it using no longer supported API endpoints" suggested a regression however that isn't the case; this is an enhancement to include the updated levels of support.
> 
> Are you interested in opening a PR for this one?

I don't know if we understand each other yet. What I was trying to say with the title and the explanations is "The part of this library that talks to the DNS Firewall API does not work at all. This is due to it using Cloudflare API endpoints that straight up don't exist (anymore)".
To me, that is not a request for enhancement.

I would prefer not to fix this myself as that would give me more time to work on business things :)

**Comment by jacobbednarz** [comment]
We're on the same page 😄 This issue is conflating Cloudflare (the service) with cloudflare-go (the library) and where deprecations/changes have happened. The enhancement portion is for the library as we're both aware, it hasn't ever supported it and only supported user level resources. To avoid introducing a breaking change here, we'll need to go the route of `api.userBaseURL("/user")` and then people explicitly opt into the account level features by setting the account ID with `UsingAccount` or similar.

I'll take a look at a PR shortly.

**Comment by jacobbednarz** [comment]
this is now in master and will be scheduled for the next release.

**Comment by luqasn** [comment]
Thanks a lot for your support and your swift action :)
