### ISSUE TITLE
Method documentation error

### ISSUE THREAD

**Issue by jvilhuber** [cloudflare/cloudflare-go#654]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

any

### Go environment

doesn't matter

### Expected output

// VerifyAPIToken tests the validity of the token.
//
// API reference: https://api.cloudflare.com/#user-api-tokens-verify-token
func (api *API) VerifyAPIToken(ctx context.Context) (APITokenVerifyBody, error) {

### Actual output

// VerifyAPIToken rolls the value associated with the token.
//
// API reference: https://api.cloudflare.com/#user-api-tokens-roll-token
func (api *API) VerifyAPIToken(ctx context.Context) (APITokenVerifyBody, error) {

### Code demonstrating the issue

https://github.com/cloudflare/cloudflare-go/blob/master/api_token.go#L193-L196

### Steps to reproduce

https://github.com/cloudflare/cloudflare-go/blob/master/api_token.go#L193-L196

### References

https://github.com/cloudflare/cloudflare-go/blob/master/api_token.go#L193-L196

**Comment by jacobbednarz** [comment]
closed by #655
