### ISSUE TITLE
Normalization of DNS record names

### ISSUE THREAD

**Issue by favonia** [cloudflare/cloudflare-go#688]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.20.0

### Go environment

<details><summary><code>go env</code></summary>

```
GO111MODULE=""

GOARCH="amd64"

GOBIN=""

GOCACHE="/home/***/.cache/go-build"

GOENV="/home/***/.config/go/env"

GOEXE=""

GOFLAGS=""

GOHOSTARCH="amd64"

GOHOSTOS="linux"

GOINSECURE=""

GOMODCACHE="/home/***/go/pkg/mod"

GONOPROXY=""

GONOSUMDB=""

GOOS="linux"

GOPATH="/home/***/go"

GOPRIVATE=""

GOPROXY="https://proxy.golang.org,direct"

GOROOT="/usr/lib/go"

GOSUMDB="sum.golang.org"

GOTMPDIR=""

GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"

GOVCS=""

GOVERSION="go1.16.6"

GCCGO="gccgo"

AR="ar"

CC="gcc"

CXX="g++"

CGO_ENABLED="1"

GOMOD="/dev/null"

CGO_CFLAGS="-g -O2"

CGO_CPPFLAGS=""

CGO_CXXFLAGS="-g -O2"

CGO_FFLAGS="-g -O2"

CGO_LDFLAGS="-g -O2"

PKG_CONFIG="pkg-config"

GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build***=/tmp/go-build -gno-record-gcc-switches"
```
</details>

### Expected output

Showing the DNS record that was just added, because the same internationalized domain name was used.

### Actual output

No record:
```
[]cloudflare.DNSRecord(nil)
```

### Code demonstrating the issue

```go
func main() {
	const UNICODE_DOMAIN = "😺.meow.org"

	handle, _ := cloudflare.NewWithAPIToken(CF_API_TOKEN)

	handle.CreateDNSRecord(context.Background(), ZONE_ID,
		cloudflare.DNSRecord{
			Name:    UNICODE_DOMAIN,
			Type:    "A",
			Content: "10.10.10.10",
		})

	rs, _ := handle.DNSRecords(context.Background(), ZONE_ID,
		cloudflare.DNSRecord{
			Name: UNICODE_DOMAIN,
		})

	fmt.Printf("%v", rs)
}
```

### Steps to reproduce

1. Choose any IDN.
2. Add a DNS record with that name using `CreateDNSRecord`.
3. List DNS records using `DNSRecords` with the `name` parameter set to the same name.

### Discussions + References

According to my experiments, Cloudflare API expects **ASCII** forms (e.g., `xn--138h.org`) for DNS record names. However, it seems to expect **Unicode** forms (e.g., `😺.org`) for zone names (see #347). I am very confused by this inconsistency, and could not find related information in the API documentation. Where is this documented? In any case, we can probably put in some code to provide a more intuitive interface as in #348, but I wish to get some confirmation before creating a PR.

To do the Punycode encoding by ourselves, there are many different options due to the complexity introduced by the incompatible IDNA2003 and IDNA2008. I believe we should use the UTS 46 nontransitional processing ("C2" as defined in https://unicode.org/reports/tr46/#Conformance) which would be different from any predefined profiles in the Go package `x/net/idna`. Here's my assessment of those "built-in" profiles in that package:
1. `idna.ToASCII` and `idna.Punycode.ToASCII` are not doing any mapping or checking, so `ÖBB` would be different from `öbb`, which might be different from the library users' expectations.
2. `idna.Lookup.ToASCII` will map `ß` to `ss`, which is different from what the Cloudflare server is doing. 
3. `idna.Display.ToASCII` is actually fine, but it is more like a coincidence---the name `Display` could be misleading.
4. `idna.Registration.ToASCII` does not map `ÖBB` to `öbb`, either.

PS: In golang/go#47510, I proposed to add a predefined profile for the nontransitional processing mentioned here.

**Comment by jacobbednarz** [comment]
The API for searching zones by name supports either (ascii or unicode) however it returns unicode as you've mentioned. I've done some digging in the past at cloudflare/Cloudflare-WordPress#412 if you're interested in more details.

**Comment by favonia** [comment]
> The API for searching zones by name supports either (ASCII or UNICODE) however it returns unicode as you've mentioned. I've done some digging in the past at [cloudflare/Cloudflare-WordPress#412](https://github.com/cloudflare/Cloudflare-WordPress/pull/412) if you're interested in more details.

Got it. So, all the zone search actually works without conversion now, because we have outsourced all comparison to the Cloudflare servers (which was not the case when #347 was reported). In sum, there are two protections that make zones work as expected: (1) we do the conversion and (2) we let the server to do the filtering. We are very safe with zones now.

Then I think it is more like a bug of the Cloudflare server that DNS record search (using the `name` parameter) does not work for both ASCII and Unicode forms. I wonder how I can make some noise about it. Another weird thing is that the server did not following UTS 46 to preprocess `ÖBB` to `öbb` either. At this point I really think the server is at fault, though we (or I) can make the library code extremely robust before the server is fixed.

A minor point I want to bring up for your patch to cloudflare/Cloudflare-WordPress#412: you were using the transitional processing, which would map `ß` to `ss`, where Cloudflare follows a different standard which keeps them separate. Unfortunately, I am not familiar with PHP to (just) turn off that transitional processing. (There is `IDNA_NONTRANSITIONAL_TO_ASCII` but I don't know if that also enables or disables something else compared to `IDNA_DEFAULT`). On the other hand, I have studied the current Go `idna` package thoroughly and know the exact options I need (see golang/go#47510).

**Comment by favonia** [comment]
@jacobbednarz I made some noise in cloudflare/cloudflare-docs#1991. I am planning to make a PR to normalize all domain-related inputs within `dns.go` to their ASCII forms before talking to the server. Let me know if something else should be done and I will follow suit.

**Comment by jacobbednarz** [comment]
I’d recommend opening a support ticket which will result in an internal
ticket to investigate. The docs repository is for the documentation at
developers.cloudflare.com and not the API itself.

**Comment by jacobbednarz** [comment]
As for the proposed DNS changes, I'll have a think about it (on vacation next week) and let you know.

**Comment by favonia** [comment]
> As for the proposed DNS changes, I'll have a think about it (on vacation next week) and let you know.

I just made a PR implementing the proposed workaround. Feel free to discard it if you prefer a different solution.
