### ISSUE TITLE
"Custom SSL certificates for a zone" doesn't work?

### ISSUE THREAD

**Issue by MeMarik** [cloudflare/cloudflare-go#689]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.20.0

### Go environment

go env

### Expected output

Working?

### Actual output

This feature doesn't work, or i don't know how to correctly use it 
<img width="509" alt="Знімок екрана 2021-08-06 о 16 50 35" src="https://user-images.githubusercontent.com/88437376/128520499-11578a8c-fe8d-4d69-a3ac-f5d97d3628db.png">

### Code demonstrating the issue

...

### Steps to reproduce

...

**Comment by jacobbednarz** [comment]
My apologies, but it looks like this never got implemented and returning `nil` isn't particularly helpful.

https://github.com/cloudflare/cloudflare-go/blob/b85431ccad52fbd3c8cd827c3655af3df9346419/cmd/flarectl/zone.go#L14-L16

`flarectl` isn't getting a whole heap of love at the moment and is essentially only in maintenance mode. We're hoping to fix a bunch of this in the future (with our SDKs) but for now, I'd recommend using `cloudflare-go` directly if you'd like this functionality. 

I'm also open to reviewing a PR that either removes the command (making this less confusing for others) or implementing the certificate endpoint (improving the workflow for you).
