### ISSUE TITLE
Traefik with Cloudflare DNS acme resolver and ZeroSSL

### ISSUE THREAD

**Issue by samip5** [cloudflare/cloudflare-go#692]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

No idea, using though Traefik v2.4.13

### Go environment

Unable to check as it's being ran from inside Traefik.

Traefik version: 2.4.13

### Expected output

It would work?

### Actual output

time="2021-08-08T11:03:26+03:00" level=error msg="Unable to obtain ACME certificate for domains \"dh.samip.dev,dh4.samip.dev,dh6.samip.dev\": unable to generate a certificate for the domains [dh.samip.dev dh4.samip.dev dh6.samip.dev]: error: one or more domains had a problem:\n[dh.samip.dev] [dh.samip.dev] acme: error presenting token: cloudflare: failed to find zone samip.dev.: ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)

### Code demonstrating the issue

N/A

### Steps to reproduce

1. Use Traefik
2. Use ZeroSSL
3. Configure Traefik to use ZeroSSL and Cloudflare DNS for challange
4. Have it fail

### References

https://github.com/go-acme/lego/issues/1460

**Comment by samip5** [comment]
I'm aware that I didin't exactly follow the template, but I'm not sure if that error is from the API or where the error comes from.

**Comment by jacobbednarz** [comment]
I'm sorry, we need more information or a reproducible test case doing this outside of the tool implementing it as this is working with just this library. Have you confirmed the credentials are being passed through correctly? What is the HTTP traffic to the API looking like?

Failing that, I'd recommend chatting with the maintainers of the tool you're using to diagnose where this is happening.

**Comment by samip5** [comment]
I was able to reproduce the error with:

```go
package main

import (
        "context"
        "fmt"
        "log"
        "os"

        "github.com/cloudflare/cloudflare-go"
)

func main() {
        // Construct a new API object
        api, err := cloudflare.New(os.Getenv("CF_API_KEY"), os.Getenv("CF_API_EMAIL"))
        if err != nil {
                log.Fatal(err)
        }

        // Most API calls require a Context
        ctx := context.Background()

        // Fetch user details on the account
        u, err := api.UserDetails(ctx)
        if err != nil {
                log.Fatal(err)
        }
        // Print user details
        fmt.Println(u)

        // Fetch zone details
        zone, err := api.ListZonesContext(ctx)
        if err != nil {
                log.Fatal(err)
        }
        // Print zone details
        fmt.Println(zone)
}
```

Log:
```
2021/08/08 10:19:36 HTTP status 400: Invalid request headers (6003)
exit status 1
```

**Comment by jacobbednarz** [comment]
I'm afraid my your reproduction is working here. Are you able to try running your test through a MITM proxy like [proxyman](https://proxyman.io/), [mitmproxy](https://mitmproxy.org/), [charles proxy](https://www.charlesproxy.com/) or [fiddler](https://www.telerik.com/fiddler) to see what the HTTP interactions look like?

**Comment by jacobbednarz** [comment]
it would also be helpful to identify which version of cloudflare-go this is using to narrow down any potential issues there.

**Comment by samip5** [comment]
It seems that it was the result of an incorrect API key, even when I had checked that it was supposed to be right. Closing.

**Comment by jacobbednarz** [comment]
Good to know you got this sorted!

**Comment by koljam** [comment]
For others coming here: My mistake was that I created Cloudflare API Tokens. But we need to provide the Global API Key.
From the [Docs](https://doc.traefik.io/traefik/v1.6/configuration/acme/):

> CLOUDFLARE_EMAIL, CLOUDFLARE_API_KEY - The Global API Key needs to be used, not the Origin CA Key

I hope this helps someone in the future!
