### ISSUE TITLE
Adding more examples

### ISSUE THREAD

**Issue by Prajwal-Koirala** [cloudflare/cloudflare-go#696]
### Current cloudflare-go version

latest

### Description

Please add more examples.
I was planning on using this library but its massive, and needs more example for a person to be able to use this codebase.

thanks.

### Use cases

.

### Potential cloudflare-go usage

```go
.
```

**Comment by jacobbednarz** [comment]
please check out the unit tests or implementations in the [Terraform provider](https://github.com/cloudflare/terraform-provider-cloudflare/).
