### ISSUE TITLE
Support for Cloudflare pages

### ISSUE THREAD

**Issue by alexdor** [cloudflare/cloudflare-go#707]
### Current cloudflare-go version

0.22.0

### Description

Support for Cloudflare pages https://api.cloudflare.com/#pages-project-properties 

### Use cases

To be able to add/edit/delete cloudflare project pages through terraform 

### Potential cloudflare-go usage

```go
Not sure to be honest
```

### References

* related issue on the provider side https://github.com/cloudflare/terraform-provider-cloudflare/issues/1037

**Comment by jacobbednarz** [comment]
closed in #724
