### ISSUE TITLE
Cloudflare Spectrum origin_dns doesn't match API docs

### ISSUE THREAD

**Issue by Minh-Ng** [cloudflare/cloudflare-go#716]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.24.0

### Go environment

1.16

### Expected output

A cloudflare_spectrum_application was created.

### Actual output

Error: error creating spectrum application for zone: HTTP status 400: The origin DNS configuration is invalid. (11001)

### Code demonstrating the issue

// Run the equivalent of 
```
resource "cloudflare_spectrum_application" "ssh_proxy" {
  zone_id      = var.cloudflare_zone_id
  protocol     = "tcp/22"
  traffic_type = "direct"
  dns {
    type = "CNAME"
    name = "ssh.example.com"
  }

  origin_dns {
    name = "myorigin.exampleorigin.com"
  }
```

### Steps to reproduce

Try to curl the cloudflare_spectrum_application creation (zones/:zone/spectrum/apps) with --data
```
{"protocol":"tcp/22","dns":{"type":"CNAME","name":"ssh.example.com"},"origin_port": "22","origin_dns":{"name":"myorigin.exampleorigin.com"},"proxy_protocol":"off","ip_firewall":true,"tls":"full","edge_ips":{"type":"dynamic","connectivity":"all"},"traffic_type":"direct","argo_smart_routing":true}
```

### References

origin_dns is referenced here: https://developers.cloudflare.com/spectrum/reference/settings-by-plan
and here: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/spectrum_application (obviously from cloudflare-go)

but origin_dns does not exist here: https://api.cloudflare.com/#spectrum-applications-create-spectrum-application

The spectrum.go file is missing OriginDNS.Type and OriginDNS.TTL if origin_dns is still a valid parameter. If it is not, how can we point a spectrum application at a Cloudflare Load Balancer?

**Comment by jacobbednarz** [comment]
Are you able to clarify the ask here? Is your issue that the API documentation doesn't match the developer documentation? A rule of thumb is that the SDKs only implement what is publicly documented so if that's the case, I'll have to request you open a support ticket to have it routed to the correct internal team for this one.

**Comment by Minh-Ng** [comment]
> Is your issue that the API documentation doesn't match the developer documentation?
Yes that is accurate. If the go client only matches the publicly documented API, then [origin_dns](https://github.com/cloudflare/cloudflare-go/blob/master/spectrum.go#L157) should not be available as a configuration option. If the go client is saying that is a valid field, it should have TTL and Type. I can definitely open up a support ticket to get this sorted out but this seems like something that Cloudflare may want to work towards keeping in sync across the board.

Additionally as a note, the comments in spectrum.go no longer point toward any valid documentation if the idea is to implement publicly documented APIs.

**Comment by jacobbednarz** [comment]
🆒 definitely submit a support ticket and we can get the public API updated which in turn can update the cloudflare-go library (with hopefully new documentation links too!). Closing this one off for now and we can see if the internal team wants to make the changes here or we can do it in a future update.

thanks!
