### ISSUE TITLE
Writing to Workers KV fails if using cloudflare.NewWithAPIToken

### ISSUE THREAD

**Issue by mountainerd** [cloudflare/cloudflare-go#721]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.24.0

### Go environment
   
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/redacted/path/Caches/go-build"
GOENV="/redacted/path/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/redacted/path/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/redacted/path/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/redacted/path/godns/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r1/y2yh4xbd77xbdr3bmsnfwdhx07rbt0/T/go-build2848968445=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Expected output

A successful write to the WorkerKV specified in the call.

### Actual output

```
HTTP status 405: PUT method not allowed for the api_token authentication scheme (10000)
```

### Code demonstrating the issue

```go
api, err := cloudflare.NewWithAPIToken("token goes here")
if err != nil {
  log.Fatal(err)
}

api.AccountID = "account id goes here"

req := &cloudflare.WorkersKVNamespaceRequest{
  Title: "test321",
}

response, err := api.CreateWorkersKVNamespace(context.Background(), req)
if err != nil {
  log.Fatal(err)
}

resp, err := api.WriteWorkersKV(context.Background(), "test321", "foo", []byte("bar"))
if err != nil {
  log.Fatal(err)
}
```

### Steps to reproduce

1. Instantiate a new client using `cloudflare.NewWithAPIToken`
2. Add account ID to `api.AccountID`
3. Try to write to a Worker KV using `api.WriteWorkersKV`

**Comment by mountainerd** [comment]
I opened this issue as it seems at odds with the reasoning and recommendations found on the [**API Keys (Legacy)**](https://developers.cloudflare.com/api/keys) documentation page. The only option at this point is to write my service with an API Key that has far more permissions than this service needs instead of using a Token appropriately scoped.

**Comment by jacobbednarz** [comment]
I'm afraid not all services fully support API tokens however the teams are working on adding incremental support. This isn't something we can solve in the libraries (we only use the available auth + APIs) so I'm closing this one out.  If you'd like to stay in the loop of when certain services as API token support, I would suggest you open a support ticket and then can loop you in if the team provides updates.

**Comment by jacobbednarz** [comment]
Alright, we managed to track down what the dealio is here and the good news is it's an easy fix 😃 The second parameter of `WriteWorkersKV` is actually the namespace _ID_ not the name (as the repro shows). The annoying part of this was actually tracking this down internally as because the route validation didn't match a pattern for namespace ID it would fail with that exception as technically the route doesn't have API token support (very misleading).

```diff
api, err := cloudflare.NewWithAPIToken("token goes here")
if err != nil {
  log.Fatal(err)
}

api.AccountID = "account id goes here"

req := &cloudflare.WorkersKVNamespaceRequest{
  Title: "test321",
}

response, err := api.CreateWorkersKVNamespace(context.Background(), req)
if err != nil {
  log.Fatal(err)
}

-resp, err := api.WriteWorkersKV(context.Background(), "test321", "foo", []byte("bar"))
+resp, err := api.WriteWorkersKV(context.Background(), resp.Result.ID, "foo", []byte("bar"))
if err != nil {
  log.Fatal(err)
}
```

Can you give this a go and let me know how you end up?

**Comment by mountainerd** [comment]
Also: apologies to anybody else on your team who had to waste time sorting this out.
