### ISSUE TITLE
flarectl can't run without credentials provided

### ISSUE THREAD

**Issue by Tenzer** [cloudflare/cloudflare-go#73]
The error handling made in 586e5a55, means that `flarectl` no longer can run without the environment variables with credentials being set to at least something. This doesn't give the best user experience, since neither `flarectl --help` or `flarectl ips` work any more, even though none of them make API calls which use credentials.

We may have to change `flarectl` so `cloudflare.New()` only will be called by the functions that actually need the authenticated API to function. A helper method can be introduced in order to minimise the code duplication. Any other suggestions?

**Comment by jamesog** [comment]
Fixed in 7bbb639.
