### ISSUE TITLE
Issue deleting a Zone that has status "moved"

### ISSUE THREAD

**Issue by mogthesprog** [cloudflare/cloudflare-go#736]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.27.0

### Go environment

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/morganj/Library/Caches/go-build"
GOENV="/Users/morganj/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/morganj/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/morganj/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t3/z674kjln3c31lrpv383rh9d00000gn/T/go-build018199251=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Expected output

deletes the dns zone

### Actual output

me@mac-mini> flarectl --account-id=##### z d --zone cf-test.beans.cheese
ambiguous zone name; an account ID might help

fails to delete the dns zone

### Code demonstrating the issue

N/A, using flarectl

### Steps to reproduce

1. have a dns zone in the "moved" state
2. have another dns zone with the same domain name in another account
3. want to delete the original "moved" dns zone
4. output of `flarectl z l`
                 ID                |             NAME              |        PLAN        | STATUS
-----------------------------------+-------------------------------+--------------------+----------
  9bf4a61990c16b1ccaf7ffce250ed484 | cf-test.beans.cheese       | Enterprise Website | moved
  6937452174f12979f35a7fb39a188c1b | cf-test.beans.cheese       | Enterprise Website | active
5. attmpt to delete the zone with state "moved" 
me@mac-mini> flarectl --account-id=##### z d --zone cf-test.beans.cheese
ambiguous zone name; an account ID might help

### References

Not that i can see.

**Comment by jacobbednarz** [comment]
looks like the `account-id` parameter isn't taken into account for the `ZoneIDByName` lookup for deletes https://github.com/cloudflare/cloudflare-go/blob/8160849490b166aaf93320c691c57b2d24855cdf/cmd/flarectl/zone.go#L99

if you want to send over a PR, i'm happy to review this one

**Comment by mogthesprog** [comment]
I think the problem actually looks like it's in the CLI only, in misc.go.

https://github.com/cloudflare/cloudflare-go/blob/master/cmd/flarectl/misc.go#L47-L49

Looks like here we're not properly setting account-id in the cli. I'll send a PR over in a sec.
