### ISSUE TITLE
Expose validation records field of certificate packs

### ISSUE THREAD

**Issue by startnow65** [cloudflare/cloudflare-go#741]
### Current cloudflare-go version

0.27.0

### Description

`validation_records` field is returned from the [get certificate](https://api.cloudflare.com/#certificate-packs-get-certificate-pack) call. This field is however not parsed into the `CertificatePack` struct and hence unavailable to users of the library.

### Use cases

The TXT value returned by the `validation_records` field is useful for fully automating the certificate ordering process as this value can be passed onwards to another step that creates the TXT records on the relevant DNS server.

### Potential cloudflare-go usage

```go
// from: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_certificate_pack.go#L116
func resourceCloudflareCertificatePackRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*cloudflare.API)
	zoneID := d.Get("zone_id").(string)

	certificatePack, err := client.CertificatePack(context.Background(), zoneID, d.Id())
	if err != nil {
		return errors.Wrap(err, "failed to fetch certificate pack")
	}

	d.Set("type", certificatePack.Type)
	d.Set("hosts", expandStringListToSet(certificatePack.Hosts))

	// This would be a new computed attribute of the cloudflare_certificate_pack resource
	d.Set("validation_records", <some function>(certificatePack.ValidationRecords))

	return nil
}
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1052

**Comment by jacobbednarz** [comment]
closed by #796
