### ISSUE TITLE
Expose Cloudlare API error codes as constants

### ISSUE THREAD

**Issue by Lionesk** [cloudflare/cloudflare-go#745]
### Current cloudflare-go version

v0.27.0

### Description

Errors returned from the API are converted into `APIRequestError` which contain a slice of errors of type `ResponseInfo`. Each of these has a code, and it would be good to have those error codes exposed as constants in `cloudflare-go`.

### Use cases

When handling errors it is useful to write a switch off of an error code. Currently `cloudflare-go` does not expose the canonical error codes, so they must be captured by the developers, which is more error-prone.

### Potential cloudflare-go usage

```go
resp, err := api.CreateWorkerRoute(ctx, zoneID, route)
if err != nil {
    if cfErr, ok := err.(cloudflare.APIRequestError); ok {
        for _, e := range cfErr.Errors {
            switch e.Code {
            case cloudflare.SomeErrorCode:
                foo()
            case cloudflare.AnotherErrorCode:
                bar()
            }
        }
    }
}
```

**Comment by jacobbednarz** [comment]
sorry, this isn’t something we’ll do for the backing services in the current state of the library. the errors are service specific and there is no way to export the internals to this library without a massive duplication effort. perhaps in the future we can revisit this but for now, we only support a few known cases from the HTTP statuses or internal library errors. if you wish you can use Golang `contains` to inspect the error message and handle your custom logic from there.
