### ISSUE TITLE
prefix methods that fetch a single item with `Get`

### ISSUE THREAD

**Issue by tjstansell** [cloudflare/cloudflare-go#755]
### Current cloudflare-go version

0.28.0

### Description

Similar to #612, perhaps all methods should use a standardized naming that has a verb prefix.  Since `List` already has its own issue, I think the remaining methods that do not already use a verb prefix are querying a single resource and should use the `Get` prefix, which is already used for some resources.

### Use cases

Similar to the argument for List, this could help with autocomplete

### Potential cloudflare-go usage

```go
just like now, but prefixed with Get.
```

### References

* #612

**Comment by tjstansell** [comment]
Related to this, is there a deprecation framework for api-incompatible change like this?  These new function names could easily be added and then deprecation warnings on the old names could be introduced to warn folks they'll be removed at a future date.  Just not sure if there's already a process for this kind of thing in place.

**Comment by jacobbednarz** [comment]
an approach like #758 is preferable and like you suggest; add new methods wrapping the old ones and eventually deprecate the old ones after a few releases.

**Comment by jacobbednarz** [comment]
this is no longer required as we will be taking a different approach with the experimental client (for v2) with different, yet consistent interfaces.

see for initial musings https://github.com/cloudflare/cloudflare-go/blob/master/docs/experimental.md
