### ISSUE TITLE
Add 'Healthy' to LoadBalancerPool struct

### ISSUE THREAD

**Issue by justinb-shipt** [cloudflare/cloudflare-go#767]
### Current cloudflare-go version

0.29.0

### Description

When I was querying the API via cURL, I noticed they had an additional property called `Healthy` that's not in the LoadBalancerPool struct:

```
curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/load_balancers/pools" \
     -H "X-Auth-Email: ${AUTH_EMAIL}" \
     -H "X-Auth-Key: ${API_TOKEN_ID}" \
     -H "Content-Type: application/json"
```

```
    {
      "description": "",
      "created_on": "2021-05-25T21:26:30.371603Z",
      "modified_on": "2021-08-27T04:08:42.784446Z",
      "id": "POOL_ID",
      "enabled": true,
      "minimum_origins": 1,
      "monitor": "MONITOR_ID",
      "name": "us-east-4",
      "notification_email": "",
      "check_regions": null,
      "healthy": true,
      "origins": [
        {
          "name": "api-gateway-east4",
          "address": "api-gcp-east-k8s.example.com",
          "enabled": true,
          "weight": 1,
          "healthy": true,
          "failure_reason": "No failures"
        }
      ]
    }
```

We are hitting the v4 API and it's not completely showing up in the documentation here: https://api.cloudflare.com/#account-load-balancer-pools-list-pools. But if you look at the `notification_filters`, you can filter on Pool health.

```
      "notification_filter": {
        "origin": {
          "disable": false,
          "healthy": null
        },
        "pool": {
          "disable": false,
          "healthy": null
        }
      }
```

So was this just missed in the API docs or is it undocumented? You can get the health status of the pool from the web UI. A single place to pull the status makes sense.

### Use cases

We would like to easily monitor the health of our LB Pools. Obviously, we could loop through each `origins`, check their health and then make sure we meet the `minimum_origins` requirement... but what fun is that when CloudFlare already provides a property for you?

### Potential cloudflare-go usage

```go
Easily monitor the health of Load Balancer Pools.
```

**Comment by justinb-shipt** [comment]
I've also been digging down through `cloudflare.LoadBalancerPoolHealth` and that gets ugly.

**Comment by jacobbednarz** [comment]
@justinb-shipt if the field isn't documented, we won't add it to the clients due to it not being considered publicly stable. 

@gofish is this intentionally omitted or should we update api.cloudflare.com to reflect the intent here?

**Comment by gofish** [comment]
@jacobbednarz Interesting, I think it's missing from the POST/PUT/PATCH methods intentionally as that field is read-only, but it is supported in GET responses and should be documented. Filing this for an update along with API doc changes to be released soon.

**Comment by justinb-shipt** [comment]
Is this also the case for `Healthy` and `Failure Reason` on the origins[] (LoadBalancerOrigin struct)? My example above includes those fields too.

I'm also happy to submit a PR once the documentation is updated.

**Comment by gofish** [comment]
Thanks @justinb-shipt, we'll take care of it. Feel free to make use of those fields in your own branch for now; if we deprecate them I'll loop back to this issue to specifically note it.

Would you mind instead providing input on your use case? In particular, (a) what got ugly when digging into `LoadBalancerPoolHealth`, and (b) what you might desire from an independent and improved set of load balancer pool health API endpoints?

Thank you! Please free free to reach out directly if preferred via the email on my profile.

**Comment by justinb-shipt** [comment]
> Thanks @justinb-shipt, we'll take care of it. Feel free to make use of those fields in your own branch for now; if we deprecate them I'll loop back to this issue to specifically note it.

Excellent! Thanks!

> Would you mind instead providing input on your use case? In particular, (a) what got ugly when digging into `LoadBalancerPoolHealth`, and (b) what you might desire from an independent and improved set of load balancer pool health API endpoints?
> 
> Thank you! Please free free to reach out directly if preferred via the email on my profile.

Last month when AWS went down, our Cloudflare Pools failed over before we got any other notifications from the things outside of Cloudflare we monitor (win Cloudflare!). So we want to monitor our Cloudflare Pools directly and we want to be notified via OpsGenie. Email notifications are nice but they can get lost. From what I can tell, I can't do this through Notifications because Alert Types are predefined. I've been looking at making API calls as my solution. I could use cURL & jq but would prefer Go.

To answer (a) it's not terribly ugly, it's 4 loops vs 2 loops to get to the information I want. So going through LoadBalancerPoolHealth you end up at LoadBalancerPoolPopHealth to get to Origins and getting a lot more information than what I find necessary (at this time). I dig down to Origin[] is so I can get the FailureReason. 

I've also seen LoadBalancerPoolPopHealth say a Pool was unhealthy but all of the Origins were healthy. The unhealthy status at the PoolPopHealth has contradicted what I've see from the Healthy field that's missing from the LoadBalancerPool struct on a couple of Pools. But now I'm getting into a potential bug or a lack of understanding on my part that I haven't been able to completely research. So potentially another thread.

```
Pool Origin count: 1 Pool Health Origin count: 1
	LoadBalancerPool.Healthy: true 
	LoadBalancerPoolHealth.Healthy: false 
	LoadBalancerOrigin.Healthy: true 
	Failure Reason: No failures
```

(b) I want the quickest and easiest way to report back on the health of my LoadBalancerPools and any reason why they have been determined unhealthy.

Thanks you for your time! I can provide more concrete code if necessary. It's been a busy day for me.

**Comment by jacobbednarz** [comment]
To be honest, it sounds like _this_ is the crux of the issue for your use case.

> Email notifications are nice but they can get lost. From what I can tell, I can't do this through Notifications because Alert Types are predefined.

Perhaps more appropriate solution would be to have the alert types for notifications include other methods of delivery instead of you doing the work.

**Comment by justinb-shipt** [comment]
Well, yes... if the available Alert Types were expanded to include Pool health, I could create a Notification with a webhook to OpsGenie. Problem solved w/o querying the API. But the only Alert Type I know of for Pools is the following:

From the endpoint: `/accounts/${ACCOUNT_ID}/alerting/v3/available_alerts`.
```
    "Load Balancing": [
      {
        "display_name": "Pool Enablement",
        "type": "g6_pool_toggle_alert",
        "description": "Pool alerts based on enable/disable toggle status"
      }
    ],
```

Again, maybe I'm incorrect, but when a Pool is unhealthy it's not necessarily disabled. And maybe there are other Alert Types I'm not aware of or should consider?

Now within the Pool, if it also allowed webhooks besides just notification_emails, that would be another solution.

**Comment by gofish** [comment]
Integration of Pool health events with Notifications is actually planned for this quarter, FYI. We definitely understand that need. Pool email notifications will then be deprecated and will be fully replaced by Notifications eventually (there will be a migration when that happens).

Regarding (a) note that the field `LoadBalancerPoolHealth.Healthy` does not exist (yet!), the only field available is `LoadBalancerPoolPopHealth.Healthy` for each PoP or Region present in the `LoadBalancerPoolHealth.PopHealth` map. `LoadBalancerPool.Healthy` represents a quorum over all these Regions or PoPs, but appears to not be directly exposed via the actual pool health API endpoint. I'll work to support that to fix this issue, it's a better place for that field than on `LoadBalancerPool` itself!

Regarding (b) we are investigating requirements in order to improve, restructure, or replace this pool health status API, along with the pool health event (logs) API. The latter would be accessed via the GraphQL Analytics like request logs currently, but the future direction of the current pool health API is open for input.

**Comment by justinb-shipt** [comment]
> Integration of Pool health events with Notifications is actually planned for this quarter, FYI. We definitely understand that need. Pool email notifications will then be deprecated and will be fully replaced by Notifications eventually (there will be a migration when that happens).

Excellent news!

> Regarding (a) note that the field `LoadBalancerPoolHealth.Healthy` does not exist (yet!), the only field available is `LoadBalancerPoolPopHealth.Healthy` for each PoP or Region present in the `LoadBalancerPoolHealth.PopHealth` map. `LoadBalancerPool.Healthy` represents a quorum over all these Regions or PoPs, but appears to not be directly exposed via the actual pool health API endpoint. I'll work to support that to fix this issue, it's a better place for that field than on `LoadBalancerPool` itself!

My bad. That was me trying to get a more thorough response but with some lazy naming. ;-) I did mean `LoadBalancerPoolPopHealth`.

> Regarding (b) we are investigating requirements in order to improve, restructure, or replace this pool health status API, along with the pool health event (logs) API. The latter would be accessed via the GraphQL Analytics like request logs currently, but the future direction of the current pool health API is open for input.

Sounds great! I did forget the other use case and the GraphQL Analytics reminded me. I wanted to have the Pool health status available in a Grafana dashboard for our observability team. I was looking to extend Labyrinth Labs' cloudflare-exporter. I'll potentially start that work using my forked version, but I'd rather have it based on the original.

**Comment by jacobbednarz** [comment]
closing this out as it has sat for over 12 months without any movement or action required. do sing out if it is something we still need to consider adding internal tickets for.

**Comment by gofish** [comment]
Note that health monitor notifications were since released and are generally available:

https://developers.cloudflare.com/load-balancing/reference/migration-guides/health-monitor-notifications/
