### ISSUE TITLE
UpdateFallbackDomain should be plural like ListFallbackDomains

### ISSUE THREAD

**Issue by tjstansell** [cloudflare/cloudflare-go#774]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

latest

### Go environment

n/a

### Expected output

The function `UpdateFallbackDomain` should be plural like `ListFallbackDomains` for consistency.  It's a single API endpoint where the entire set of domains is PUT/GET so it should be plural.

### Actual output

n/a

### Code demonstrating the issue

n/a

### Steps to reproduce

n/a

**Comment by jacobbednarz** [comment]
Closing per the comments in cloudflare/terraform-provider-cloudflare#1381

will revisit if the resource is re-jigged.
