### ISSUE TITLE
AccessOrganizationLoginDesign type is incorrect

### ISSUE THREAD

**Issue by trjstewart** [cloudflare/cloudflare-go#775]
### Current cloudflare-go version

v0.30.0

### Description

It looks like the API response for `GET accounts/:identifier/access/organizations` has changed and has not been updated in the [documentation](https://api.cloudflare.com/#access-organizations-access-organization-details), nor here as a result.

According to the docs, the response should be:
``` json
{
  "success": true,
  "errors": [],
  "messages": [],
  "result": {
    "created_at": "2014-01-01T05:20:00.12345Z",
    "updated_at": "2014-01-01T05:20:00.12345Z",
    "name": "Widget Corps Internal Applications",
    "auth_domain": "test.cloudflareaccess.com",
    "login_design": {
      "background_color": "#c5ed1b",
      "text_color": "#c5ed1b",
      "logo_path": "https://example.com/logo.png"
    }
  }
}
```

Actual response is:
``` json
{
  "success": true,
  "errors": [],
  "messages": [],
  "result": {
    "auth_domain": "redacted.cloudflareaccess.com",
    "created_at": "2020-05-15T03:41:02Z",
    "login_design": {
      "background_color": "redacted",
      "logo_path": "redacted",
      "header_text": "redacted",
      "footer_text": "redacted"
    },
    "name": "redacted",
    "updated_at": "2021-01-05T07:20:20Z"
  }
}
```

I know this won't (and shouldn't) be merged till the public docs are corrected. I will put through a PR either way though so that it's ready when they are, and I will also raise a support ticket for the incorrect docs.

### Use cases

Correct types allow responses to be used downstream.

### Potential cloudflare-go usage

```go
The correct type for API response.
```

**Comment by jacobbednarz** [comment]
closed by #776
