### ISSUE TITLE
Search by wildcard in name

### ISSUE THREAD

**Issue by Widmo** [cloudflare/cloudflare-go#779]
### Current cloudflare-go version

0.30.0

### Description

Sometimes it is necessary to filter many results, e.g. in case of a script error there are several hundred results to remove: "_acme-challenge.zzz.yyy". 

You cannot currently use an asterisk in a query, e.g: 

`flarectl dns list --zone="xxx.yy" --type="TXT" --name "_acme-challenge.*"`

```
  ID | TYPE | NAME | CONTENT | PROXIED | TTL
-----+------+------+---------+---------+------
```

And the full search works. 

### Use cases

While we need to find specific record. 

### Potential cloudflare-go usage

```go
flarectl dns list --zone="xxx.yyy" --type="TXT" --name "_acme-challenge.*"
```

**Comment by jacobbednarz** [comment]
thanks for the issue however, at this time we have no plans to extend `flarectl`. this may change in the future but nothing is planned.
