### ISSUE TITLE
[breaking] Proposal: Make Response types private; expose Results only

### ISSUE THREAD

**Issue by elithrar** [cloudflare/cloudflare-go#78]
Exposing `XXXResponse` types clutters the public API and offers minimal (if any) benefit to consumers of the package.

Discussion with @jamesog and @saljam internally leads to this proposal:
- [ ] `XXXResponse` types should be made private
- [ ] We should only expose `Response.Result` - which will be a `*DNSRecord` or `*PageRule`
- [ ] We unwrap the errors from `Response.Errors` and return them.

In addition we should look to standardize on returning/using pointer types, but that could also be tackled in a separate PR/issue.

**Comment by jamesog** [comment]
Having just been toying with trying to get pagination working for DNS, I think we do need to keep the Response types public, or else return ResultInfo (with the page and count info) separately.

**Comment by elithrar** [comment]
@jamesog Returning `ResultInfo` as the second of three params might be the best way.

**Comment by jamesog** [comment]
So, something like this?

```
func (api *API) DNSRecords() (*DNSRecord[], ResultInfo, error)
```

**Comment by elithrar** [comment]
Yep.
