### ISSUE TITLE
Expose the Pages Retry Deployment equivalent API

### ISSUE THREAD

**Issue by TomOnTime** [cloudflare/cloudflare-go#792]
### Current cloudflare-go version

latest

### Description

I'd like to use the API to do the equivalent of clicking the "Retry Deployment" button on:

Pages -> [click on project name] -> View build -> Manage deployment -> Retry Deployment

I think this is the endpoint:

  "https://api.cloudflare.com/client/v4/accounts/{account_id}/pages/projects/{project_name}/deployments";

But it may be:

    POST accounts/:account_id/pages/projects/:project_name/deployments/:deployment_id/retry

### Use cases

Use case: We're building a control-panel that needs to have a "re-generate web site" button.

### Potential cloudflare-go usage

```go
n/a
```

**Comment by jacobbednarz** [comment]
closed by #765
