### ISSUE TITLE
Global option --account-id doesn't work 

### ISSUE THREAD

**Issue by vitich** [cloudflare/cloudflare-go#799]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.31.0

### Go environment

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/cf/.cache/go-build"
GOENV="/home/cf/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/cf/GO/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/cf/GO"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.17/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2361969694=/tmp/go-build -gno-record-gcc-switches"

### Expected output

I only want to see the domain zones of this account.

### Actual output

I see domain zones from all accounts.

### Code demonstrating the issue

flarectl --account-id ******************** zone list

### Steps to reproduce

flarectl --account-id ******************** zone list

### References

Please fix it.
I can't use the app with more than one related accounts.

**Comment by azhonja** [comment]
I tried to play with different account_id but get the same result.
Whichever account_id I used always get zones from all accounts which I have access to.
