### ISSUE TITLE
Potential Breaking Changes

### ISSUE THREAD

**Issue by elithrar** [cloudflare/cloudflare-go#8]
I wanted to discuss these before pushing anything, but I'd like to make some (minor) breaking changes. 

These would be caught on compile for those not vendoring the library, and should be easy fixes, but they'll still 'break' things.

* Change `New()` to return `(*API, error)` and enforce non-empty key/email.
* Add functional options to `New` so that you can change the underlying `http.Client`, global pagination options, and other options in the future - e.g. `func New(key, email string, option ...Option)` where `Option` is a `func (*API) error` ([see here for examples](https://godoc.org/github.com/gorilla/csrf#Option))
* Additionally, and less critically, consider returning slices of pointers - e.g. `[]*DNSRecord` - where relevant.

Any changes would also include updating `flarectl` in the same PR.

**Comment by jamesog** [comment]
That all seems sensible, I've no problem with that at all.

**Comment by elithrar** [comment]
Closed in #10.
