### ISSUE TITLE
Zone: Use time.Time for time fields

### ISSUE THREAD

**Issue by nishanths** [cloudflare/cloudflare-go#80]
In the `Zone` type, use `time.Time` instead of `string` for the `CreatedOn` and `ModifiedOn` fields.

Current:
```
CreatedOn         string   `json:"created_on"`
ModifiedOn        string   `json:"modified_on"`
``` 

Proposed:
```
CreatedOn         time.Time   `json:"created_on"`
ModifiedOn        time.Time   `json:"modified_on"`
```

This would make the `Zone` type similar to `ZoneCustomSSL`, `KeylessSSL`, `PageRule`, etc. that use `time.Time` for time fields.

**Comment by Tenzer** [comment]
The idea was to have dates as `time.Time` types instead of strings, it was changed for existing structs in #68, but we probably forgot to check that on PRs which has come in afterwards.
Please go ahead and make a PR to change it if you don't mind!
