### ISSUE TITLE
Add support for video / stream API

### ISSUE THREAD

**Issue by muhlemmer** [cloudflare/cloudflare-go#811]
### Current cloudflare-go version

v0.32.0

### Description

Please provide the methods for the the [stream](https://developers.cloudflare.com/stream/) API endpoints, like is done for the [Images](https://pkg.go.dev/github.com/cloudflare/cloudflare-go#Image). I've recently included the latter into our project, to great satisfaction, and would like to continue to expand it by hosting videos on CF.

### Use cases

For us, as a starter we would like to use:

- [Direct creator uploads](https://api.cloudflare.com/#stream-videos-create-a-video-and-get-authenticated-direct-upload-url)
- [List videos](https://api.cloudflare.com/#stream-videos-list-videos)
- [Delete video](https://api.cloudflare.com/#stream-videos-delete-video)

### Potential cloudflare-go usage

```go
u, err := cf.CreateStreamDirectUploadURL(ctx, os.Getenv("CLOUDFLARE_ACCOUNT"), cloudflare.StreamDirectUploadURLRequest{
	Expiry: time.Now().Add(30 * time.Minute),
})
```

### References

 #300 (closed by stalebot)
 #393 (closed by stalebot)

**Comment by LockedThread** [comment]
Thank you, I agree
