### ISSUE TITLE
Supporting Cloudflare Tunnels API

### ISSUE THREAD

**Issue by regnaio** [cloudflare/cloudflare-go#831]
### Current cloudflare-go version

v0.34.0

### Description

https://api.cloudflare.com/#cloudflare-tunnel-list-cloudflare-tunnels

There does not seem to be support for Cloudflare Tunnels

### Use cases

https://api.cloudflare.com/#cloudflare-tunnel-list-cloudflare-tunnels

### Potential cloudflare-go usage

```go
https://api.cloudflare.com/#cloudflare-tunnel-list-cloudflare-tunnels
```

### References

https://api.cloudflare.com/#cloudflare-tunnel-list-cloudflare-tunnels

**Comment by jacobbednarz** [comment]
tunnels are supported under [argo_tunnel.go](https://github.com/cloudflare/cloudflare-go/blob/master/argo_tunnel.go)
