### ISSUE TITLE
Allow filtering of Listing Argo/Cloudflare Tunnels

### ISSUE THREAD

**Issue by regnaio** [cloudflare/cloudflare-go#832]
### Current cloudflare-go version

v0.34.0

### Description

[`ArgoTunnels(ctx context.Context, accountID string)`](https://github.com/cloudflare/cloudflare-go/blob/master/argo_tunnel.go#L47) does not allow for filtering of tunnels

Suppose we only want to list non-deleted tunnels. This is possible via the [REST API endpoint](https://api.cloudflare.com/#argo-tunnel-list-argo-tunnels) by providing Optional Parameters, i.e. `accounts/:account_identifier/tunnels?is_deleted=false`

Ideally, there could be a third parameter to `ArgoTunnels(...)` that allows for filtering similar to how Listing DNS Records is handled in `cloudflare-go`, i.e.

[`DNSRecords(ctx context.Context, zoneID string, rr DNSRecord)`](https://github.com/cloudflare/cloudflare-go/blob/master/dns.go#L94) where `rr` allows for filtering the list

### Use cases

https://api.cloudflare.com/#argo-tunnel-list-argo-tunnels
https://api.cloudflare.com/#cloudflare-tunnel-list-cloudflare-tunnels

### Potential cloudflare-go usage

```go
https://api.cloudflare.com/#argo-tunnel-list-argo-tunnels
https://api.cloudflare.com/#cloudflare-tunnel-list-cloudflare-tunnels
```

### References

https://api.cloudflare.com/#argo-tunnel-list-argo-tunnels
https://api.cloudflare.com/#cloudflare-tunnel-list-cloudflare-tunnels

**Comment by jacobbednarz** [comment]
i've added this as a part of the refactor `ArgoTunnels` => `Tunnels`. in order to use this, you'll have to swap to the [`Tunnels` method](https://github.com/cloudflare/cloudflare-go/pull/866/files#diff-0947b7eeb88e90056234fb607c10910044529f657616792b7b18be0c5c957e58R88) when it lands.
