### ISSUE TITLE
Add support for Pages Deployment

### ISSUE THREAD

**Issue by regnaio** [cloudflare/cloudflare-go#854]
### Current cloudflare-go version

v0.36.0

### Description

https://api.cloudflare.com/#pages-deployment-properties

### Use cases

https://api.cloudflare.com/#pages-deployment-properties

### Potential cloudflare-go usage

```go
https://api.cloudflare.com/#pages-deployment-properties
```

**Comment by jacobbednarz** [comment]
there is already a PR open for this. you can follow the progress at #765.
