### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by joshuamsager** [cloudflare/cloudflare-go#859]
### Current cloudflare-go version

0.37.0

### Description

The newest commits that landed it's way into `master` this week would be really nice to have in a new release of the go api. In particular, my team would love to start using https://github.com/cloudflare/cloudflare-go/pull/858

### Use cases

We want to be able to terraform `http_log_custom_fields`. After a new version of https://github.com/cloudflare/cloudflare-go is released, we would be able to update https://github.com/cloudflare/terraform-provider-cloudflare pointing at the new version of the go api.

### Potential cloudflare-go usage

```go
Used via existing Terraform resources
```

**Comment by sbfaulkner** [comment]
cc @jacobbednarz

**Comment by jacobbednarz** [comment]
Releases are fortnightly unless we have security fixes. Please see the last release to estimate the next release.
