### ISSUE TITLE
Add contribution guide to project

### ISSUE THREAD

**Issue by Tenzer** [cloudflare/cloudflare-go#86]
As noted in #85, it would be good if we had a contribution guide on the repository. GitHub has a bit of documentation about it [on the blog](https://github.com/blog/1184-contributing-guidelines), but I'm sure we can find some examples from other projects.

The need that prompted this issue to be created, was that we currently don't have any documentation on the tests being run on all PRs, and suggestions for why they may fail.

**Comment by nishanths** [comment]
[Related (newer) blog post](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by Tenzer** [comment]
Thanks @nishanths, although I'm not sure we're at a point where we need issue and PR templates. I just used the link which popped up first after a quick search.
