### ISSUE TITLE
Ability to access RayID on requests made to the API

### ISSUE THREAD

**Issue by atmosx** [cloudflare/cloudflare-go#867]
### Current cloudflare-go version

0.35.1

### Description

We open a support request on a curious case where an [application](https://github.com/gathertown/casper-3) using the [cloudflare-go](https://github.com/gathertown/casper-3/blob/main/pkg/providers/cloudflare/dnsrecord.go#L9) package got bogus answer from the CloudFlare API. The support team requests the RayID and although the RayID is available when performing `curl` requests as part of the response headers, it's not available via [cloudflare-go](https://github.com/cloudflare/cloudflare-go/blob/master/dns.go#L94-L132).

### Use cases

Help cloudflare support locate a specific request to the API. Our specific use case is DNS requests, but should be added everywhere as it acts as a unique request identifier and is requested by the support team.

### Potential cloudflare-go usage

```go
r, err := client.DeleteDNSRecord(ctx, zoneID, record.ID)
fmt.Println(r.RayID)
```

**Comment by jacobbednarz** [comment]
This is already supported by enabling `Debug` on the client - https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L55 (https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L279)

In the upcoming experimental client, this is also accessible on the `Error` itself - https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare_experimental.go#L317.
