### ISSUE TITLE
TunnelToken missing string return

### ISSUE THREAD

**Issue by regnaio** [cloudflare/cloudflare-go#883]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.39.0

### Go environment

N/A

### Expected output

https://pkg.go.dev/github.com/cloudflare/cloudflare-go@v0.39.0#API.TunnelToken shows the signature:
```go
func (api *API) TunnelToken(ctx context.Context, params TunnelTokenParams) error
```

But this is missing a `string` in its return, which causes lint and build errors in VSCode

---

https://github.com/cloudflare/cloudflare-go/blob/master/tunnel.go#L272 has the correct signature:
```go
func (api *API) TunnelToken(ctx context.Context, params TunnelTokenParams) (string, error)
```

### Actual output

Please see above

### Code demonstrating the issue

Please see above

### Steps to reproduce

Please see above

**Comment by jacobbednarz** [comment]
this is already fixed on `master`; no further action required here
