### ISSUE TITLE
Prop:Question: Enable Always Use HTTPS & Enable Auto Minify & Brotli

### ISSUE THREAD

**Issue by remotejob** [cloudflare/cloudflare-go#893]
### Current cloudflare-go version

v0.39.0

### Description

How after:
cloudflare.ZoneCreateParams{Name: domain, JumpStart: true, Type: "CF-Free"}

Activate:
 Enable Always Use HTTPS & Enable Auto Minify  & Brotli ?

### Use cases

Activate:
 GET zones/:zone_identifier/settings/automatic_https_rewrites
 GET zones/:zone_identifier/settings/minify
 GET zones/:zone_identifier/settings/brotli

### Potential cloudflare-go usage

```go
Activate:
 GET zones/:zone_identifier/settings/automatic_https_rewrites
 GET zones/:zone_identifier/settings/minify
 GET zones/:zone_identifier/settings/brotli
```

**Comment by jacobbednarz** [comment]
see the methods in https://github.com/cloudflare/cloudflare-go/blob/master/zone.go for modifying and managing zone settings.
