### ISSUE TITLE
Change Minify setting don't work 

### ISSUE THREAD

**Issue by remotejob** [cloudflare/cloudflare-go#894]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.39

### Go environment

GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1306410537=/tmp/go-build -gno-record-gcc-switches"

### Expected output

			sett := cloudflare.ZoneSetting{Value: "{\"js\":\"on\",\"css\":\"on\",\"html\":\"on\"}"}

			responseSettings, err := api.UpdateZoneSingleSetting(context.Background(), zId, "minify",sett)
			if err != nil {
				log.Fatal(err)
			}

			log.Println(responseSettings)

### Actual output

Invalid value for zone setting minify (1007)

### Code demonstrating the issue

sett := cloudflare.ZoneSetting{Value: "{\"js\":\"on\",\"css\":\"on\",\"html\":\"on\"}"}
responseSettings, err := api.UpdateZoneSingleSetting(context.Background(), zId, "minify",sett)
if err != nil {
		log.Fatal(err)
}

log.Println(responseSettings)

### Steps to reproduce

sett := cloudflare.ZoneSetting{Value: "{\"js\":\"on\",\"css\":\"on\",\"html\":\"on\"}"}
responseSettings, err := api.UpdateZoneSingleSetting(context.Background(), zId, "minify",sett)
if err != nil {
		log.Fatal(err)
}

log.Println(responseSettings)

### References

PATCH zones/:zone_identifier/settings/minify

**Comment by jacobbednarz** [comment]
you need to pass the `Value` a `map[string]string`; you cannot just pass a JSON-ified string because it will end up passing it through escaped instead of the actual types.

```
api.UpdateZoneSingleSetting(ctx, zoneID, "minify", cloudflare.ZoneSetting{Value: map[string]string{"js": "on", "css": "on", "html": "on"}})
```
