### ISSUE TITLE
DeleteFilters not working

### ISSUE THREAD

**Issue by sbs2001** [cloudflare/cloudflare-go#903]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

master

### Go environment

```
❯ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shivam/.cache/go-build"
GOENV="/home/shivam/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shivam/.asdf/installs/golang/1.18.1/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shivam/.asdf/installs/golang/1.18.1/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/shivam/.asdf/installs/golang/1.18.1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/shivam/.asdf/installs/golang/1.18.1/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3986147942=/tmp/go-build -gno-record-gcc-switches"

```

### Expected output

DeleteFilters should delete filters when there are multiple of them provided

### Actual output

```
time="19-05-2022 22:46:10" level=fatal msg="HTTP status 400: invalid field value: 73d4d593bca54aa6a21f2dbfb261e81a,7631acc1987640f49ef3926440f07e43"
```

### Code demonstrating the issue

https://github.com/cloudflare/cloudflare-go/blob/dcc2147c30e706215e8793c1fc5b3f453eebc80d/filter.go#L199 here all the filter ids are provided separated by commas. 

However the docs https://developers.cloudflare.com/firewall/api/cf-filters/delete/#delete-multiple-filters say to provide each filter id as value to `id` parameter separately.

### Steps to reproduce

Call `DeleteFilters1 with more than one filters.

### References

https://github.com/crowdsecurity/cs-cloudflare-bouncer/issues/96

**Comment by jacobbednarz** [comment]
can you please show the exact Go code you are using here? the values for filter IDs should be a slice of values, not comma separated values.

**Comment by jacobbednarz** [comment]
oh, do you mean the API request itself is joining them and you're getting this error? if so I can chat to the service team and see when this changed as it should still be supported like this.

**Comment by sbs2001** [comment]
@jacobbednarz  yes indeed. For eg doing something like 

```
DeleteFilters(ctx, myZone, []string{"valid_filter_id_1", "valid_filter_id_1"})
```

would produce the error. The problem is because the go lib calls:
```
..../filters?id=<FILTER_ID_1>,<FILTER_ID_2>
```

While the API seems to expect soething like

```
/filters?id=<FILTER_ID_1>&id=<FILTER_ID_2>
```
