### ISSUE TITLE
`Accounts` not working as expected when needed to fetch all accounts

### ISSUE THREAD

**Issue by sbs2001** [cloudflare/cloudflare-go#909]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

master

### Go environment

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shivam/.cache/go-build"
GOENV="/home/shivam/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shivam/.asdf/installs/golang/1.18.1/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shivam/.asdf/installs/golang/1.18.1/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/shivam/.asdf/installs/golang/1.18.1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/shivam/.asdf/installs/golang/1.18.1/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/shivam/work/cs-cloudflare-bouncer/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3327606679=/tmp/go-build -gno-record-gcc-switches"

### Expected output

In older version of this library `api.Accounts(ctx, cloudflare.PaginationOptions{})` used to fetch all the accounts a particular user had access to.

### Actual output

After the update, the function has been changed to `api.Accounts(ctx, cloudflare.AccountsListParams{})` . This particular call doesn't fetch any accounts at all. 

After digging into code it seems that it's appending `name=` parameter to this particular api call with null value. Hence we get no accounts.

### Code demonstrating the issue

api.Accounts(ctx, cloudflare.AccountsListParams{})

https://github.com/cloudflare/cloudflare-go/blob/e5c6a2d8740459c045a4f020b5510a87b29fa548/accounts.go#L60

### Steps to reproduce

Just use `api.Accounts(ctx, cloudflare.AccountsListParams{})`, in latest version. It's not returning all accounts as expected

**Comment by jacobbednarz** [comment]
thanks, addressed by #910

**Comment by sbs2001** [comment]
Thanks for the quick fix. May know when the next release of this library (including this fix) be published ?

**Comment by jacobbednarz** [comment]
it is roughly a fortnightly cadence and we had a release a couple of days ago. in the meantime, you'll need to use the git references if you'd like this change immediately.
