### ISSUE TITLE
Add support for R2

### ISSUE THREAD

**Issue by pkoch** [cloudflare/cloudflare-go#927]
### Current cloudflare-go version

master

### Description

I'd like to have API support for working with R2 bucket. Wrangle has it, so there must be some API-level support already.

### Use cases

I think it's pretty self-evident, but mine is using terraform. See https://github.com/cloudflare/terraform-provider-cloudflare/issues/1664.

### Potential cloudflare-go usage

Sorry, I'm not a Golang developer, I don't have a good clue. :/

**Comment by rgcostea** [comment]
I would also like to see API support for buckets.

**Comment by ghuntley** [comment]
Disappointed to see there's no support for buckets w/terraform.

**Comment by KianNH** [comment]
FWIW, you can use the AWS S3 provider as demonstrated by @Cyb3r-Jak3 in https://github.com/cloudflare/cloudflare-docs/pull/5250/files in the interim

**Comment by imoldfella** [comment]
> FWIW, you can use the AWS S3 provider as demonstrated by @Cyb3r-Jak3 in https://github.com/cloudflare/cloudflare-docs/pull/5250/files in the interim

Sadly this doesn't include extensions. Conditional Put is a killer extension, its amazing that S3 has not supported conditional put. Of course it's not clear at all how to add this header to the s3 PutObject

**Comment by KianNH** [comment]
I'm not sure I follow - are you saying that it's not clear how to use R2's conditional extension to PutObject in general?

**Comment by imoldfella** [comment]
It looks easy! It's just that the options now are 
1. Use the s3 library: easy, but no conditional put and to add it seems to require serious code mangling 
2. More likely, write a ground up PutObject based on http.Client. This seems like a better approach to me, but I haven't undertaken it yet. This requires adding the S3 special headers 

Was just adding my vote for R2 support directly. Being able to use the S3 library is cool, but having easy access to R2 features would be cooler.
