### ISSUE TITLE
UpdateAccessRule: Should it report success when configuration values are provided which aren't supported in a PATCH update

### ISSUE THREAD

**Issue by moogzy** [cloudflare/cloudflare-go#934]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

All

### Go environment

All

### Expected output

An error when passing the following to "UpdateAccessRule" because the Cloudflare API doesn't allow configuration blocks to change you can only update the mode or notes on an access rule via the API.

```
 curl -X PATCH "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/firewall/access_rules/rules/$RULE_ID" \                                                                          
-H "X-Auth-Email: $EMAIL_ADDRESS" \
-H "X-Auth-Key: $AUTH_KEY"  \
-H "Content-Type: application/json" \
--data '{"mode": "whitelist","configuration": {"target": "ip","value": "8.8.8.8"},"notes": "Test"}'
```

### Actual output

The API reported a success even though it ignored the configuration block completely:

```
{
  "result": {
    "id": "<REDACTED>",
    "paused": false,
    "modified_on": "2021-08-11T05:17:34.736351Z",
    "allowed_modes": [
      "whitelist",
      "block",
      "challenge",
      "js_challenge",
      "managed_challenge"
    ],
    "mode": "whitelist",
    "notes": "Test",
    "configuration": {
      "target": "ip",
      "value": "8.8.8.8"
    },
    "scope": {
      "id": "<REDACTED>",
      "name": "example.com",
      "type": "zone"
    },
    "created_on": "2021-08-11T05:17:34.769917109Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

### Code demonstrating the issue

See above examples of calls against the API.

### Steps to reproduce

See above example of call against the API for access rule patch.

### References

No current open issues or PRs. I'd like to understand if the Cloudflare API is WAI here.... as this makes the Cloudflare terraform provider code for access rule management observe a bug relating to access rule updating.

As the API never updates the configuration block but returns a success. The Terraform provider thinks it was successful only to pick up the same resource change next time a plan/apply is run.... rinse and repeat.

I'll open a terraform provider issue once we confirm how the API should behaving here. As I know how to fix the provider (well mostly) but if the API is doing the wrong thing here then I'd rather Cloudflare fix the API first and then we can fix the provider handling.

**Comment by jacobbednarz** [comment]
this behaviour is a little odd, but expected. per the [documentation](https://api.cloudflare.com/#firewall-access-rule-for-a-zone-edit-access-rule) the only parts that are updatable are mode and notes. other than that, you need to recreate the rule.

in terraform-provider-cloudflare, we [trigger new resource creation](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/schema_cloudflare_access_rule.go#L10) when any other resources are changed.

**Comment by moogzy** [comment]
@jacobbednarz do you want me to open an issue in the terraform-provider queue then?

As we're using v3.8.0 of the provider and it does not trigger new resource creation of access rules. It is trying to update them in place and never does so continuously tries to diff/apply because the API ignores the configuration block.

This is why I started the discussion here. If you think this doesn't need to be updated in the API then I'll move this to the terraform provider as an issue there.

**Comment by jacobbednarz** [comment]
if the issue is in the provider, that is the best place to start the conversation. I would recommend ensuring you're on the latest version before submitting an issue and if it is still an issue, then follow the issue template to get it triaged.

**Comment by jacobbednarz** [comment]
a brief skim of the CHANGELOG shows that v3.15.0 may have already addressed this and you just need to upgrade to fix this issue - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#3150-may-18th-2022

**Comment by moogzy** [comment]
Legend thanks for taking a look. I looked at the provider code and didn't see force new yesterday.. hmm. Anywhose... will play around with it and open an issue if required.

Thanks for your help!
