### ISSUE TITLE
Inconstant usage of `time.time` vs `*time.time`

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/cloudflare-go#960]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.4.3

### Go environment

N/A

### Expected output

There is constant use of either `time.time` or `*time.Time` for structs.

### Actual output

It varies between file

### Code demonstrating the issue

`access_application.go`
```go
// AccessApplication represents an Access application.
type AccessApplication struct {
...
	CreatedAt               *time.Time                     `json:"created_at,omitempty"`
	UpdatedAt               *time.Time                     `json:"updated_at,omitempty"`
...
}
```

`account.go`
```go
// Account represents the root object that owns resources.
type Account struct {
	ID        string           `json:"id,omitempty"`
	Name      string           `json:"name,omitempty"`
	Type      string           `json:"type,omitempty"`
	CreatedOn time.Time        `json:"created_on,omitempty"`
	Settings  *AccountSettings `json:"settings,omitempty"`
}
```

### Steps to reproduce

N/A

### References

I can go around and make the changes, just want to know what it should be set to. I have used `*time.Time`

**Comment by jacobbednarz** [comment]
i wouldn't spend time on this at the moment as we'll need to do mass updates to support it across three tools however, the next major version can address this automatically.
