### ISSUE TITLE
flarectl: More output formats: json, yaml

### ISSUE THREAD

**Issue by lukassup** [cloudflare/cloudflare-go#963]
### Current cloudflare-go version

current latest

### Description

Would be nice to have JSON and/or YAML output formats

### Use cases

Having JSON and/or YAML output format option would provide better scripting capabilities

### Potential cloudflare-go usage

```go
n/a - only relevant for cli functionality
```

**Comment by Cyb3r-Jak3** [comment]
flarectl already has JSON export with the `--json` flag.

**Comment by jacobbednarz** [comment]
thanks for the issue however, right now we aren't focusing on expanding `flarectl`s output options. this may change in the future however definitely not in the near term.
