### ISSUE TITLE
Add support for intelligence

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/cloudflare-go#965]
### Current cloudflare-go version

v0.43.0

### Description

Add support for intelligence endpoint

https://api.cloudflare.com/#domain-intelligence-get-domain-details

https://api.cloudflare.com/#ip-intelligence-properties

https://api.cloudflare.com/#asn-intelligence-properties 

### Use cases

Be able to query intelligence cloudflare-go

### Potential cloudflare-go usage

```go
result, err := cloudflare.IntelligenceIP(...)
```

### References

Happy to work on this. Wanted to make sure that the beta status was okay with this project.

**Comment by jacobbednarz** [comment]
as long as we have documented endpoints, I'm 👍
