### ISSUE TITLE
Replace `github.com/pkg/error` with native error wrapping

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/cloudflare-go#968]
Package github.com/pkg/errors is in maintenance mode due to the golang native error wrapping. 

### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

latest

### Go environment

N/A

### Expected output

Switch to 
```go
import "errors"
```

### Actual output

```go
import "github.com/pkg/errors"
```

### References

Issue for K8: https://github.com/kubernetes/release/issues/2549

Probably just use `sed` to replace, but not sure if waiting for experimental client.

**Comment by jacobbednarz** [comment]
this is easy enough with a tool like https://comby.dev/. I think I've already run a rule like this for Terraform so I'll have a look around on Monday to see if I still have it handy.
