### ISSUE TITLE
Programmatically getting an R2 API token

### ISSUE THREAD

**Issue by rgcostea** [cloudflare/cloudflare-go#981]
### Current cloudflare-go version

0.44.0

### Description

When creating an R2 API token through the UI, we get an access key and a secret key.  These can then be used to manage buckets and objects using the aws sdk for s3.  But when trying to use the cloudflare API to create an API token, the resulting "Value" field does not match the expected format of a secret key.  When we try to use that with the aws sdk, it does not work.    

### Use cases

To generate R2 API tokens programmatically that follow the standard secret key format and work with the AWS SDK.

### Potential cloudflare-go usage

```go
No Response
```

**Comment by ferhatelmas** [comment]
@rgcostea you just need to take the sha-256 hash of the value field of the token to be able to use as the secret (id of the token is the access id).

@jacobbednarz we can close this.
